### ISSUE TITLE
Banner non scompare nonostante spunta "Accetta l'informativa sull'evento scroll del mouse"

### ISSUE THREAD

**Issue by Malve** [overclokk/italy-cookie-choices#101]
Ciao innanzi tutto complimenti per il tuo plug-in che è veramente fatto bene ed intuitivo; purtroppo con l'ultimo aggiornamento ho notato come da titolo che la funzione di scroll del mouse per accettazione non funziona... mi sai dire se è un bug conosciuto o se devo fare specifiche impostazioni? ti informo inoltre che fino alla versione precedente funzionava senza problemi e che non ho modificato niente rispetto a prima,il sito web è www.maicakes.it e la versione di wordpress è 4.2.2 grazie mille, Roberto

**Comment by overclokk** [comment]
Ciao @Malve grazie dei complimenti :-), nessun bug conosciuto, provato ora su alcuni siti che gestisco e funziona tutto regolarmente, eventualmente prova a ricaricare via ftp i file del plugin scaricandolo dal repo di WP e vedi se risolvi.

**Comment by Malve** [comment]
Ciao, ho provato ma non cambia niente... purtroppo con lo scroll del mouse il banner rimane, si elimina solo cliccando su accetto....ho provato anche io su altri siti che gestisco ma anche li sempre la stessa storia... ho provato anche a disinstallare il plug-in e a settarlo nuovamente da capo ma non funziona ugualmente lo scroll... per conferma hai provato a vedere il banner sul mio sito web www.maicakes.it se anche a te con lo scroll rimane? eventualmente potrei inviarti degli screenshot delle impostazioni del plug-in ma non vorrei disturbarti ulteriormente....aspetto tue notizie, ci tengo molto al tuo plug-in mi ha risolto completamente la grana della privacy e la funzione scroll è veramente ottima....aspetto tue notizie

**Comment by calamity7** [comment]
Ciao, anch'io ho lo stesso problema entrando e uscendo dalla pagina dell'informativa estesa, rimane bloccato il banner, non succede nulla se clicco ACCETTA e anche non riesco a far comparire i contenuti (Foto con plugin Layer Slider).
Ho provato a inserire nel campo "script da non bloccare", ma me li blocca lo stesso. Il sito è questo  http://www.vinilecenturie.it

Grazie per l'impegno.

**Comment by andreapernici** [comment]
Io cliccando accetta vedo il contenuto.

Hai provato a testare da sloggato?

**Comment by andreapernici** [comment]
Ciao @Malve hai un errore JS

 _gaq.push([‘_gat._anonymizeIp’]);

devi usare le virgolette dritte non quelle oblique.

**Comment by calamity7** [comment]
Si, cliccando Accetta si vede il contenuto, ma se prima di questa azione vai a leggerti la pagina dell'informativa estesa e ritorni alle home, non funzia. E' un giro probabile per un visitatore che vuole leggersi la policy.

**Comment by overclokk** [comment]
@Malve dal codice non vedo attivo lo scroll, nel backend c'è la spunta?

**Comment by andreapernici** [comment]
@calamity7 questo è corretto. La pagina policy non genera l'accettazione perché l'utente ci clicca per informarsi. Dopo essersi informato accetta. Finché non esprime consenso il cookie non viene settato.

**Comment by Malve** [comment]
@overclokk si nel backend c'è la spunta, questi gli screenshot del plug-in:
![schermata 2015-06-25 alle 17 21 38](https://cloud.githubusercontent.com/assets/13048561/8358151/0c040eee-1b5f-11e5-851a-b6120006edc6.png)
![schermata 2015-06-25 alle 17 22 32](https://cloud.githubusercontent.com/assets/13048561/8358152/0c0b3c00-1b5f-11e5-8311-f242909a76a7.png)
![schermata 2015-06-25 alle 17 22 41](https://cloud.githubusercontent.com/assets/13048561/8358153/0c10f51e-1b5f-11e5-9694-9da3b7529dd6.png)
![schermata 2015-06-25 alle 17 22 46](https://cloud.githubusercontent.com/assets/13048561/8358154/0c1577d8-1b5f-11e5-8b12-fb21185a56b3.png)

**Comment by Malve** [comment]
@andreapernici grazie Andrea, ho corretto l'errore delle virgolette...

**Comment by overclokk** [comment]
@Malve la cosa è molto strana, fai questo esperimento, togli la spunta dall'accettazione con lo scroll e qundi salva, poi rimetti la spunta e salva nuovamente.

**Comment by Malve** [comment]
@overclokk ho appena provato ma non cambia niente, con lo scroll non scompare il banner.... stessa cosa anche su altro sito web in costruzione..... cosa mi consigli di fare? sono in un vicolo cieco

**Comment by overclokk** [comment]
Allora dobbiamo fare il debug, segui queste indicazioni e dimmi se cambia qualcosa
https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work

**Comment by Malve** [comment]
@overclokk niente, purtroppo anche con la guida che mi hai riportato non cambia niente....la cosa strana è che fino alla versione precedente funzionava regolarmente,  mi consigli magari di reinstallare la versione precedente?.....

**Comment by Malve** [comment]
@andreapernici per curiosità come hai fatto a vedere l'errore delle virgolette?....non sono espertissimo e vorrei capire

**Comment by Malve** [comment]
@overclokk altra cosa strana che ho notato è che se vado a disinstallare il plug-in quando gli do il comando mi si blocca in una schermata bianca e non permette l'eliminazione del plug-in, quindi se ritorno alle impostazioni del plug-in, il plug-in risulta come di default con tutte le impostazioni da settare.... nonostante ciò dopo aver reimpostato tutte le configurazioni il banner con lo scroll non scompare.
Ho provato quanto sopra perchè volevo provare ad installare la versione precedente ma non facendomi disinstallare l'ultima versione mi rimane impossibile installare la precedente....

**Comment by overclokk** [comment]
@Malve le versioni precedenti le trovi tutte qui https://github.com/ItalyCookieChoices/italy-cookie-choices/releases e devi caricarle via ftp sovrascrivendo quella che hai installata senza fare la procedura di disinistallazione se no cancella le opzioni nel DB

Se riesci prova e fammi sapere.

Però è strano perché su altri siti su cui l'ho installato funziona correttamente, quindi con tutto di default tema compreso cache svuotata non ti funziona?

**Comment by Malve** [comment]
@overclockk domani provo a sovrascrivere con ftp e ti so dire, probabilmente è andato storto qualcosa durante l'aggiornamento in quantomeno come ti ho detto anche se volessi rimuovere il plugin non me lo fa fare in quanto si blocca su una schermata bianca, provo come ho detto domani con ftp e ti faccio sapere, grazie mille dell'assistenza

**Comment by overclokk** [comment]
@Malve la schermata bianca è sintomo di qualche conflitto ma se non si attiva il debug di WordPress non possiamo sapere quale.

**Comment by andreapernici** [comment]
@Malve apri chrome > Ispeziona elemento > Trovi l'errore in console con una X rossa.

**Comment by calamity7** [comment]
Fatal error: Call to undefined function deregister_string() in /web/htdocs/www.vinilecenturie.it/home/wp-content/plugins/italy-cookie-choices/uninstall.php on line 56

Questo è l'errore quando si cerca di cancellare il plugin per reinstallarlo.
Tornando nella sezione plugin di WP, si scopre che non è stato cancellato.

Altra cosa: il plugin mi blocca lo slider anche se l'ho inserito nell'area "Script da non bloccare".

Ps: su altro sito che gestisco problemi zero!!!

**Comment by Malve** [comment]
@calamity7 stesso problema, anche su altro sito web che gestisco....come suggerito da @overclokk più tardi provo a sovrascrivere con ftp e vediamo....

**Comment by Malve** [comment]
@andreapernici grazie per le dritte!

**Comment by Malve** [comment]
@overclokk allora ho disinstallato tramite ftp il plug-in per poi reinstallarlo e configurarlo ma non cambia niente, su altro sito che gestisco ho disattivato tutti i plug-in e attivato solo Italy cookie ma il banner con lo scroll non va via, ho installato manualmente la versione 2.1.0 e con questa versione il banner con lo scroll SCOMPARE REGOLARMENTE.... quindi è sicuramente qualcosa della versione 2.2.0 che impedisce il regolare funzionamento dell'opzione scroll, grazie per il sostegno

**Comment by overclokk** [comment]
@calamity7 quel problema è strano visto che la funzione c'è, comunque faccio dei test per capire meglio

@Malve per caso la input slug è vuota?

**Comment by Malve** [comment]
@overclokk è così: 
![schermata 2015-06-26 alle 13 42 32](https://cloud.githubusercontent.com/assets/13048561/8376611/5378366a-1c09-11e5-94b8-090e46891553.png)

**Comment by overclokk** [comment]
@Malve prova ad inserire lo slug dell'informativa

**Comment by Malve** [comment]
ADESSO FUNZIONA PERFETTAMENTE!!! ho inserito l'url della pagina del cookie policy, grazie mille @overclokk

**Comment by overclokk** [comment]
Ovviamente non riuscivo a capire perché io lo avevo settato su tutti i siti e quindi funzionava :-)

Ora è da valutare se mettere come obbligatorio lo slug o fare una check anche per questa input nella if della variabile $scroll

**Comment by Malve** [comment]
@overclokk Grazie ancora per lo splendido lavoro e l'assistenza continua.... adesso aggiorno anche l'altro sito dove avevo bloccato l'aggiornamento a 2.1.0.....Di nuovo complimenti per tutto!
edit: aggiornato anche l'altro mio sito web ed inserendo l'url della cookie policy nella sezione slug il banner con lo scroll scompare regolarmente!!

**Comment by overclokk** [comment]
Grazie a te :-)

**Comment by overclokk** [comment]
Ho deciso di settare la variabile con un valore dummy in caso lo slug non sia presente.
