### ISSUE TITLE
Problema di visualizzazione con tema custom

### ISSUE THREAD

**Issue by umpire274** [overclokk/italy-cookie-choices#102]
Ciao a tutti.
Ho scaricato, installato, attivato e configurato il vostro plugin (2.2.0) in un sito Wordpress 4.2.2 che usa un tema interamente custom.
Purtroppo non riesco a vedere il banner in nessuna modalità, top bar, dialog o bottom bar.

Ho provato con il tema standard "Twenty Eleven" e tutti i plugin che uso attivi e il banner si vede.
Mi potete aiutare?

Grazie,
Alex.

**Comment by andreapernici** [comment]
Linkaci il sito grazie.

**Comment by umpire274** [comment]
http://www.previti.it

**Comment by andreapernici** [comment]
Sei sicuro di aver attivato il plugin?

Io non vedo il codice del plugin. Forse nel tuo tema non utilizzi le funzioni che permettono l'inserimento di hook come wp_head etc etc....

**Comment by umpire274** [comment]
Sono sicuro di averlo attivato (check Display banner for Cookie Law in front-end ).
Comunque adesso l'ho installato localmente da me, prima di andare in produzione volevo fare dei test.
Questo tema l'ho preso in gestione e credo che abbia la limitazione circa l'inserimento di hook come pensi perché anche nel codice html generato qui localmente non c'è traccia del codice del plugin: cosa che invece trovo se attivo uno dei temi standard di WP, ad esempio Twenty Eleven.

**Comment by andreapernici** [comment]
Allora aggiungi wp_head e wp_footer e dovrebbe funzionare.

**Comment by umpire274** [comment]
Grazie Andrea. Risolto. Mancava il wp_footer nel footer.php
Ancora complimenti.
