### ISSUE TITLE
Feedburner: Errore interpretazione XML: contenuto illegale dopo l’elemento

### ISSUE THREAD

**Issue by overclokk** [overclokk/italy-cookie-choices#103]
> Errore interpretazione XML: contenuto illegale dopo l’elemento
> Indirizzo: http://feeds.feedburner.com/wrpgames
> Riga numero 1, colonna 66:

Errore strano segnalato da un utente sul mio sito link http://www.overclokk.net/italy-cookie-choices-wordpress-plugin/comment-page-1#comment-34225

Da quello che mi ha detto ha provato tutte le procedure di debug da me consigliate ma nulla.

Da approfondire meglio.

**Comment by floryn90** [comment]
Ciao @overclokk! Dai un'occhiata al codice sorgente della pagina che hai indicato e vedrai che c'è del codice del plugin nella generazione del feed rss. il codice a quanto pare viene impostato nel file class-italy-cookie-choices-front-end.php presente in classes e più precisamente alla riga 672

**Comment by overclokk** [comment]
Ciao @floryn90 si, quello l'ho visto ma appunto quello è il codice che serve per mostrare il banner, l'unica soluzione è disabilitarlo nei feed

**Comment by floryn90** [comment]
Enea, ma per caso hai apportato qualche modifica al file in questione? mi sono impostato un'ambiente di sviluppo per testare tale bug ma a me funziona bene. potresti eventualmente chiedere qualche info in più alla persona interessata in modo da replicare tare bug?

**Comment by overclokk** [comment]
Nessuna modifica particolare, ha comunque (così mi ha detto) eseguito tutte le istruzioni per verificare che non ci sia nessuna incompatibilità e continua ad avere con quell'errore, ad ogni modo il banner nei feed non serve ed eventualmente posso integrare un'opzione per disattivarlo.

**Comment by overclokk** [comment]
Con la versione 2.3.3 problema dovrebbe essere risolto
