### ISSUE TITLE
Problema con il consenso sull'evento scroll del mouse

### ISSUE THREAD

**Issue by francescoIme** [overclokk/italy-cookie-choices#104]
Ciao,
ho installato il plugin sul sito http://www.quando.net/
ma non riesco a capire come mai non funziona il consenso con lo scroll del mouse.
Chiaramente nelle impostazioni la voce "Accetta l'informativa sull'evento scroll del mouse" è spuntata.

Riuscireste ad aiutarmi a capire dov'è il problema???

**Comment by andreapernici** [comment]
A me funziona.

Che browser usi?

**Comment by overclokk** [comment]
Duplicato con #101 continuiamo di la
