### ISSUE TITLE
bloccare i bottoni di condivisione?

### ISSUE THREAD

**Issue by allegra2014** [overclokk/italy-cookie-choices#105]
Ciao, 
prima di tutto mi accodo ai complimenti degli altri.
Il plugin blocca sì i contenuti terzi, ma lascia caricare i bottoni di sharing (uso l'opzione Condividi di Jetpack, ma anche con AddThis la musica non cambia: i bottoni appaiono sempre. Solo con Addtoany c'è una piccola differenza: appare il banner con il blocco, ma subito sotto i bottoni, che si vedono comunque...). 
Non sono un tecnico quindi se possibile mi servirebbe una soluzione "facile" o almeno un po' spiegata in modo semplice...
Grazie!

PS: uso ultime versioni plugin, WP e php

**Comment by overclokk** [comment]
Ciao @allegra2014 e grazie dei complimenti :-)
qui trovi la soluzione più semplice che conosco https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/Custom-script

**Comment by allegra2014** [comment]
Grazie della risposta in diretta! 
Avevo già provato, ma non so dove sbaglio. Avrei inserito gli script nello spazio "Script da bloccare" della configurazione del plugin, ma non succede niente... Li mando in allegato se può aiutare ad aiutarmi .. :-) 

![script](https://cloud.githubusercontent.com/assets/13089151/8397740/f0484d36-1dd5-11e5-85dd-a59b7727c42e.jpg)

**Comment by overclokk** [comment]
Hai copiato il codice così come lo hai trovato nel sorgente della pagina?
Hai provato ad inserire uno script alla volta e provato se funziona?

**Comment by allegra2014** [comment]
Copiato e incollato. 
Ho provato anche uno script alla volta.

Ma vedo che negli esempi, sia nella pagina di configurazione che alla pagina https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/Custom-script si cita sempre un formato di script del tipo //**<script>** oppure **<script src**, mentre io ho degli **<script type**... //

**Comment by overclokk** [comment]
Blocchiamone uno alla volta, prova con questo snippet:

`<script type="text/javascript"><---------SOMETHING--------->pinterest<---------SOMETHING---------></script>`

Prima guarda il sorgente e cerca pinterset, quando lo hai bloccato ricontrolla e dimmi se vedi ancora lo snippet, è l'ultimo dell'immagine che hai postato sopra.

**Comment by allegra2014** [comment]
Se ho capito bene: cerco Pinterest sul sorgente (da riga 626), poi inserisco nel plugin il codice tuo, salvo e riguardo il sorgente. 
Beh, ora Pinterest a quella riga non c'è più, e al suo posto inizia il codice del banner di ICC

**Comment by allegra2014** [comment]
il bottone però appare comunque, ok?

**Comment by overclokk** [comment]
Bene, se non c'è più allora funziona, ora fai la stessa cosa con tutti gli altri snippet, uno alla volta e controlla sempre se viene bloccato.

**Comment by andreapernici** [comment]
Ci linki il sito?

Magari il bottone viene caricato in locale come immagine.

**Comment by allegra2014** [comment]
Ciao Andrea, questa è la pagina che sto controllando http://www.turismoslovacchia.it/?p=5504. (non la home page che non ha né video YT né bottoni di condivisione

Ciao Enea, ho provato ad esempio a inserire lo snippet per facebook. Se vedo bene, dal sorgente sembrerebbe che non cambi nulla: anche con un solo snippet tutti gli script di condivisione (quelli postati ieri nell'immagine più sopra) appaiono inglobati nel codice del plugin ICC da riga 624 in poi (vedi sopra link pagina per controllare se ho visto bene)

Grazie a entrambi!

**Comment by overclokk** [comment]
@allegra2014 a parte i cookie di analytics non ne vedo altri, i bottoni non installano cookie e non serve bloccarli.

**Comment by allegra2014** [comment]
oopss... ma avevo letto qui e là che "tutti" i pulsanti di condivisione sarebbero da bloccare in ogni caso. Allora sorry :-/   Analytics cmq è stato anonimizzato, direi

**Comment by overclokk** [comment]
Bisogna sempre verificare quanto si legge, lo puoi fare anche tu, con chrome CTRL + SHIFT + i  quindi vai nella tab resources > cookie e verifichi cosa viene installato, se non li conosci copia a incolla su google il nome del cookie e vedi di cosa si tratta.

**Comment by andreapernici** [comment]
Infatti non vedo alcun cookie di pinterest.

I bottoni li vedi perché quel plugin usa immagini locali per i bottoni.

**Comment by allegra2014** [comment]
Beh, grazie a tutti e due. 

@overclokk  Questa cosa non la capisco. Nel tab resources > cookie non appare nessun cookie anche senza il plugin ICC, ovvero dopo aver accettato il loro uso, malgrado nella pagina ci sia ad esempio un video Youtube. Anche in altre pagine dove ci sono altri contenuti bloccati con il plugin, sbloccandoli non appaiono cookie... Mentre il sito secondo quanto risulta da Chrome Impostazioni / Cookie e dati dei siti, usa diversi cookie

**Comment by andreapernici** [comment]
Hai cliccato nel Cookie giusto?
