### ISSUE TITLE
Dimensioni elementi banner superiore

### ISSUE THREAD

**Issue by kkri** [overclokk/italy-cookie-choices#106]
Ciao.
In questo sito http://www.kemicreazioni.it/ volevo formattare il banner (topbar di default con margine), soprattutto la dimensione del testo, l'altezza della riga ecc. e comunque ridurla un po'. Ho usato il mio child css perchè non ho capito bene come si usa il css del plugin (come deve essere scritta la sintassi), comunque scrivendo come sotto, mi rimane uno spazio bianco sotto il banner che non riesco a togliere. Attualmente ho rimesso la formattazione originale. Mi diresti come fare? Nell'immagine è quello lilla. Grazie.
# cookieChoiceInfo {

```
color: #000;
text-align: left;
font-size: 0.9em;
line-height: 1.3em;
```

}

![banner](https://cloud.githubusercontent.com/assets/6691744/8398822/2b7c1f22-1dfe-11e5-94d0-7379d8023c99.jpg)

**Comment by overclokk** [comment]
Ciao @kkri 
parti dal CSS che vuoi modificare (nel tuo caso quello con i bottoni piccoli), lo copi dal sorgente della pagina e lo incolli nella textarea apposita e fai le modifiche che ti servono quindi nella select box (menù a tendina) selezioni custom CSS e salvi.

Che nel tuo caso è questo:

```
#cookieChoiceInfo{background-color: #c9c9c9;color: #000;left:0;margin:0;padding:4px;position:fixed;text-align:left;top:0;width:100%;z-index:9999;}.contentStyle{max-width:980px;margin-right:auto;margin-left:auto;padding:15px;}.italybtn{color:#000;padding:3px 7px;font-size:14px;line-height:14px;text-decoration:none;text-transform:uppercase;margin:10px 20px 2px 0;letter-spacing: 0.115em;display:inline-block;font-weight:normal;text-align:center;  vertical-align:middle;cursor:pointer;border:1px solid #000;background:rgba(255, 255, 255, 0.03);}.consentText{display:block}
```

PS: Se riesci ad inserirlo minificato nella text box sarebbe l'ideale

**Comment by kkri** [comment]
Bellissimo, grazie! Guarda carino http://www.kemicreazioni.it/  L'ho minificato con un tool online, io non so fare ... Alcune cosine, ma si tratta di dettagli, più o meno... Dimmi tu se sono cose possibili e/o troppo onerose, ma soprattutto conformi alla normativa:
1) la diversificazione in 2 classi tra il bottone "accetto" e quello "informativa" la farei a monte nel plugin, poi se uno vuole, li diversifica altrimenti si arrangia (io non avevo capito subito come fare dal pannello del plugin, ma non sono così tecnica. Dai commenti che leggo molti sono meglio di me, ma per fortuna qualcuno mi batte ...);
2) se l'utente arriva sul sito, vede il banner, prima di accettare vuole leggere l'informativa, clicca e ci va, ma se si è impostata l'accettazione anche con la sola navigazione, vale come accettazione e il banner sparisce. Dovrebbe poter leggere la pagina senza che questo significhi che accetta. Sbaglio ad impostare qualcosa?
3) si può mettere una x intesa come "chiudi" (il banner), in modo che l'utente possa scegliere di navigare il sito senza cookies e beccarsi tutti i warnings dove sotto in realtà ci sono gli elementi nascosti?
4) si possono avere sotto forma di shortcodes i bottoni "accetto",  "informativa", "chiudi" e anche "cancella tutti i cookies" (quest'ultimo mi dicevate fosse particolarmente semplice da fare) in modo che:
a) "accetto e informativa" si possano inserire nel banner nella posizione preferita (prima uno o l'altro a seconda di come si aggiungono gli shortcodes);
b)  "accetto", "chiudi" e "cancella tutti i cookies" si possano inserire anche nell'informativa estesa così i visitatori possano fare le operazioni anche da lì.
Grazie 1000 per quello che potrete fare.

**Comment by overclokk** [comment]
Ottimo :-)

1) se li vuoi diversificare inserisci due classi differenti negli appositi input sotto il custom CSS
2) devi inserire lo slug dell'informativa nell'apposito input
3) Meglio che l'utente veda sempre il banner così sa che se non lo vuole più vedere deve accettare i cookie
4) Lo shortcode per l'accettazione c'è già https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/Shortcode che è l'unico che ha bisogno di eseguire la funzione di accettazione, quello dell'informativa è un link.

a) e b) se si farà sarà molto più semplice ;-)

Comunque la cancellazione dei cookie meglio farla dal browser

**Comment by kkri** [comment]
Hi.
1) io l'ho fatto già, dicevo che per essere più dummy proof, tanto valeva prevederlo a monte nel setup del plugin, senza che debba farlo l'utente (dummy);
2) l'avevo messo, comunque ho provato e riprovato, ho cambiato anche pagina e slug, ma non me lo fa vedere. Adesso ho tolto la spunta dell'accettazione con la navigazione e funzia. per me va bene  anche così: l'accettazione adesso è con il bottone accetto e con lo scroll, non basta? Il Garante vuole anche quella con la navigazione obbligatoriamente?
3) non mi sono spiegata: quella che dicevo è un'opzione che attualmente non c'è, quella di poter scegliere di navigare un sito senza cookie e, naturalmente, senza poter vedere molti elementi della pagina. Non so se è una possiblità che si deve dare: per logica mi sembra di sì, per legge non so. Attualmente gli stiamo dicendo: il sito usa i cookies, o acconsenti o vai a casa tua (facendo attenzione a non inciampare nella rotellina del mouse, perchè appena la muovi, lo scroll ti fulmina ...) Se l'utente volesse vedere il sito senza pubblicità e accessori vari? Glielo proibiamo e basta?
4) ok! non l'avevo visto. Adesso l'ho provato e ho visto che sparisce una volta accettato, ma a quel punto non sarebbe logico sostituirlo con quello della cancellazione? Gli altri shortcodes, anche se sono links, era solo per poterli posizionare (dx o sx) o poterli inserire in una pagina
4 a e 4 b - erano solo le possibilità derivanti dal punto 4 che si possono sfruttare potendo maneggiare le varie funzionalità sotto forma di shortcode.
"la cancellazione dei cookie meglio farla dal browser": immagino che il 95% dei visitatori non sappia dove mettere le mani, ma se va bene a tutti ... che si debba fare dal browser, va bene anche a me. 
Grazie, ciao.

**Comment by overclokk** [comment]
1) Di base i due link hanno lo stesso stile e duplicare il codice in due classi diverse non ha senso
2) DI base deve funzionare, puoi indicare una url per provare?
3) Se non vede il banner poi pensa che lo stiamo truffando :-) (anzi, il banner se lo merita :-P)
4) a b nell'informativa estesa basta indicare all'utente come cancellare i cookie, gli altri link li puoi mettere comunque dove vuoi usando la sintassi di un link `<a herf="">link</a>` per questo non serve uno shortcode, ricorda sempre che le performance sono più importanti.

**Comment by kkri** [comment]
1)  ho dovuto creare anche la seconda classe per differenziare la formattazione, v.sito
 2) Urk. adesso funziona, forse avevo fatto impazzire il browser... Verifica anche tu per piacere http://www.kemicreazioni.it/
 3) dicevo sia il banner che il "chiudi". Solo che ho visto adesso per esempio su GialloZafferano che chiudere in realtà è l'ennesimo modo per dare il consenso, quindi non importa, bastano e avanzano gli altri 3 modi, purchè non sia obbligatorio anche quello.
 4) "accetto" e "cancella tutti i cookies" non sono links no?. Se sì, dimmi come posso fare ad usarli come links!!. :)

**Comment by overclokk** [comment]
1) è così che funziona
2) c'è ancora qualcosa che non funziona correttamente
3) valuteremo
4) accetto è un link, cancella non c'è
Baste che guardi il sorgente del pulsante e lo copi dove vuoi, però se per caso dovessi (io o noi) cambiare il modo in cui avviene l'accettazione il tuo link non funzionerebbe più, comunque basta che guardi il sorgente del tuo bottone e copi lo snippet.

**Comment by kkri** [comment]
1) ok, allora ho fatto bene
2) no, infatti non funziona. come posso fare? allego screenshot delle impostazioni
3) no, non importa a meno che non sia necessario per la normativa
4) per "accetto" uso lo shortcode, visto che c'è.
![ss-icc-setup-3006](https://cloud.githubusercontent.com/assets/6691744/8420333/a67112e6-1ec1-11e5-801a-8088d5922d3f.jpg)

**Comment by overclokk** [comment]
2) segui questi passi e dimmi se cambia qualcosa https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work

**Comment by kkri** [comment]
Ciao Enea.
Mannaggia, immaginavo che fosse un problema molto più semplice. Adesso il banner si vede nella pagina della policy (prova, per piacere), ma bastava mettere uno slash prima e uno dopo dello slug della pagina sulla privacy nelle impostazioni del plugin (/privacy-e-cookie/)! Nel campo apposito non si vede, anche perchè se uno prova a vedere la fine del testo di esempio, il placeholder sparisce e lascia il campo in bianco. E' da stamattina che disattivo plugin, riattivo, cancello dei temi vecchi, stavo per reinstallarne un'altra versione ecc., poi ho pensato a quel campo, che era quello deputato ad attivare quella funzione specifica. Anyway, adesso è a posto.
Procedo con gli altri siti, questo doveva essere tra i più lisci ... ;)
p.s. in un sito in "3 lingue" che però usa il traduttore di Google Translate, quindi traduce al volo le pagine, l'unico modo è mettere nel banner 3 righe di informativa nelle 3 lingue e poi dare un nome "internazionale" ai bottoni (es. info e ok) mandandoli nella stessa pagina dove per ogni lingua ci deve essere sia sezione privacy che cookies? Thank u

**Comment by overclokk** [comment]
Qui una spiegazione su cosa sono gli slug http://codex.wordpress.org/Glossary#Slug

Nello slug non vanno inseriti gli /

Nella prossima release ho allargato la input

Traduttore automatico = brutta cosa
Detto questo direi che quella sia l'unica soluzione

**Comment by kkri** [comment]
Slug: infatti all'inizio non avevo minimamente pensato di metterli, ma, appena messi, il banner ha funzionato. Hai provato tu senza o con? Spero che continui a funzionare, no?;
Input: invece dello slug non si può usare la URL? Lì uno avrebbe meno dubbi, farebbe un copia/incolla e non sbaglia di sicuro;
Traduttore: lo so, però devo farlo su quello.
Grazie, ciao.

**Comment by overclokk** [comment]
Slug: farò ulteriori test
Input: lo slug è più pratico, devo solo migliorare la documentazione per come usarlo

Intanto ho fatto l'upload di una nuova versione 2.2.1 con alcuni bugfix, se la vuoi provare

**Comment by kkri** [comment]
Input: se posso proporre, dalla parte dei dummies ;) "Inserisci lo slug della tua pagina dell'informativa sui cookie (e.s. per la pagina http://www.miodominio.it/privacy-e-cookie/ lo slug da inserire è privacy-e-cookie ). Saranno visualizzati solo la topbar, lo scroll e l'accettazione durante la navigazione che il plugin disattiva appositamente solo in quella pagina."
Installata la versione nuova grazie, in questo sito per il momento non mi cambia niente.
C'entra niente sotto il mio commento il riferimento all'issue #111 ?

**Comment by overclokk** [comment]
Input: Si, posso aggiungerla nella traduzione, grazie

Con la issue sto facendo dei test, non so se sia correlata.

**Comment by overclokk** [comment]
@kkri appena caricata la 2.2.2 con la descrizione da te consigliata, mi sono permesso di cambiare solo qualche parola mantenendo la forma.

**Comment by kkri** [comment]
Grazie, Enea. Onorata di avere qualche parolina mia nel tuo plugin! ;)
Per aggiornare aspetto che le mo segnali sulla bacheca di WP, no?

**Comment by overclokk** [comment]
Si esatto.
Poi vedo di capire come risolvere l'altro problema

**Comment by kkri** [comment]
Come non detto, mi faceva vedere l'aggiornamento nella sezione dei plugins e non in alto, vicino alla voce Bacheca, poi mentre lanciavo l'aggiornamento mi è apparso anche il warning dell'aggiornamento, boh. Anyway adesso funzia! 
L'altro problema #111 io non ce l'ho, l'aveva segnalato un altro utente e github lo evidenzia anche nella pagina dove stiamo scrivendo io e te, ari-boh ... :)
p.s. sempre per la questione dummy-proof dello slug: non vorrei mai che qualcuno ci metta anche la parentesi e il punto, visto che sono attaccati allo slug... ahahahhaha (tutto è possibile con noi utenti!)
DIDASCALIA:
 ...  lo slug sarà privacy-e-cookie).

**Comment by overclokk** [comment]
Visto che lo avevo appena caricato è normale, c'è la cache anche in quello :-)

Per il 111 non ti preoccupare, serve a me come appunto.

Ma si vede, lo slug è in grassetto la parente (Cit. Totò) no :-)

**Comment by kkri** [comment]
Slug: ricorda la legge di Murphy! ...

**Comment by overclokk** [comment]
Direi di aver risolto con la versione 2.3.0
