### ISSUE TITLE
Accettazione tramite scroll

### ISSUE THREAD

**Issue by alessandrocaputo** [overclokk/italy-cookie-choices#107]
Salve!
Ho installato sul mio blog il vostro plugin e ho riscontrato un problema(?)
Ho notato che l'accettazione tramite scroll funziona correttamente se ci si trova sulla Home Page del sito. Ma nel caso in cui si dovesse arrivare al sito tramite una pagina secondaria o un articolo, l'accettazione tramite scroll non funziona.
Chiedo quindi come poter ovviare a questo problema.

Saluti,
Alessandro Caputo

**Comment by overclokk** [comment]
Ciao, potresti indicare un link per vedere?
