### ISSUE TITLE
Si può usare questo plugin per i commenti social?

### ISSUE THREAD

**Issue by IvanPsy** [overclokk/italy-cookie-choices#108]
Se volessi inserire i commenti social (es. G+ o FB con plugin quali Comments Evolved), questo plugin può bloccarne preventivamente i cookie?

**Comment by overclokk** [comment]
Ciao, il plugin blocca tutto quello che è script, embed e iframe dentro il body, footer e header vanno bloccati inserendo lo snippet nell'apposita textarea https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/Custom-script
