### ISSUE TITLE
La barra non è visibile

### ISSUE THREAD

**Issue by Pr1zma3** [overclokk/italy-cookie-choices#109]
Ciao

su un sito che sto costruendo la barra in backend si vede ma in frontend no.
Ho ricontrollato tutti le voci e cancellato la cache, provato da diversi browser ma il problema rimane.
potete aiutarmi
grazie
mARZIA

**Comment by overclokk** [comment]
Ciao @marziadimeo il primo passo da fare è seguire questa guida https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work e poi mi dici cosa cambia, ad ogni modo nel backend la barra non si deve vedere.

**Comment by Pr1zma3** [comment]
Perfetto risolto.
Ho cancellato tutti i plugin che potevano bloccare (non so dirti quale 
nello specifico) e cancelalto olte ai cookie anche al cache!
Ora va bene
grazie
Mz

Il 30/06/2015 14:19, Enea ha scritto:

**Comment by overclokk** [comment]
Perfetto :-)
