### ISSUE TITLE
Fatal Error quando si disinstalla il plugin

### ISSUE THREAD

**Issue by nicolabavaro** [overclokk/italy-cookie-choices#110]
In una installazione Wordpress aggiornata riscontro questo errore quando cerco di eliminare il plugin:

Fatal error: Call to undefined function deregister_string() in /home/xxxxxx/public_html/xxxxxx/wp-content/plugins/italy-cookie-choices/uninstall.php on line 56

**Comment by overclokk** [comment]
Ciao @nicolabavaro è un errore già conosciuto e il fix sarà disponibile alla prossima release.

**Comment by overclokk** [comment]
Con la 2.2.1 bug risolto

**Comment by nicolabavaro** [comment]
Perfect :+1:
