### ISSUE TITLE
Con WP in sotto directory lo slug non fa il match con 'REQUEST_URI'

### ISSUE THREAD

**Issue by overclokk** [overclokk/italy-cookie-choices#111]
Facendo alcuni test nella mia installazione in locale lo slug inserito non fa il match con `$_SERVER['REQUEST_URI']` e quindi l'accettazione alla seconda visita non funziona più, non ho provato in un sottodominio e non vorrei che ci possa essere una concausa anche per questo problema #106

**Comment by acardinale** [comment]
Non è possibile che "l'accettazione alla seconda visita non funziona più", se non matcha al massimo quando si clicca sul link dell'informativa viene accettato come se fosse una seconda visita.

**Comment by overclokk** [comment]
Ok, scusa, non ci sto con la testa :-)
Volevo dire che non fa il match con lo slug e quindi scroll e second view non vengono disattivati per quella pagina.

**Comment by acardinale** [comment]
Come posso testarlo?
Basta una installazione in sottodirectory?
ossia con **define('PATH_CURRENT_SITE', '/miadirectory/');** ?

**Comment by overclokk** [comment]
Directory e sottodominio

**Comment by acardinale** [comment]
Dunque si verifica solo con entrambe le condizioni?

**Comment by overclokk** [comment]
ho provato una e l'altra, non insieme

**Comment by acardinale** [comment]
Allora non "Directory e sottodominio" ma Directory **o** sottodominio ;)

**Comment by overclokk** [comment]
e/o :-P

**Comment by overclokk** [comment]
Appena ho un attimo aggiungo anche lo slug per il multilingua #115
