### ISSUE TITLE
Possibilità di settare la scadenza

### ISSUE THREAD

**Issue by giovvila** [overclokk/italy-cookie-choices#112]
Sarebbe utile che ad ogni apertura del sito chiedesse l'accettazione dei cookies (nel caso di uso del medesimo computer da più utenti)

**Comment by overclokk** [comment]
E noi come facciamo a sapere chi sta usando il computer in quel momento?

**Comment by giovvila** [comment]
Chiedevo solo se era possibile settare la richiesta di accettazione ad ogni accesso  del browser nella pagina del sito o una volta al giorno
.

**Comment by overclokk** [comment]
La richiesta viene mostrata solo se non è stato ancora settato il cookie, quando accetti come fai a mostrare nuovamente la richiesta visto che il cookie è già presente?

**Comment by giovvila** [comment]
ok, grazie

**Comment by overclokk** [comment]
L'unico modo sarebbe che l'utente cancellasse i cookie appena finita la sua sessione.

**Comment by andreapernici** [comment]
Il browser può essere istruito per farlo, ma non ha senso.
