### ISSUE TITLE
Non appare più la TopBar o il PopUp in Firefox dopo upgrade da 2.1.0 a 2.2.1

### ISSUE THREAD

**Issue by micdalco** [overclokk/italy-cookie-choices#113]
Ciao a tutti,
   se eseguo l'upgrade di italy-cookie-choices alla versione più recente non appare più la topbar in Firefox. In Chrome invece continua a funzionare e sono visibili le nuove personalizzazioni di tema.
   Il sito è www.annabaiguera.com. Ho provato a disattivare i plugin che potevano interferire e a disattivare tutte le cache presenti, ma non ho potuto mettere il tema standard, perché si tratta di un sito in produzione.
   Ho provato a disinstallare completamente il plugin e a riconfigurarlo, senza risultato.
Facendo il downgrade alla 2.1.0 è tornato regolarmente visibile.

Grazie,
Michele

**Comment by overclokk** [comment]
Ciao @micdalco 
Quindi hai già seguito questi passaggi https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work ?

**Comment by kkri** [comment]
Neanche a me si vede con l'ultima versione del plugin. Solo in FF, in IE e Chrome va bene. www.kemicreazioni.it

**Comment by micdalco** [comment]
Salvo l'ultimo punto (Se non funziona riattiva il tema standard e riprova) sì.
Per eseguire quest'ultimo test dovrò copiare il sito in locale.
Speravo il problema fosse altrove, dato che sto usando questo plugin, senza variazioni al tema, fin dalle prime versioni e fino alla 2.1 è funzionato (e funziona!) correttamente con tutti i browser.
E' evidente che con le ultime modifiche che avete apportato qualche incompatibilità sia stata introdotta.
Dovesse esservi effettivamente incompatibilità col tema implementerò il popup manualmente direttamente nel tema.
Grazie comunque.

**Comment by micdalco** [comment]
Ho avuto analogo comportamento al sito di kkri: barra vuota dopo l'upgrade.
Poi dopo aver disinstallato e reinstallato il plugin e aver disattivato gli altri plugin la barra non è più apparsa, nemmeno vuota.
Rimettendo la 2.1.0 riappare immediatamente barra e testo.
Ripeto: problema verificato esclusivamente in Firefox.

**Comment by overclokk** [comment]
Provate questo sito e ditemi se vedete lo stesso problema http://demo.italystrap.it/

**Comment by kkri** [comment]
Provato: con Chrome vedo il banner mentre con FF lascia lo spazio ma non la fa vedere.

**Comment by overclokk** [comment]
ok, già capito il problema, entro breve carico un nuovo aggiornamento con il fix

**Comment by kkri** [comment]
Mi sembra che FF sposti il banner in fondo, ma faccio fatica a ederlo perchè con lo scroll me la toglie subito ...

**Comment by overclokk** [comment]
Anzi, prima provate a visitare nuovamente la url di prima e ditemi se è cambiato qualcosa (ovviamente pulizia cache e cookie è d'obbligo)

**Comment by kkri** [comment]
funzia!

**Comment by overclokk** [comment]
Ok, allora intanto carico questo fix così lo risolviamo subito

**Comment by micdalco** [comment]
Confermo, l'unltima versione funziona correttamente!

**Comment by overclokk** [comment]
Appena caricata la 2.2.2 con il fix, datemi conferma se funziona :-)

**Comment by micdalco** [comment]
Aggiornato. Ti confermo che ora funziona alla perfezione! Grazie!!!

**Comment by overclokk** [comment]
Ottimo :-)
