### ISSUE TITLE
Cookie script visibile in locale e non in remoto

### ISSUE THREAD

**Issue by magev88** [overclokk/italy-cookie-choices#114]
Salve a tutti,
sto quasi per impazzire.. sto tentando di inserire lo script dei cookies nel body di questo sito: http://isobuilding.it/index.html ma nonostante abbia più volte provato a cambiargli posizione, sempre dentro al body (pensando che fosse quello il problema) non ho risolto, lo carico online e non lo vedo!
Se mi scarico tutto il sito in locale e mi apro la index.html (per ora stavo lavorando su quella) vedo correttamente la barra superiore con il disclaimer.
Visualizzando il codice sorgente della pagina si vede ma da fron-end niente. Da che può dipendere? Non so più che pesci prendere.

Grazie infinite

**Comment by overclokk** [comment]
Ciao @magev88 
prima di tutto segui questi passaggi e dimmi se risolvi https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work

**Comment by magev88** [comment]
Ciao,
avevo già fatto quanto consigliato nel post che mi hai inoltrato, ma senza esito positivo.
Inoltre io NON ho Wordpress, ma è un semplice sito in HTML. La cosa strana è che in locale visualizzo correttamente la barra, mentre una volta caricato in remoto non si vede nulla, come se ci fosse qualcosa che impedisce la visualizzazione dello script.

**Comment by overclokk** [comment]
@magev88 con l'occasione ho creato una guida dedicata a pagine in puro HTML https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/Pages-in-pure-HTML
Vedi se ti può essere d'aiuto.

**Comment by magev88** [comment]
@overclokk Grazie mille! Ma come posso collegare un sito in locale ad uno in remoto? non capisco dove dovrei inserire il codice esteso del plugin... :/

**Comment by overclokk** [comment]
@magev88 esattamente della guida linkata quali punti non sono chiari che così li modifico.

**Comment by magev88** [comment]
@overclokk riguarda il secondo metodo, che nel mio caso sarebbe quello che mi serve, essendo un sito di solo HTML, ma non capisco cosa dovrei fare quando scrivi "configurare direttamente lo snippet in un WordPress anche locale". Grazie!!

**Comment by overclokk** [comment]
@magev88 Ok, ho modificato quella parte, vedi se ora è più chiaro

**Comment by magev88** [comment]
@overclokk perdona la testa dura (per non dire altro...! :P) ma dunque posso incollare il codice anche in una versione locale di Joomla? Come lo richiamo però nel mio sito html? Aiuto.

**Comment by overclokk** [comment]
Domanda: sai cos'è l'HTML e come si modifica una pagina HTML?

**Comment by magev88** [comment]
si certo. Inserendo il codice fornito da google però, come già detto, se apro la index.html dal mio computer in locale vedo bene il banner con il disclaimer, mentre una volta che la ricarico in remoto non lo vedo più. Quello che domandavo io, rispetto ai tuoi gentili e preziosi consigli, era riguardo l'attinenza tra un sito Joomla/wordpress in locale ed un sito Html in remoto..? Mi sono spiegato meglio?

**Comment by overclokk** [comment]
Non ha importanza quale CMS utilizzi, la pagina può essere anche in puro PHP, qualunque sia il sistema verrà sempre restituita una pagina HTML poiché il browser può "leggere" solo l'HTML, quindi se inserisci lo snippet che hai preventivamente copiato da una pagina in cui il banner funziona correttamente nel relativo file utilizzato per restituire la pagina che il browser visualizzerà verrà mostrato correttamente il banner, che sia in remoto o in locale non ha importanza, per esempio WordPress utilizza il file footer.php per inserire codice nel footer, joomla non so come gestisca la cosa ma semplicemente dovrai inserire lo snippet nel file del tema dove hai la chiusura del tag body.

**Comment by magev88** [comment]
Ok, quindi a livello puramente pratico cosa devo fare?
Nel mio caso la pagina HTML funziona (in locale) ma quando la carico via ftp e la guardo in remoto non più. Adesso ad esempio, ho provato ad inserire il semplice codice in una pagina HTML vuota, e quando la vado a caricare (http://www.isobuilding.it/cookiescript.html) non si vede nulla. Se me la apro in locale si.

**Comment by overclokk** [comment]
A livello puramente pratico vai qui ma non scrollare http://www.overclokk.net/ cerchi lo snippet, lo copi e lo metti nel tuo HTML.

Nella tua pagina vedo che il file js da un 404

**Comment by magev88** [comment]
Fatto, ma niente, c'è qualcosa che lo blocca. In locale lo vedo mai in remoto no.
(Ho fatto un test sempre qui: http://www.isobuilding.it/cookiescript.html)

Il file js si trova nella root principale del sito

**Comment by overclokk** [comment]
Io lo vedo funzionante, la barra è in basso e il testo è visibile.

PS: tutto quello che sta dopo </noscript> non serve, son js del mio sito ;-)

**Comment by magev88** [comment]
Solo questo allora:

<div><style scoped>#cookieChoiceInfo{background-color: #000;color: #000;left:0;margin:0;padding:4px;position:fixed;text-align:center;bottom:0;width:100%;z-index:9999;}.italybtn{margin-left:10px;}</style><script>var coNA="displayCookieConsent",coVA="y";scroll="1",elPos="fixed",infoClass="italybtn",closeClass="italybtn",htmlM="",rel="",tar="1",bgB="#fff",btcB="#000",bPos="bottom:0",bannerStyle="bannerStyle",contentStyle="contentStyle",consText="consentText",jsArr = [];function allowCookie(){var a,b=document.getElementsByClassName("el"),c=new RegExp("<script.*?");for(a=0;a<b.length;a++){b[a].removeChild(b[a].childNodes[0]);var d=c.test(jsArr[a]);if(d){var e=/<script.*?src="(.*?)"/,f=e.test(jsArr[a]);f&&(f=e.exec(jsArr[a]),loadJS(f[1]));var g=/<script\b[^>]_>([\s\S]_?)<\/script>/gm,h=g.exec(jsArr[a]);h[1]&&appendJS(h[1])}else{var i=b[a].innerHTML;d=i.replace(/<cookie>/g,jsArr[a]),b[a].innerHTML=d}}}function loadJS(a){var b=document.createElement("script");b.type="application/javascript",b.src=a,document.body.appendChild(b)}function appendJS(a){var b=document.createElement("script");b.type="text/javascript";var c=a;try{b.appendChild(document.createTextNode(c)),document.body.appendChild(b)}catch(d){b.text=c,document.body.appendChild(b)}}!function(a){if(a.cookieChoices)return a.cookieChoices;var b=a.document,c=(b.documentElement,"textContent"in b.body),d=function(){function a(a){var b=a.offsetHeight,c=getComputedStyle(a);return b+=parseInt(c.marginTop)+parseInt(c.marginBottom)}function d(a,c,d,e){var f=b.createElement("div");f.id=s,f.className=bannerStyle;var j=b.createElement("div");return j.className=contentStyle,j.appendChild(g(a)),d&&e&&j.appendChild(i(d,e)),j.appendChild(h(c)),f.appendChild(j),f}function e(a,c,d,e){var f=b.createElement("div");f.id=s;var j=b.createElement("div");j.className="glassStyle";var k=b.createElement("div");k.className=contentStyle;var l=b.createElement("div");l.className=bannerStyle;var m=h(c);return k.appendChild(g(a)),d&&e&&k.appendChild(i(d,e)),k.appendChild(m),l.appendChild(k),f.appendChild(j),f.appendChild(l),f}function f(a,b){c?a.textContent=b:a.innerText=b}function g(a){var c=b.createElement("span");return c.className=consText,f(c,a),c}function h(a){var c=b.createElement("a");return f(c,a),c.id=t,c.className=closeClass,c.href="#",c}function i(a,c){var d=b.createElement("a");return f(d,a),d.className=infoClass,d.href=c,tar&&(d.target="_blank"),d}function j(){return q()&&(htmlM&&(b.getElementsByTagName("html")[0].style.marginTop=u),allowCookie(),p(),n()),rel&&b.location.reload(),!1}function k(c,f,g,h,i){if(q()){var k=i?e(c,f,g,h):d(c,f,g,h),l=b.createDocumentFragment();l.appendChild(k),b.body.appendChild(l.cloneNode(!0)),htmlM&&(b.getElementsByTagName("html")[0].style.marginTop=a(b.getElementById("cookieChoiceInfo"))+"px"),b.getElementById(t).onclick=j,scroll&&(b.onscroll=j)}}function l(a,b,c,d){k(a,b,c,d,!1)}function m(a,b,c,d){k(a,b,c,d,!0)}function n(){var a=b.getElementById(s);null!==a&&a.parentNode.removeChild(a)}function o(){j()}function p(){var a=new Date;a.setFullYear(a.getFullYear()+1),b.cookie=r+"="+coVA+"; expires="+a.toGMTString()+";path=/"}function q(){return!b.cookie.match(new RegExp(r+"=([^;]+)"))}var r=coNA,s="cookieChoiceInfo",t="cookieChoiceDismiss",u=b.getElementsByTagName("html")[0].style.marginTop,v={};return v.showCookieConsentBar=l,v.showCookieConsentDialog=m,v.removeCookieConsent=o,v}();return a.cookieChoices=d,d}(this);document.addEventListener("DOMContentLoaded", function(event) {cookieChoices.showCookieConsentBar("Questo sito usa i cookie per migliorare la tua esperienza d'uso e usa cookie di terze parti.", "Chiudi", "Più info.", "http://www.overclokk.net/privacy");});</script></div><noscript><style scoped>html{margin-top:35px}</style><div id="cookieChoiceInfo"><span>"Questo sito usa i cookie per migliorare la tua esperienza d'uso e usa cookie di terze parti."</span><a href="http://www.overclokk.net/privacy" class="italybtn" target="_blank">Più info.</a></div></noscript><script type='text/javascript' src='http://s0.wp.com/wp-content/js/devicepx-jetpack.js?ver=201527'></script>

**Comment by overclokk** [comment]
Togli tutto quello in cui c'è scritto overclokk ;-)
Per il resto hai visto che funziona?

**Comment by magev88** [comment]
Funziona ma come scrollo sparisce... dovrebbe rimanere fisso invece, no?

**Comment by overclokk** [comment]
Perché tu hai messo il codice che ho configurato per il mio sito :-) per questo ti dicevo che se te lo configuri in una tua installazione di WordPress puoi applicare le tue personalizzazioni.

**Comment by magev88** [comment]
Però devo avere un sito di wordpress caricato in remoto solo per avere il plugin configurato? Non c'è una maniera meno "complessa" per richiamarlo senza creare problemi? Chiedo troppo dici..

**Comment by overclokk** [comment]
Dipende, se vuoi la versione base puoi usare cookiechoices di google, per quella più customizzata devi per forza prendere il codice da una installazione di WordPress.

**Comment by magev88** [comment]
A me la base andrebbe benissimo, non capisco però perchè lo vedo solo il locale e non in remoto.
Può essere un settaggio del server?? O forse va in conlitto con qualcosa...cosa potrei controllare?

**Comment by overclokk** [comment]
In quello base il file js dava un 404

**Comment by magev88** [comment]
ma perchè a me non lo dava....provo ad appoggiarlo su un sito esterno e richiamarlo allora, magari dipende solo da quello. Sto impazzendo per questa cavolata :|

**Comment by overclokk** [comment]
Il file deve essere caricato nello stesso percorso inserito nel tuo HTML se no da 404 e non funziona

**Comment by magev88** [comment]
Si infatti era proprio questo il problema (stra-idiota). Talmente stupido che lo davo per scontato e cercavo chissà quale cosa super complicata!

Grazie infinite per la pazienza e l'aiuto ;)

**Comment by overclokk** [comment]
Di nulla :-)
