### ISSUE TITLE
HTML nell'informativa breve

### ISSUE THREAD

**Issue by kkri** [overclokk/italy-cookie-choices#116]
Ciao. Devo mettere il testo dell'informativa in 3 lingue e questo purtroppo perchè il sito in questione usa Google Translator e quindi in realtà non gestisce le pagine multilingua ma con una pagina unica. Visto che dovrò mettere un bannerone come informativa "breve", non posso almeno separare i 3 testi con un <br /> o un &nbsp; o simili? Il box supporta solo testo puro e non HTML? Addirittura pensavo di mettere lo shortcode di Google Translate in modo che me la potevo cavare con 1 testo con vicine le bandierine per tradurlo su necessità (v. come le bandierine fanno in tutte le pagine del sito), ma immagino che tantomeno supporti gli shortcodes. Thanx

**Comment by overclokk** [comment]
Ciao @kkri era già in programma #32 ma causa tempo e priorità non è stato ancora fatto, spero di riuscire nelle prossime release

**Comment by kkri** [comment]
1) Ok. Già che il banner verrà comunque orribile, perchè enormemente alto, cercherò almeno di dargli una formattata ...
2) Non riesco a bloccare Google Translate: non va bene così la sintassi per il blocco?

<script type='text/javascript' src='http://www.vincenzoraponi.com/wp-content/plugins/google-language-translator/js/flags.js?ver=4.2.2'></script>

<---------SEP--------->
    <script>
      jQuery(document).ready(function($) {
        $("a.nturl").on("click",function() {
      default_lang = "it";
      lang_prefix = $(this).attr("class").split(" ")[2];

```
  if (lang_prefix == default_lang) {               
    load_default();
  } else {
    load_selected_language();
  }

  function load_default() {
    doGoogleLanguageTranslator(default_lang + "|" + default_lang);
  }

  function load_selected_language() {
    doGoogleLanguageTranslator(default_lang + "|" + lang_prefix);
  }
    });

    $("a.flag").on("click",function() {
      default_lang = "it";
  lang_prefix = $(this).attr("class").split(" ")[2];

  if (lang_prefix == default_lang) {               
    load_default();
  } else {
    load_selected_language();
      }

  function load_default() {
    doGoogleLanguageTranslator(default_lang + "|" + default_lang);
  }

  function load_selected_language() {
    doGoogleLanguageTranslator(default_lang + "|" + lang_prefix);
  }
    });

    if ($ ("body > #google_language_translator").length == 0) {
      $("#glt-footer").html("<div id='google_language_translator'></div>");
    }
  });
</script>
```

<---------SEP--------->

<script type='text/javascript'>function GoogleLanguageTranslatorInit() { new google.translate.TranslateElement({pageLanguage: 'it', layout: google.translate.TranslateElement.InlineLayout.HORIZONTAL, autoDisplay: false}, 'google_language_translator');}</script>

<---------SEP--------->

<script type='text/javascript' src='//translate.google.com/translate_a/element.js?cb=GoogleLanguageTranslatorInit'></script>

<---------SEP--------->

p.s. mi rendo conto adesso che non posso mettere lo shortcode delle bandierine di Google Translate nell'informativa breve perchè avrebbero bisogno del consenso ...

**Comment by kkri** [comment]
come si scrive del codice su github? ... v.allegato ... :)
![ss-noscripts](https://cloud.githubusercontent.com/assets/6691744/8504707/4f45346c-21d6-11e5-8e28-b6251c0bac6e.jpg)

**Comment by overclokk** [comment]
1) ma perché non usi un plugin per il multilingua? Riusciresti a risolvere quel problema, Italy Cookie Choices supporta WPML, Ceceppa e Polylang
2) Hai visto che puoi usare anche il tag `<---------SOMETHING--------->`?

Per inserire codice in github leggi qui https://guides.github.com/features/mastering-markdown/

**Comment by kkri** [comment]
1) il plugin per il multilingua significa dover tradurre le pagine, a "manina", per 2 lingue, e sono un centinaio ...
2) cosa fa il tag SOMETHING? non ho capito. Dovrei scrivere come l'esempio che ti ho mandato, ma sostituendolo a SEP? Che differenza c'è? Non so cosa sia il regex ...
3) intendevo perchè me lo prenda all'interno del messaggio, altrimenti lo allego in un file di txt, no problem.
4) è difficile e lungo permettere l'HTML nell'informativa breve? :) :) :)

**Comment by overclokk** [comment]
1) era solo un consiglio ;-)
2) nella wiki c'è scritto, dimmi se è comprensibile
3) appunto, quella è la guida e c'è scritto come inserire snippet di codice
4) no, bisogna fare test sulla sicurezza, comunque ho aggiunto questa funzionalità nella versione in sviluppo, vedo di caricarla in questi giorni

Poi ho aggiunto una semplificazione per lo slug e la url.

**Comment by kkri** [comment]
1) sì, grazie, ma impegnativo da realizzare ...
2) io credo che a parte gli scripts, che sono preceduti e seguiti da script e fine script, gli utenti/dummies come me ... non sanno cosa sia quello che devono bloccare, nel senso se snippet o altro. Quello che devo bloccare io sono diversi scripts che si riferiscono tutti a Google translate, li ho messi nel box di quelli da bloccare separati da SEP + "frecce" prima e dopo e tutt'ora mi sembra abbia fatto bene, ma, evidentemente non è così. Per vedere la sintassi v.l'immagine nel messaggio sopra;
3) dopo guardo;
4) ok, thanx :)
5) slug: quello che hai messo va bene, verificato step by step, ma lo farei precedere da questo:
Lo slug è l'indirizzo "nudo" della pagina, escludendo tutta la parte iniziale dell'indirizzo del sito, prendendo solo la parte finale senza slashes "/" prima e dopo. 
Esempio:
Pagina informativa: http://www.miosito.it/informativa-privacy-e-cookies/
Slug: informativa-privacy-e-cookies 
Per inserirlo nell'apposito campo del plugin puoi copiarlo e incollarlo prendendo solo quella parte, oppure seguendo il procedimento sotto: ....

**Comment by overclokk** [comment]
2) quindi secondo te servirebbero degli snippet già pronti per l'utilizzo? (almeno per quelli più conosciuti si può fare, tipo FB, G+)

5) quello che intendo è che nella prossima versione sarà più semplice inserire uno slug e una url

**Comment by kkri** [comment]
2) would be great !!!!!! :) Veramente intendevo che in giro c'è molta più ignoranza di quella che tu metti in conto (io per prima, che faccio i siti da anni, ma non conosco questioni troppo tecniche), ma se ne indicassi un po' di quelli classici (ma anche a parte nella guida tutti quelli che puoi), sarebbe di grandissimo aiuto).
5) ok.

**Comment by overclokk** [comment]
2) Ok, preparare qualche snippet si può fare ma come renderli "facili" da aggiungere?
Un pulsante? Un "customizer"?

**Comment by kkri** [comment]
Un pulsante con scritto il nome dello script sarebbe una favola, ma non so quanto lavoro ti comporti. Il customizer come funzionerebbe?
In una pagina dove ci sono tutti video ho messo il nocookie nel codice embeddato, ma siccome avevo letto che YT rilasciava cookies comunque, ho anche cambiato metodo scegliendo "Cookie da tutti gli embed nel tuo contenuto (Beta) (DEPRECATA) " invece del secondo, quello sui widgets. Poi ho dovuto mettere 2 scripts di revolution Slider da non bloccare perchè non mi faceva più vedere le slides nella home. I 3 metodi di blocco si possono usare tutti senza problemi? Perchè c'è scritto da un bel pezzo DEPRECATA? Quella che ho scelto io può andar bene? Guarda come funzia il giro: http://www.vincenzoraponi.com/media/

**Comment by kkri** [comment]
Sempre per i soliti dummies: puoi spiegarmi/ci meglio che azz è la regex e quando/come si usa SOMETHING invece di SEP? :(

**Comment by overclokk** [comment]
Gli script possono essere sia inline che esterni, ovvero:

```
<script>//questo è uno script inline</script>
```

```
<script src="url/dello/script/esterno.js"></script>
```

Gestire le varie situazioni non è semplicissimo quindi è da vedere bene come risolvere, forse i pulsanti non vanno bene, si rischierebbe di avere una lista infinita.

Quella funzionalità è deprecata perché con il nuovo blocco si riesce a gestire meglio le varie situazioni, non è ancora stata rimossa per permettere alle persone di poter migrare alla nuova funzionalità, prima o poi verrà rimossa.

Se hai notato non puoi usare tutte e tre insieme.

Una regex o espressione regolare serve per trovare all'interno di una stringa (testo) un determinato valore che può essere sia esatto sia un pattern di valori per trovare più di una occorrenza.

Nel nostro caso per semplificare le cose (che sono comunque ancora complesse) è stato introdotto SOMETHING (che non ha nulla a che vedere con SEP), questo pattern serve per trovare un determinato script che contiene una parola specifica, quindi invece di copiare l'intero script così come viene stampato nel sorgente si può usare SOMETHING in questi due modi:

```
<script src="/assets/js/<---------SOMETHING--------->.js" ></script>
```

oppure

```
<script<---------SOMETHING--------->esempio-facebook<---------SOMETHING--------->></script>
```

Questi sopra bloccheranno tutti gli script esterni
Questo sotto invece bloccherà uno script inline (es GA):

```
<script><---------SOMETHING--------->GoogleAnalyticsObject<---------SOMETHING---------></script>
```

**Comment by kkri** [comment]
1) per i pulsanti fai nel modo più corretto, anche se spesso non corrisponde a quello più comodo ... ;) 
2) per il metodo del blocco: quindi devo partire dal fatto che l'unico che rimarrà sarà "Cookie da tutti gli embed nella tua pagina, eccetto head e footer (Beta)"? Stavo sistemando il terzo sito e in ognuno avevo adottato un metodo diverso, a seconda di quanti/quali cookies ha, ho scelto il metodo di quello che me ne bloccava di più e poi sistemavo gli altri nel box da quelli da bloccare/sbloccare. Adesso bisogna che li riguardi tutti e 3 perchè credo in nessuno avevo adottato quello che rimarrà. Quello che rimarrà, subirà nessuna variazione?
3) se ho capito: SEP serve solo per separare uno script dall'altro tra quelli da bloccare, mentre SOMETHING è una sorta di query che poi inserisce tutte le occorrenze che trova e poi le passa al plugin da bloccare. Spero sia così, ma credo che non riuscirò mai a scrivere bene la sintassi. 
4) Esempio: in un sito con Google Analytics + pagina con 12 video YT, ho scelto il primo metodo che mi blocca tutti i video in una volta e ho "sbloccato" una slide fatta con Revolution Slider. Adesso con il blocco definitivo come faccio ad avere lo stesso risultato? 
4) Facebook page plugin: il nuovo box di FB per un attimo lo blocca e poi appare, senza consenso. Fino a ieri lo bloccava. E' cambiato qualcosa?

**Comment by overclokk** [comment]
1) ho fatto delle prove e forse inizialmente è meglio un popup con degli esempi (che sono poi quelli presenti nella wiki e che implementerò anche con altri)
2) si, in futuro rimarrà solo quello, comunque il funzionamento è identico ai primi due ma in più ha la possibilità di poter bloccare anche codice di terze parti inserite nel footer e nell'header
3) diciamo di si, gli snippet pronti servono anche a quello
4) la terza opzione è uguale alle prime due solo aggiunge il blocco anche per gli script aggiunti nella funzione wp_header() e wp_footer()
5) non è cambiato nulla

**Comment by kkri** [comment]
Ho appena iniziato a sistemare i siti con il blocco definitivo e non mi fa vedere il sito per niente, tutto bloccato http://www.kemicreazioni.it/

**Comment by overclokk** [comment]
E' bloccato perché usi nextgen gallery, purtroppo con questo plugin c'è una incompatibilità nota, l'unica soluzione al momento è quella di migrare ad altro plugin (cosa che consiglio vivamente essendo NGG una vera schifezza per come è sviluppato) vedi anche qui #81

**Comment by kkri** [comment]
Notizia ferale, lo uso in tutti i miei siti e in particolare in quello! La peggior notizia della giornata.

**Comment by kkri** [comment]
Ho fatto questo:
1) nel sito http://www.kemicreazioni.it/ ho riselezionato il metodo "Cookie da tutti gli embed nei tuoi widget (Beta) (DEPRECATA)" e mi blocca il FB page plugin e fa esattamente quello che deve fare, non si potrebbe fare in modo che continui a farlo? :)
2) ho guardato il plugin Foo-gallery che è quello che dovrebbe fare anche l'importazione delle gallerie create con Nextgen, ma ho visto che degli utenti dicevano che non funziona se si  usa Visual Composer e le mie gallerie sono dentro a box di VC... Sempre nel supporto del plugin, la maggior parte delle richieste inevase sono lì da oltre 2 mesi e non è un buon segno.
Non so come fare, è un gatto che si morde la coda, dammi una dritta.

**Comment by overclokk** [comment]
1) finché c'è puoi usarlo (è ancora li proprio perché stiamo testando le varie situazioni e come vedi c'è ancora molto lavoro da fare per sostituirlo completamente)
2) migrare alla galleria standard di WordPress?

**Comment by kkri** [comment]
1) sì, ma dopo devo rifare tutto il lavoro un'altra volta moltiplicato per un tot di siti. Vorrei anche metterci una pietra sopra e passare ad altro, ormai sono più di 2 mesi che gli vado dietro a sti maledetti cookies. Il prezzo che avevo fatto ottimisticamente ai clienti è ormai esaurito da un pezzo :(
2) la galleria di Wordpress è orribile e non valorizza certo le foto: la maggior parte dei siti che gestisco vivono di belle foto, i clienti mi ucciderebbero.

**Comment by kkri** [comment]
Sarà sicuramente una stupidaggine, ma non si potrebbe fare un sitema di blocco "modulare"? Nel senso che si possa impostare con vari check box, uno blocca i widgets, uno blocca gli scripts in header e footer ecc. E' chiaro però che dovrebbero essere anche combinabili e poterne scegliere più d'uno ... Ti prego dimmi di sì ...

**Comment by overclokk** [comment]
1) Purtroppo ne sono consapevole, trovare una soluzione che possa andare bene a tutti non è facile come hai potuto vedere, possiamo sempre valutare di mantenere per sempre quelle due funzionalità che però sono standalone e non sono collegate ai custom script, quindi non puoi permettere gli script.

2) come in molte cose WordPress fornisce la funzionalità poi sta a noi migliorarla esteticamente, io per esempio me la personalizzo in base alle esigenze, per esempio qui ci sono alcuni esperimenti di un carousel con bootstrap e la galleria standard http://demo.italystrap.it/bootstrap-carousel.html

3) C'è una parte del contenuto che rimarrebbe scoperta, ovvero tutta quella che è inserita direttamente nell'HTML e non sfrutta nessun gancio di WordPress

**Comment by kkri** [comment]
1)  non è importante che la soluzione sia unica per tutti in maniera diretta, ma che comunque in qualche modo, con più o meno variazioni partendo da una base comune di blocco, ognuno possa usare il plugin per adattarlo alla sua situazione. Credo che ci sia in giro moltissima gente più tecnica e brava di me, ma anche altrettanta meno esperta (in realtà credo molta di più del 50% totale)  che si è vista investire come da un treno da questa legge sui cookies. Mentre i primi hanno più armi per combattere il problema, i secondi, me compresa, sono disarmati e finalmente, dopo parecchio tempo passato a cercare di informarmi sugli obblighi della legge, che sono stati (e lo sono ancora) un incubo, per incertezze, assurdità ecc., mi ero un attimo ripresa perchè con il vostro plugin avevo almeno l'arma giusta per combattere il problema, anche se con gli accorgimenti del caso. 
Se però adesso mi dici che alcune cose non posso proprio farle in nessun modo, ripiombo nella disperazione come e molto di più di prima, perchè adesso non so dove mettere le mani e in più sono anche in ritardo con i siti. 
Visual Composer e Nextgen gallery sono entrambi stradiffusi, per cui una patch di qualche tipo per bloccare/sbloccare elementi inseriti dentro VC o gallerie costruite con Nextgen, farebbe felice una grossissima fetta dei vostri 10.000 utenti. 
Considera che noi che non sappiamo programmare (e neanche fare molto meno), ma lavoriamo sull'architettura dei contenuti, sulla scelta e l'implementazione dei plugins giusti che realizzano quanto i clienti si aspettano faccia il loro sito, sul dirigere il cliente a scegliere quello che vuole, ma soprattutto quello che è meglio per il buon andamento del sito, possiamo affidarci solo alle potenzialità del plugin, e, se non copre i vari casi, siamo completamente disarmati e nel panico. 
Se lascerai i 2 metodi deprecati e poi però non posso sbloccare uno script, tipo una slide con Revolution slider, mi fermo lì perchè non so minimamente come risolvere la seconda parte del problema. 
Personalmente sono disposta a fare tutte le varianti e le prove che posso, ma anche se nel caso specifico, riuscissi a passare in maniera indolore da NG gallery a Foo-gallery, poi magari il plugin non me le sblocca perchè sono all'interno di box di testo creati con VC, quindi sarebbe inutile. Visual Composer è ormai diventato indispensabile per la sua versatilità di costruire facilmente pagine dalle strutture più diverse e con elementi che coprono il 90% delle esigenze di qualsiasi tipo di sito e che sostituiscono buona parte dei plugins che una volta era necessario implementare, non è fattibile che da adesso in poi non si utilizzi più, quando sempre più temi lo includono. 
Dammi qualche consiglio mirato su come procedere, sempre considerando che le mie conoscenza tecniche sono molto limitate, ma sono pronta a sperimentare, pur di finire di sistemare i siti per questa maledetta cookie law. Aspetto buone notizie ;) e naturalmente non finiremo mai abbastanza di ringraziarti per il tuo lavoro, se posso dare una mano, dalla parte degli utenti, molto volentieri.

**Comment by andreapernici** [comment]
La realtà è che il plugin è per Wordpress e non per tutta la miriade di plugin (a volte anche a pagamento) che esistono in giro.

In molti casi converrebbe chiedere a quei plugin di modificare il loro codice.

Tenteremo di fare il possibile, ma non è possibile coprire l'intero mondo di casistiche anche perché se un plugin anche se versatile è fatto male ci si può fare molto poco.

In ogni caso per supportare alcune tesi servirebbero numeri reali.

Quanti usano Visual Composer? Io non lo ho mai usato ad esempio e mi guardo bene dall'usarlo.
Ho usato nextgen e devo dire che è davvero fatto male.

In ogni caso vediamo se si potrà fare qualcosa, ma ti consiglio di rompere le scatole anche al produttore di nextgen e di visual composer.

**Comment by kkri** [comment]
1) Il plugin è per Wordpress ma tanto non è che uno riesca a fare tutto un sito usando solo le funzioni del core e il tema di default, a meno che non sia un sito supermamatoriale o estremamente tecnico che non necessita di praticamente niente;
2) il problema è che io non ho la minima idea su cosa chiedere di modificare;
3) per VC per esempio credo che la casistica si riduca al solo fatto che il vostro plugin non riesca a leggere il contenuto dei vari elementi creati con VC, anche se non capisco perchè, non legge comunque l'HTML? 
4) per le varie tesi non volevano certo essere una statistica precisa, ma dal 2008 giro su Themeforest e ormai conosco anche le evoluzioni che hanno avuto i temi, il perchè del loro successo e la tendenza sempre più evidente a creare temi anche se non eccessivamente customizzati, ma sicuramente potenziati al massimo dall'inserimento di VC che fa tutto quello che il tema nudo e crudo non farebbe. Questa larga diffusione e tendenza speravo fosse garanzia di adeguamento anche di plugins, tools e quant'altro gira intorno a un sito Wordpress;
5) sono sicura che tu e molti altri "bravi" ;) come te non abbiano mai usato e anzi proprio evitino VC e simili come la peste, però io credo che bisogni anche partire dal fatto che chi fa un sito con WP non necessariamente debba anche conoscere programmazione o altro, ma che potrebbe essere una figura molto più "spartana", e nel mio piccolo ne conosco tante, senza considerare tanta gente che ha poco più di un sito amatoriale self-made, magari la casalinga disperata... Puoi capire che VC è un po' come la manna dal cielo, quando fino a poco tempo fa si potevano usare esclusivamente strutture di pagine previste dall'autore del tema e il tutto era praticamente ingessato.
Nextgen è fatto male da quando è passato dal suo autore storico all'attuale prorpietario Photocrati (pensa che non riesco a fare un backup completo del sito perchè il plugin crea un percorso talmente lungo che supera il numero di caratteri consentiti, prima mai successo ...). Nel bene e nel male attualmente ha oltre 12 milioni di downloads e va tenuto comunque in considerazione, almeno fino a quando non verrà soppiantato da plugins migliori. 
6) come dicevo, non so cosa chiedere agli autori in quanto non ho nè competenze nè potere contrattuale in quanto singola utente. Come autori di un plugin a cui VC e Nextgen impediscono di lavorare bene, voi avreste abbondantemente entrambe le qualità.
Riassumendo:
- se uso Nextgen il sito si oscura tutto se uso il blocco non deprecato? che plugin posso usare che non crei problemi? (non la galleria di WP)
- se uso VC non mi blocca gli eventuali contenuti all'interno degli elementi creati con VC? Scappatoia?
- considera che utilizzando il blocco dei widgets (deprecato) + i box per bloccare /sbloccare gli scripts riuscirei in qualche modo a gestire il tutto senza dover rivoluzionare tutti i siti che ho (v. http://www.kemicreazioni.it/ )
  Mi dispiace essere così noiosa, ma ero arrivata a un millimetro da finire il tutto e invece con il solo metodo di blocco che rimarrà non riesco a fare niente e devo guastare anche 3 siti che avevo sistemato.
  Grazie 1000

**Comment by overclokk** [comment]
1) in realtà con le migliaia di funzioni che ci sono nel core di WordPress si può coprire uno spettro molto ampio di customizzazioni, la maggior parte di quelle soluzioni di terze parti non rispettano neanche il codice standard di WordPress.
2) Intanto potresti chiedergli perché non sono in linea con lo standard WordPress.
3) anch'io non ho mai usato un visual composer ma non credo che il problema sia questo, penso solo che sia un problema di sintassi utilizzata, dovrei però vedere di persona.
4) il problema è che non esiste solo un metodo, ma ne sono nati diversi, ognuno ha sviluppato il proprio infatti prova a migrare da un tema ad un'altro senza avere problemi, praticamente impossibile e infatti questo è anche il motivo per cui WordPress ha introdotto il customizer.
5) il problema è che purtroppo non c'è un controllo sui plugin caricati sul repo di WP (NGG ne è la prova), chiunque può caricare qualsiasi cosa, immagina cosa puoi trovare su siti come themeforest, è come andare al ristorante, tu vedi il piatto quando te lo portano non quando lo cucinano.
6) quello che possiamo fare è valutare se mantenere per sempre quelle due funzionalità per gestire casi particolari come questo.
Il VC lo dovrei vedere per capire cosa fa, però ripeto, secondo me è solo un problema di sintassi.

**Comment by kkri** [comment]
1) Saranno anche molte le possibilità che dà di suo WP ma parti sempre dal fatto fondamentale che uno possa non essere molto esperto di codice, css ecc., inoltre con i prezzi sempre all'osso per i clienti che non vogliono/possono spendere, non posso metterci ore a formattare, modificare ecc. quando con VC ci metto 5 minuti e con risultati ottimi, dovrei almeno triplicare i prezzi e i miei clienti sono o privati o artigiani, hobbisti, piccoli locali ecc., li perderei tutti;
2) sì ma appena mi chiedono in che senso o altro, ho già finito gli argomenti ...
3) penso anch'io che non sia un problema globale di VC, volevo fare delle altre prove, intanto guardalo e se vuoi posso anche mandarti i parametri d'accesso in privato http://www.angiolettochecucina.it/
4) per me se il Customizer funziona, va benissimo, sperando però che offra opzioni simili al pannello di qualsiasi tema premium ... 
5) E'ora che Wordpress incorpori nel core molti più plugins che così funzionano sicuro e li monitori, è chiaro che così va a morire il mercato dei plugins e dei temi e non so ...
6) dici di mantenere i 2 metodi deprecati? per me magari, sempre se però abbinabili ai box degli scripts, altrimenti risolvo un problema ma poi non mi si vedono altri elementi (la slide per esempio).

![ss-icc-setup-090715](https://cloud.githubusercontent.com/assets/6691744/8596430/6f354c08-264f-11e5-96b4-93ef3d32c271.jpg)

**Comment by overclokk** [comment]
1) anche per questo è nato il customizer
2) il problema non è tuo ma è il loro
3) l'immagine che hai inviato è la configurazione di quel sito?
4) il customizer è lo standard WP
5) il problema è solo che ci vorrebbe un controllo maggiore, c'è già troppo codice nel core
6) faremmo tutte le considerazione del caso.

**Comment by kkri** [comment]
2) mi chiederanno sicuramente spiegazioni, la domanda è un po' troppo ermetica.
3) sì
6) quale blocco posso usare per sistemare i siti che mi rimangono?

**Comment by overclokk** [comment]
2) Con NGG digli semplicemente che ("siccome il vostro plugin fa schifo" -no, non dirgli così- ) ha avuto il blocco totale attivando entrambi i plugin, e vediamo se rispondono.
3)  + 6) Se i tre disponibili non sono sufficienti bisogna sviluppare qualcosa ad hoc mi sa, ci penso e vedo se trovo una soluzione.

**Comment by kkri** [comment]
2) adesso gli scrivo. intanto ho trovato questo commento che rassomiglia al mio caso https://wordpress.org/support/topic/conflict-with-x-theme-cornerstone prova a vedere se a te dice qualcosa ;) Altrimenti gli scrivo che fanno cag ... no, non glielo scrivo ;)
3 + 6) Se mi dici che posso usarli tutti e 3 ma insieme agli scripts da bloccare/sbloccare, qualcosa riesco a fare.
Hai visto nel sito http://www.angiolettochecucina.it/ che mi blocca il titolo (txt) del FB plugin page, ma non mi blocca il box FB v ero e proprio? Il nuovo box non è un js?

**Comment by overclokk** [comment]
2) no, quella discussione non centra nulla, il problema è simile a questi: https://wordpress.org/support/topic/who-decided-to-call-ob_start-on-every-single-page?replies=1
http://wordpress.stackexchange.com/questions/41012/proper-use-of-output-buffer?answertab=active#tab-top
http://stackoverflow.com/questions/772510/wordpress-filter-to-modify-final-html-output/22818089#22818089
3) + 6) ovviamente no, o solo i primi due o il terzo, tutti e tre insieme no
Provato anche il primo?
Probabilmente non viene bloccato perché non è contenuto ne nel content ne nei widget.

**Comment by kkri** [comment]
2) speravo di aver trovato qualcosa di utile...
3 + 6) i primi 2 vanno bene se rimangono entrambi ma spero che ognuno di loro possa essere associato anche ai box dove vanno gli scripts da bloccare/sbloccare;
Provato anche il primo ma nada.
Adesso ho modificato sostanzialmente la struttura della home e il box di Facebook che non bloccava prima, non lo blocca neanche adesso che è in una sidebar come widget (ICC blocco 2). Non dipende quindi che era inserito dentro un elemento di Visual Composer (e da una parte mi solleva), ma probabilmente dipende dal nuovo codice di Facebook, può essere? Se mi dici quale parte di codice prendere da inserire nei box degli scripts da bloccare ci provo, se bastasse quello, no problem. In parte ci "prova" a bloccarlo, nel senso che mette la scritta degli elementi bloccati nel box grigino.
http://www.angiolettochecucina.it/

**Comment by overclokk** [comment]
3+6 qui bisogna agire in modo diverso, penso ad una soluzione

**Comment by kkri** [comment]
Quando pensi alacremente, vengono sempre fuori delle belle sorprese ... :)

**Comment by overclokk** [comment]
Aggiunto funzionalità di poter inserire HTML nei due box per il testo con la versione 2.3.0
