### ISSUE TITLE
Multilingua: localizzazione testo embed bloccati e relativo pulsante

### ISSUE THREAD

**Issue by mavoga** [overclokk/italy-cookie-choices#118]
Enhancement - dovrebbe essere possibile la localizzazione delle stringhe "Testo per gli embed bloccati" e "Testo per il bottone di accettazione degli embed bloccati", apparentemente non gestibili da Polylang.

**Comment by overclokk** [comment]
@mavoga è già nella lista di cose da fare, per il momento avevamo lasciato così perché era in programma una funzionalità di personalizzazione del testo in base al tipo di codice bloccato, ma è ancora prima dell'apha

**Comment by overclokk** [comment]
Aggiunto con la versione 2.3.0

**Comment by mavoga** [comment]
Purtroppo [qui](http://www.gradina.biz/privacy-cookie-policy-it/) sembra che non funzioni... i
testi effettivamente appaiono nella pagina di traduzione delle stringhe
di Polylang, ma nelle pagine appare sempre solo quello inserito nella
pagina di impostazioni di ICC.

**Comment by overclokk** [comment]
Farò ulteriori test

**Comment by overclokk** [comment]
Era un problema di priorità, ora con la 2.3.1 fa il match corretto anche con la url di Polylang
