### ISSUE TITLE
Settings: Click su label associata alla checkbox non modifica stato

### ISSUE THREAD

**Issue by widoz** [overclokk/italy-cookie-choices#119]
Ciao,

È una bazzecola di problema, semplicemente se clicco sulla label associata ai checkboxes lo stesso non cambia il suo stato. Il problema l'ho notato su **chrome Version 43.0.2357.132 (64-bit)** su **OSX**. Credo che sia perché non vi è l'attributo id associato alle checkboxes ma solo l'attributo name.

**Comment by overclokk** [comment]
Ciao @widoz grazie della segnalazione, fix disponibile dalla prossima release.
