### ISSUE TITLE
Facebook Page Plugin

### ISSUE THREAD

**Issue by kkri** [overclokk/italy-cookie-choices#121]
Ciao.
Grazie per la versione 2.3.0 del plugin. L'ho installata, ho settato il blocco 2, quello degli embed nei widget, ho messo il codice di Facebook in un widget di testo nella sidebar, ma non mi blocca la Facebook Page Plugin. Poichè il codice che genera FB da inserire su WP è composto da una prima parte (script) più una seconda parte (per l'aspetto del box), non è che il codice che va messo nel box degli scripts da bloccare è solo una parte di quello generato da FB oppure va tutto racchiuso tra <embed> o <iframe>? Ho fatto delle prove mettendoli nella prima parte del codice o in tutto ma si vede lo stesso anche se visualizza comunque il box grigio che avvisa del "blocco", ma io posso facilmente sbagliare la sintassi. Ho provato con il blocco 3, lo blocca, ma poi anche con il consenso non lo sblocca più. Any idea?
codice fb page plugin: 
https://www.dropbox.com/s/48mrn0u9248yjnd/icc-fb-page-plugin-code.txt?dl=0

sito: 
http://www.angiolettochecucina.it/

**Comment by overclokk** [comment]
Ciao @kkri hai visto cosa è cambiato?
Il plugin blocca solo gli script, embed e iframe, i div non vengono toccati.
Il blocco dei widget in teoria dovrebbe funzionare, però se puoi usare il blocco totale (3) è meglio, e nel caso puoi usare questa sintassi:

```
<script><---------SOMETHING--------->facebook<---------SOMETHING---------></script>
```

Ma in quel sito non ti dava problemi il blocco totale a causa di NGG?

**Comment by kkri** [comment]
Ciao Enea. Non avevo visto la differenza ma comunque ho provato il blocco 3 e senza mettere il something non me lo blocca, ma scusa non ho ancora capito bene come si usa: nel caso specifico dovrei solo sostituire a "facebook" tutto il codice di FB sia lo script che quello per il layout? e poi metterlo nel box degli scripts da bloccare?
Sì prima mi dava problemi per NGG ma adesso forse con la versione nuova del plugin, sia forse anche perchè ho cambiato struttura alla pagina (main + sidebar dx) non mi blocca più tutto il sito.
