### ISSUE TITLE
Aggiornamento plugin wordpress e pagina blank

### ISSUE THREAD

**Issue by David83x** [overclokk/italy-cookie-choices#122]
Ho effettuato l'ultimo aggiornamento del plugin Italy Cookie Choise su Wordpress e non appena attivo il plugin mi appare la pagina bianca e non posso più accedere al pannello amministrativo.

Grazie
Saluti
David

**Comment by overclokk** [comment]
Ciao @David83x ho fatto diversi aggiornamenti sui siti che gestisco e non ho riscontrato nessun errore, vorrei capire meglio cosa sia successo per poter replicare questo eventuale problema, qual'è la procedura esatta che hai fatto?
Cosa hai fatto prima, durante e dopo?

**Comment by okmugello** [comment]
Ciao Enea, anch'io ho riscontrato il solito prolbema. Sto effettuando delle prove. Ho eliminato dei vecchi plugin ormai obsoleti, ma al momento che lo attivo mi fornisce sempre pagina bianca.

**Comment by giojan** [comment]
Ciao stesso problema. riattivata versione 2.2.2 per risolvere il problema.

**Comment by overclokk** [comment]
Fate queste prove e postatemi il risultato https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work

In particolare eventuali errori php e configurazione di partenza.

**Comment by GPwebdesign** [comment]
Ciao Enea
Credo che il problema sia nella versione di WP.
Io ho risolto passando da WP3.7.2 a WP4.2.2
Saluti e complimenti per l'ottimo (e provvidenziale) plugin

**Comment by overclokk** [comment]
Ciao @GPwebdesign ottimo, buono a sapersi, ora aspettiamo anche la risposta degli altri, almeno per capire la funzione che genera errore.

**Comment by gruppo3millennio** [comment]
Ciao Enea, sfortunatamente noi abbiamo WP 4.2.2 su due siti ed entrambi si impallano (pagina bianca dell'amministrazione) dopo l'aggiornamento del Plugin.
Dove possiamo trovare la versione precedente che funzionava benissimo?
Ciao e buon lavoro

**Comment by overclokk** [comment]
Ciao @gruppo3millennio io ho bisogno di sapere quale errore avete se no non posso risolverlo.

Qui ci sono le versioni precedenti https://github.com/ItalyCookieChoices/italy-cookie-choices/releases

**Comment by jdlele** [comment]
Buonasera, con wp 4.2.2 riscontro anche io il problema di blank page. Non vengono mostrati errori. Devo rinominare la cartella del plug-in per rientrare nell'amministrazione.
Aggiungo che anche tornando alla versione 2.3.0 ho lo stesso problema, ne deduco che altri aggiornamenti di worpress hanno scatenato questo comportamento

**Comment by overclokk** [comment]
Per mostrare gli errori bisogna attivare il debug di WordPress altrimenti viene mostrata una pagina bianca, qui ho indicato come https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work
Se per cortesia mi indicate gli errori restituiti durante l'aggiornamento (disattivando prima tutti gli altri plugin e mettendo il tema originale per evitare falsi positivi) mi fate un favore e sono in grado di risolvere, altrimenti non posso fare nulla.

Io ho aggiornato una 20ina di siti e non ho avuto nessun problema.

**Comment by borkie** [comment]
Stesso problema, il messaggio di errore che viene fuori abilitando la modalità di debug è:

```
Notice: Undefined offset: 1 in /wp-content/plugins/italy-cookie-choices/classes/class-italy-cookie-choices-front-end.php on line 324

Notice: Undefined offset: 2 in /wp-content/plugins/italy-cookie-choices/classes/class-italy-cookie-choices-front-end.php on line 325
```

**Comment by overclokk** [comment]
Ciao @borkie vorrei sapere anche la tua versione di PHP

Mi sembra strano quell'errore visto che quella funzione è presente dalla 2.0

**Comment by borkie** [comment]
5.4.41-0+deb7u1 su macchina debian

**Comment by overclokk** [comment]
E la configurazione del plugin?

**Comment by borkie** [comment]
l'errore compare quando abilito l'opzione: 
    Cookie da tutti gli embed nella tua pagina, eccetto head e footer (Beta)

**Comment by overclokk** [comment]
Ma è una nuova installazione o un aggiornamento?

**Comment by borkie** [comment]
nuova installazione

**Comment by andreapernici** [comment]
Comunque la notice non dovrebbe inficiare il funzionamento.

Forse è la configurazione di php?

**Comment by borkie** [comment]
altre info: nelle pagine wordpress del tema che sto creando includo una lunga lista di simboli in svg (circa 3300 righe), se disabilito questa include tutto funziona crrettamente.
Potrebbe essere qualche problema di memoria?

**Comment by andreapernici** [comment]
Secondo me è la configurazione di PHP. Prova ad aumentare la memoria anche se 3300 righe di SVG mi sembra eccessivo.

**Comment by borkie** [comment]
sono tre set di icone convertite in svg che mi servono per lo sviluppo, nella versione definitiva saranno molto meno.
Ora provo

**Comment by borkie** [comment]
Il problema sembra essere proprio quello, ho aumentato il limite fino a 2GB ma da ancora errore.
Se invece riduco il numero di icone non si presenta più il problema.
E' possibile magari specificare di escludere certe parti di codice?

**Comment by overclokk** [comment]
@borkie allora questo non è il problema della issue aperta.

Il plugin blocca script, iframe e embed, non ho capito cosa vorresti bloccare.

**Comment by borkie** [comment]
forse ho sbagliato issue, ma avevo anche io pagina bianca quando attivavo il plugin con la configurazione sopra.
Quando nella classe `class-italy-cookie-choiches-front-end.php` alla riga 323 va a fare `preg_match("/(.*)(<body.*)/s", $buffer, $matches);` vorrei escludere una parte di codice (in particolare quella con le definizioni degli svg che crea problemi di memoria).
Era solo una curiosità, per il momento tengo il plugin disabilitato finchè non elimino le icone superflue.

**Comment by overclokk** [comment]
La pagina bianca (se il debug è disattivato) viene con un fatal error, ora ti da ancora pagina bianca con il debug disattivato?

Il notice forse è dovuto al fatto di bloccare codice non consentito, gli svg non vengono bloccati dal plugin.

**Comment by overclokk** [comment]
Se il problema vi si presentava in un **multisite** ho appena caricato un bugfix con la 2.3.2

**Comment by allegra2014** [comment]
Se può essere utile, stesso problema anche io: aggiornato il plugin a 2.3.2 e pagina bianca. 
Dopo la disattivazione di tutti i plugin, provando a riattivare ICC dava il messaggio di errore fatale.

Reinstallata la versione 2.2.2 e ora tutto OK. Avevo provato anche la 2.3.0 ma dava lo stesso errore.
Ho WP 4.2.2 e PHP 5.5.21, sito singolo.

**Comment by overclokk** [comment]
Ciao @allegra2014 se mi scrivi la stringa con tutto l'errore sarebbe l'ideale, per farlo devi avere i debug attivo.

**Comment by allegra2014** [comment]
Fatal error: Cannot redeclare get_language() (previously declared in /nfsmnt/hosting2_1/5/3/536fcb24-5a3c-4fbb-b2ef-35ffe62dd584/xxx.sk/web/wp-content/plugins/italy-cookie-choices/includes/functions-italy-cookie-choices-lang.php:18) in /nfsmnt/hosting2_1/5/3/536fcb24-5a3c-4fbb-b2ef-35ffe62dd584/xxx.sk/web/wp-content/plugins/italy-cookie-choices/includes/functions-italy-cookie-choices-lang.php on line 30

**Comment by overclokk** [comment]
Ecco, già con questo riesco a capirci meglio, ti chiedo un'altra cortesia, mi puoi dire anche che plugin sono attualmente attivi?
Grazie

**Comment by allegra2014** [comment]
Ecco:

Akismet
Backup Scheduler
Feed Wrangler
Google Analytics by Yoast
Google XML Sitemaps
Img Title Removal
Jetpack by WordPress.com
KB Advanced RSS Widget
Smart Youtube PRO
WordPress Popular Posts
WP-PageNavi
WP Bannerize
WP Links
WP Translate

**Comment by allegra2014** [comment]
Inizialmente avevo avuto l'impressione che l'errore fosse nato con l'aggiunta del modulo "Widget della barra laterale extra" di Jetpack, che avevo usato per il widget Facebook Like Box, che era stato attivato in contemporanea con l'aggiornamento di ICC. Ma poi quella funzionalità di Jetpack l'avevo rimossa, e tutt'ora non è attiva. Quando ho riattivato i plugin avevo lasciato Jetpack per ultimo proprio perché credevo fosse quello il problema, ma col senno di poi sembra che c'entri niente.

**Comment by overclokk** [comment]
Hai provato per caso ad aggiornare il plugin disattivando tutti gli altri?

Comunque è strano quell'errore perché le funzioni per il multilingua ci sono dalla 2.2.0

**Comment by allegra2014** [comment]
ho riprovato adesso, tutti i plugin disattivati, e va ancora in errore fatale. Anche dopo aver ripulito la cache del browser

**Comment by overclokk** [comment]
L'errore è lo stesso di prima?

**Comment by allegra2014** [comment]
Acc... non avevo attivato il debug :-(  Devo?

**Comment by allegra2014** [comment]
Ho riprovato con il debug attivo.... 
Esce di nuovo il messaggio "Il plugin non può essere attivato perché genera un errore fatale."
Ma non c'è più quel messaggio del debug... Hai fatto qualcosa?

**Comment by overclokk** [comment]
No, non ho fatto nulla, finché non so cosa fixare ho le mani legate.

Per caso hai provato anche a fare un'installazione da zero del plugin?
Prima però devi cancellarlo per cancellare anche il riferimento nel db

**Comment by overclokk** [comment]
@David83x 
@okmugello 
@giojan 
@allegra2014 
@jdlele 
Con la aversione 2.3.4 ho risolto un bug nell'admin mi dite se aggiornando riscontrate ancora lo stesso problema?

**Comment by okmugello** [comment]
Purtroppo si! Aggiornato il plugin, attivato e "pagina Bianca". Ho provato ad attivare il debug dal file wp-config ma niente rimaneva pagina bianca senza nessuna informazione di merito. Disattivato plugin e tutto torna normale...

**Comment by overclokk** [comment]
@okmugello mi dici la versione del plugin, di WP e di php?
Il debug lo hai attivato prima di aggiornare?
La versione 2.3.4 è di quesa mattina

**Comment by okmugello** [comment]
La versione di WP 4.2.2 PHP 5.5 - Il debug lo attivato dopo l'aggiornamento del plugin. Il plugin lo aggiornato all'ultima versione.

**Comment by overclokk** [comment]
Sarebbe utile che il debug fosse attivato prima di aggiornare e per eliminare falsi positivi gli altri plugin sarebbe meglio fossero disattivati.

**Comment by okmugello** [comment]
OK effettuerò prova e verifica domani nella serata, poiché il sito in cui era installato il plugin è attivo e non posso farlo in contemportanea con le attività in corso.

**Comment by overclokk** [comment]
Ok, aspetto tue notizie

**Comment by overclokk** [comment]
Con la versione 2.3.5 è stato risolto un problema di performance per siti con migliaia di articoli
@David83x 
@okmugello 
@giojan 
@allegra2014 
@jdlele 
Se riuscite a fare una verifica posso chiudere la issue.

**Comment by overclokk** [comment]
Intanto chiudo, se ci fosse ancora il problema con la versione 2.3.5 riapro.
