### ISSUE TITLE
Il plugin non può essere attivato perché genera un errore fatale.

### ISSUE THREAD

**Issue by romanomauro** [overclokk/italy-cookie-choices#123]
Ricevo questo errore all'attivazione del plugin, non vedo errori nei log del server.
Ha smesso di funzionare dall'ultimo aggiornamento.
Grazie.

**Comment by overclokk** [comment]
Ciao @romanomauro continuiamo da la #122  se mi indichi anche gli errori che ricevi sarebbe ottimo, prima però per evitare di avere falsi positivi disattiva tutti i plugin e tema.
