### ISSUE TITLE
Cookie Wordpress plugin multilingua

### ISSUE THREAD

**Issue by magev88** [overclokk/italy-cookie-choices#124]
Ciao,
sto installando ora il plugin Italy Cookies Choices su un sito in WP che ha sia ITA che ENG come lingue, solo che non riesco a capire (non lavoro solitamente con Wordpress) come poter inserire la traduzione per l'una e per l'altra lingua. Questa in allegato è la schermata che mi compare (e mi minaccia) dicendo che rischio la perdita di dati ecc ecc.. ma è lei che gestisce il multilingua? Che posso fare?

![schermata 2015-07-15 alle 11 47 10](https://cloud.githubusercontent.com/assets/13137939/8695794/c876a6b2-2ae7-11e5-8717-3fc308879725.png)

Grazie

**Comment by overclokk** [comment]
Ciao @magev88 qui trovi le informazioni e plugin testati per la funzionalità multilingua https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/Multilanguage

Comunque nel sicuro un bel backup del database sei sempre in tempo a farlo.

**Comment by magev88** [comment]
Sul sito al quale sto lavorando hanno utilizzato Qtranslate, con questo non posso fare nulla allora?
Se non provare ad abilitarlo (previo backup) e vedere che succede.

**Comment by overclokk** [comment]
Si, fai una prova e dimmi

**Comment by magev88** [comment]
Ho optato per fare un backup di sito e DB ed installarlo in una sotto cartella del dominio per fare le prove li senza invalidare il sito "originale" (www.wheelybikerental.com/wheely) ma una volta cambiato il file di configurazione con le info aggiornate, vedo solo una pagina bianca.. che mi sono perso?!

**Comment by overclokk** [comment]
Dovresti attivare il debug per vedere eventuali errori.

**Comment by magev88** [comment]
Posso farlo in che modo? Perdonami ma con WP sono almeno 5 o 6 anni che non ci lavoro più e mi sono un pò perso..

**Comment by overclokk** [comment]
Vedi qui https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn%27t-work#ulteriore-test
Appena hai fatto dimmi l'errore

**Comment by magev88** [comment]
Ho fatto, ma non visualizzo nessun errore..sempre pagina bianca

**Comment by overclokk** [comment]
Hai i log del server?

**Comment by magev88** [comment]
Il sito è hostato su Joomlahost, non mi pare ci siano i log..

**Comment by overclokk** [comment]
Senza log non possiamo conoscere eventuali errori, chiedi al tuo hosting se te li può fornire

**Comment by magev88** [comment]
però come è possibile che mi copio il sito intero, mi copio il DB, ricarico il sito in una sotto cartella dello stesso dominio e carico anche il DB ma non riesco a vedere niente?

**Comment by overclokk** [comment]
Questo non lo posso sapere, possono essere tanti i fattori, l'unico modo è vedere i log del server per eventuali errori.

**Comment by overclokk** [comment]
Se il problema vi si presentava in un **multisite** ho appena caricato un bugfix con la 2.3.2

**Comment by webmarker73** [comment]
Ciao Overclokk, io ho un sito wordpress con multilingua (Ceceppa) e il plugin Italy cookies choice, ma quando attivo entrambi, il banner di "italy cookies..." appare senza traduzioni (es. tipo: "banner text" oppure per il pulsante di "maggiori informazioni": "Anchor text". Come disattivo Ceceppa torna a funzionare... Dov'è secondo te il problema?
Preciso inoltre che quando salvo le impostazioni di Italy cookies in admin wordpress, mi da un errore del tipo: 
[Parse error: syntax error, unexpected ',', expecting '&' or variable (T_VARIABLE) in /data/vhosts/...]
[.../wp-content/plugins/italy-cookie-choices/includes/functions-italy-cookie-choices-lang.php(51) : runtime-created function on line 1]

Cosa vuol dire? Non erano compatibili Ceceppa e Italy Cookies?
Aiutami se puoi...
Grazie.
Webmarker73

**Comment by overclokk** [comment]
Ciao @webmarker73 domani controllo

**Comment by overclokk** [comment]
Si, in effetti da anche a me quell'errore, strano, vedo cosa sia successo.

**Comment by webmarker73** [comment]
Ok grazie... fammi sapere...

**Comment by overclokk** [comment]
@webmarker73 ho appena caricato la versione 2.3.5 risolvendo il problema di parse error, dimmi se è tutto ok.
@magev88 provala anche tu e dimmi se ora funziona
Ps: nel sito quanti articoli hai?

**Comment by webmarker73** [comment]
Ciao Overclokk, allora il problema in admin è risolto: nessun parse error.
Ora però rimane il problema della cookie policy nella lingua inglese...
Intanto non vedo nelle impostazioni del plugin la possibilità di inserire il testo in lingua inglese, per cui come attivo il plugin ("Visualizza il banner sul tuo sito web, se non attivi non viene mostrato nulla.") in automatico appare il banner con i bottoni non tradotti. Qui sta un esempio...

![image](https://cloud.githubusercontent.com/assets/13421482/8904326/bb53d524-345e-11e5-8bb1-5f8a80270860.png)

In pratica appaiono le scritte/pulsanti in questo modo:
Banner text
BANNER ANCHOR TEXT
BANNER BUTTON TEXT

Fammi sapere come si può risolvere il problema. Intanto grazie per la tua disponibilità.
Marco.

**Comment by yaku78** [comment]
Ciao ragazzi, sono tornato.
Ho un problema anch'io con un sito multilingua (Wpml) non riesco ad installare il plugin, mi da un errore fatale: 

Parse error: syntax error, unexpected T_FUNCTION in /var/www/virtual/evomek.it/htdocs/wp-content/plugins/italy-cookie-choices/includes/functions-italy-cookie-choices-lang.php on line 52

**Comment by overclokk** [comment]
Ciao @yaku78 devi aggiornare il PHP del server, il plugin supporta minimo l 5.3

**Comment by overclokk** [comment]
Appena caricato il fix per Ceceppa.
Per quanto riguarda qTranslate non verrà fatto nulla visto che il plugin non è più presente sul repo (e da nessun'altra parte) ed è rimasto alla versione di WordPress 3.8.1 come indicato anche qui http://www.qianqin.de/qtranslate/download/
Consiglio di fare una migrazione ad un plugin che sia regolarmente aggiornato.

**Comment by dademaru** [comment]
Ciao @overclokk 

(anzitutto grazie per il plugin, sempre aggiornato per stare al passo con le pazze normative)

per una maggiore compatibilità con i diversi plugin multilingue o per traduzioni autonome con PoEdit o programmi simili, si potrebbero aggiungere hook alle variabili in cui richiami i testi delle impostazioni del plugin, ad esempio:

```
$text_option = $this->wp_json_encode( wp_kses_post( get_string( 'Italy Cookie Choices', 'Banner text', $this->options['text'] ) ) );
$text = apply_filters( 'icc_text_filter', $text_option );

$anchor_text_option = esc_js( get_string( 'Italy Cookie Choices', 'Banner anchor text', $this->options['anchor_text'] ) );
$anchor_text = apply_filters( 'icc_anchor_text_filter', $anchor_text_option );

$button_text_option = esc_js( get_string( 'Italy Cookie Choices', 'Banner button text', $this->options['button_text'] ) );
$button_text = apply_filters( 'icc_button_text_filter', $button_text_option );
```

In questo modo si possono sempre utilizzare i campi delle impostazioni di ICC, altrimenti ci si può agganciare con dei filtri e passare delle stringhe traducibili, con __().

P.S. [qTranslateX](https://it.wordpress.org/plugins/qtranslate-x/) è regolarmente aggiornato.

**Comment by overclokk** [comment]
Ciao @dademaru 
grazie per il consiglio, sicuramente in una prossima versione si possono implementare più hook, me lo segno e ci guardo appena possibile.
