### ISSUE TITLE
Il plugin non può essere attivato perché genera un errore fatale.

### ISSUE THREAD

**Issue by cattom** [overclokk/italy-cookie-choices#125]
Ciao,
Ho aggiornato oggi il plugin all'ultima versione e mi ha mostrato errore fatale che mi bloccava la parte back end di Wordpress. Ho rimosso la cartella pensando che fosse un errore di aggiornamento e reinstallato tutto da capo, ma non posso attivarlo perchè mi mostra l'errore in titolo.

L'errorlog invece mi mostrava la seguente stringa all'atto dell'aggiornamento:

[15-Jul-2015 17:12:52 UTC] PHP Notice:  Undefined index: HTTP_ACCEPT in /wp-content/plugins/italy-cookie-choices/classes/class-italy-cookie-choices-front-end.php on line 251

E' solo un errore mio o è un problema dell'ultima release?

Grazie,

Tommaso

**Comment by cattom** [comment]
Ho appena scaricato la 2.3.0 e installata manualmente, stessa issue. 
Installando la 2.2.2 invece nessun problema.

**Comment by overclokk** [comment]
E' strano, è dalla 2.0.0 che c'è quella variabile, sembra quasi un problema con il server, prova a commentare la riga 251 nella versione 2.3.1 e caricarla via ftp.

Forse è legato al problema #122

**Comment by overclokk** [comment]
Se il problema vi si presentava in un **multisite** ho appena caricato un bugfix con la 2.3.2

**Comment by ralicata** [comment]
Ho scaricato anche la Versione 2.3.3 ma su un sito multisite ho lo stesso problema.. Error 500 appena attivo il plugin.
Rimettendo la versione 2.2.2 è tornato tutto a funzionare

**Comment by overclokk** [comment]
Ho bisogno di conoscere l'errore php generato per poter capire perché succede questo, per vedere gli errori php bisogna attivare il debug di WordPress e qui spiego come fare https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work

Considerando che solo in pochi hanno questo problema è possibile che ci siano problemi nell'installazione stessa di WordPress come è già successo ad alcuni con problema simile.

**Comment by overclokk** [comment]
@cattom 
@beooo 
Con la aversione 2.3.4 ho risolto un bug nell'admin mi dite se aggiornando riscontrate ancora lo stesso problema?

**Comment by ralicata** [comment]
ho provato ad aggiornare alla 2.3.4 ma mi dà ancora il Fatal Error

"Allowed memory size of 134217728 bytes exhausted (tried to allocate 30720 bytes) in /var/www/clients/client2/web3/web/wp-admin/includes/ms.php on line 785"

ho provato ad aumentare la memoria a disposizione ma non cambia nulla

**Comment by overclokk** [comment]
E' molto probabile che sia una configurazione non corretta della macchina, io per esempio con 256MB non ho problemi, prova ad aumentare ancora.

La cosa strana è che il plugin usa pochissima memoria, ho fatto alcuni test e siamo poco sopra i 3MB

**Comment by overclokk** [comment]
Verificato sulla mia macchina locale e uso 128MB di ram per il PHP (equivalente a 134217728) e non ho nessun problema.

**Comment by AlexTorre13** [comment]
Confermo anche sui miei siti
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 72 bytes)
Plugin vers 2.3.4
tutti fermi...

Aggiungo, il warning per wp-includes/meta.php on line 829

**Comment by overclokk** [comment]
Mi dispiace che abbiate questo genere di errore ma e probabile che il problema sia il server stesso, io ovviamente da qui non posso sapere com'è configurato il sito, l'unica cosa che posso dire è qui c'è la guida da seguire se si hanno di questi problemi https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work

Se si riscontrano ancora errori (dopo aver seguito tutti i passagi) allora qui mi fate sapere tutto il possibile dell'installazione di WordPress come ho indicato nel link precedente, memory limit non mi dice nulla.

Una situazione simile è successa anche ad un altro utente, non riusciva a risolvere poi ha provato il plugin su un altro sito e si è accorto che il problema era il server ;-)

**Comment by AlexTorre13** [comment]
Overclokk, ti ringrazio delle spiegazioni, ma ovviamente i particolari delle installazioni non possono essere messe in un forum. Se avete un servizio di heldesk personale ben lieto. Altrimenti, siccome non va e non si può rimanere senza sono costretto a sostituirlo. Ma, oltre al lavoro per farlo, sarebbe davvero un guaio in quanto il plugin lavora benissimo, non inficia per nulla le statistiche, insomma è ottimo. Attendo, grazie.

**Comment by overclokk** [comment]
@AlexTorre13 non voglio assolutamente conoscere dati sensibili ma eventuali configurazioni tipo plugin usati, versione php ecc come indicato qui https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work#informazioni-utili-che-ci-potrebbero-servire
Altra informazione utile potrebbe essere sapere quanti articoli ha il tuo sito perché ho appena caricato un fix con la 2.3.5 per chi ha migliaia di articoli.

**Comment by AlexTorre13** [comment]
No certo, niente cose sensibili, ma quando avete la possibilità di un report privato è meglio. Lista plugin, server, php, niente di particolare certo ma è un elenco che preferirei non mettere on line.
Grazie comunque

**Comment by overclokk** [comment]
Puoi dirmi però più o meno quanti articoli ha il tuo sito?

**Comment by AlexTorre13** [comment]
Ce ne sono vari, uno dei più grossi 15mila, un altro 8mila, roba così, niente di imponente

**Comment by AlexTorre13** [comment]
Upgrade 2.3.5 funziona perfettamente, rivedo un attimo il layout per IE ma va tutto. Grazie

**Comment by overclokk** [comment]
Ottimo allora era proprio il problema di performance che ho risolto, @beooo e @cattom se fate una prova anche voi con la versione 2.3.5 e mi dite se il problema è risolto anche per voi chiudo la issue.

**Comment by ralicata** [comment]
Ho aggiornato alla versione 2.3.5 e ora funziona tutto! grazie mille!

**Comment by overclokk** [comment]
Ottimo, aspetto @cattom ora.

**Comment by AlexTorre13** [comment]
Già detto mille volte, ma grazie delle risposte sempre pronte e dell'aiuto Overclokk. Complimenti.

**Comment by overclokk** [comment]
:-)
Intanto chiudo, se ci fosse ancora il problema con la versione 2.3.5 riapro.
