### ISSUE TITLE
ICC inietta codice nei *sitemap*.xml e nei feed

### ISSUE THREAD

**Issue by mavoga** [overclokk/italy-cookie-choices#126]
A quanto pare ICC inietta il suo codice anche in sitemap_index.xml generato dal plugin WordPress SEO di Yoast, in tutti i *_sitemap.xml da esso linkati e nelle pagine dei feed.

edit: per i feed vedi #103 
edit2: il mio sito non usa alcuna cache

**Comment by overclokk** [comment]
Faccio dei test e vedo cosa sia successo

**Comment by overclokk** [comment]
Si, ci sono dei problemi, ora vedo di risolvere.

**Comment by overclokk** [comment]
Con la versione 2.3.3 problema dovrebbe essere risolto

**Comment by mavoga** [comment]
Il 21/07/2015 18:02, Enea ha scritto:

> Con la versione 2.3.3 problema dovrebbe essere risolto

Sembra proprio tutto ok! Ancora una volta grazie di cuore.

**Comment by overclokk** [comment]
Ottimo :-)
