### ISSUE TITLE
Issue on Mobile view

### ISSUE THREAD

**Issue by Tommylip** [overclokk/italy-cookie-choices#127]
Ciao, ho notato da qualche giorno un problema su visualizzazione da mobile del mio sito (mobilitapubblicoimpieto[dot]it), dopo aver cliccato su Accetto devo per forza fare refresh altrimenti resta su questo alert errore
![issue on mobile - mpi](https://cloud.githubusercontent.com/assets/12598433/8900651/51f5239c-3442-11e5-8aab-ca26be01c8a3.PNG)

**Comment by andreapernici** [comment]
Disabilita i warning nel php.ini.

**Comment by Tommylip** [comment]
Ok, come si fa? :-S

**Comment by andreapernici** [comment]
Apri il tuo file php.ini e edita la riga relativa agli errori da mostrare. Cerca error reporting nel file.

Alternativa è farlo via .htaccess o modificando il file wp-config.php di wordpress.

**Comment by Tommylip** [comment]
ho provato ad aprire sia htacess che wp-config ma non ci sono tracce di error reporting.
Ho cercato il file php.ini ma senza successo, ho chiesto al gestore dell'hosting per capire dove trovarlo

**Comment by Tommylip** [comment]
OK
ho sentito l'assistenza Aruba e alla fine, dopo aver effettuato l'accesso al sito, ecco cosa mi hanno detto: 

Gentile cliente,
dopo aver eseguito alcuni test è emerso che il problema dato sul mobile è un bug su stringa di codice incompatibile probabilmente con il tema o con qualche plugin installato.

Le consigliamo di utilizzare questo plugin per i cookie https://wordpress.org/plugins/cookie-notice/ più semplice da usare e pienamente compatibile con wordpress e gli altri plugin da Lei installati.

:-/

**Comment by overclokk** [comment]
@Tommylip di pure ad aruba che il loro servizio è una ciofeca ;-) e che io overclokk ti ho detto che è meglio migrare ad un hosting più serio di loro ;-)
Ora vediamo come risolvere quel problema (che di per se non è un problema del plugin ma del server che come dicevo prima è una ciofeca)

**Comment by Tommylip** [comment]
Ahahahah, lo so lo so, era provocatoria la cosa! 
Però dai, mi hanno telefonato, si sono impegnati!
Se mi fai sapere ti ringrazio, io mi trovo bene con il plugin, non voglio cambiarlo e poi lo uso anche su socialmedialife.it e funziona benissimo

**Comment by overclokk** [comment]
Quando sento il nome aruba mi viene l'acido nelle vene (specialmente dopo che ho sentito alcune testimonianze di chi ci ha lavorato...)

Comunque, veniamo a noi, ho bisogno di sapere se per caso usi nextgengallery e come hai configurato il plugin.

**Comment by Tommylip** [comment]
No nexrgengallery

la cosa bella? prima l'errore appariva solo su mobile, ora anche su browser.. ma sti st...
Per i settings, ecco uno screenshot

![pannello di italy cookie choices mobilitapubblicoimpiego it wordpress](https://cloud.githubusercontent.com/assets/12598433/8952725/eefee112-35d9-11e5-885f-1518cc95b20c.png)

**Comment by overclokk** [comment]
Cominciamo a debuggare un po'

Prima di tutto togli momentaneamente la spunta sull'accettazione allo scroll e su continua la navigazione, poi li riattiverai dopo.

Poi prova senza il blocco dei cookie

Poi prova ad attivare il blocco ma cancella i custom script da bloccare che hai messo (tienili salvati da qualche parte che dopo facciamo altre prove)

Ad ogni passaggio cancella la cache del browser e refresh della pagina.

**Comment by Tommylip** [comment]
Ok ho seguito step by step e il problema sembra sorgere con il blocco dei cookie (e privo dei custom script, accettazione e scrolling attivi)

**Comment by overclokk** [comment]
Ok, disattiva il blocco totale e fammi sapere, voglio vedere nella pagina cosa c'è.

**Comment by Tommylip** [comment]
Sbloccato il Blocco dei cookies di terze parti, l'unico flaggato prima

**Comment by overclokk** [comment]
Ok, ho visto, lo script di google maps è immenso, prova a disattivare la mappa, metti il blocco totale nel plugin e vedi se cambia qualcosa.

**Comment by overclokk** [comment]
Ma hai messo il blocco nei widget?

**Comment by Tommylip** [comment]
Ok, scusami, blocco totale nel plugin come prima? 
Contenuto
Widget
Pagina
???

**Comment by overclokk** [comment]
Segui le indicazioni del mio penultimo messaggio

**Comment by Tommylip** [comment]
Si, attivato il blocco e cancellato lo script, con la Mappa attiva, dava errore. 
Disattivo la mappa e provo con Blocco Attivo e senza Script?

**Comment by overclokk** [comment]
Si, disattiva la mappa

**Comment by Tommylip** [comment]
disattivata mappa
Blocco Attivo
No Script

**Comment by overclokk** [comment]
Per ora nessun errore
Ancora con la mappa disabilitata e il blocco totale attivato, aggiungi gli script precedentemente tolti nel custom script e dimmi se ci sono errori.

**Comment by Tommylip** [comment]
oK FATTO

**Comment by overclokk** [comment]
Ok, allora il problema come puoi vedere è il codice della mappa troppo corposo per il server.

Per risolvere puoi mettere la mappa in modo che venga caricata con un'azione dell'utente, più o meno la tecnica del lazy load, almeno solo per il primo avvio della pagina.

Altrimenti altre soluzioni prevedono di mettere mano al codice.

**Comment by overclokk** [comment]
Vedi questo https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/Filters-Hook#modificare-larray-con-tutti-gli-embed-trovati-disponibile-dalla-versione-235

**Comment by Tommylip** [comment]
OK grazie mille, deciderò sul da farsi! 
Sei stato molto paziente e gentile, lo apprezzo!

**Comment by overclokk** [comment]
Se hai altri dubbi chiedi pure :-)
