### ISSUE TITLE
PHP Issue (Solved)

### ISSUE THREAD

**Issue by francescogiunta** [overclokk/italy-cookie-choices#128]
Buongiorno, intanto complimenti per l'ottimo lavoro,
Ho installato senza problemi il Plugin su un sito e funziona benissimo, ma su altri due siti da me gestiti da lo stesso errore.

Parse error: syntax error, unexpected T_FUNCTION in /web/htdocs/www.rasmataonlus.org/home/wp-content/plugins/italy-cookie-choices/includes/functions-italy-cookie-choices-lang.php on line 52

Ho provato a commentare i blocchi di codice che danno errore e a quel punto mi dice:

Activation of Italy Cookie Choices in not possible:
Your server is running PHP version 5.2.17 but this plugin requires at least 5.3

Risolto aggiornando PHP

Scrivo a beneficio comune

Grazie!

**Comment by overclokk** [comment]
Ciao @amntony grazie della notifica, ho aggiunto anche  quel file al check del php che già era presente.
