### ISSUE TITLE
Aggiornamenti versioni

### ISSUE THREAD

**Issue by kkri** [overclokk/italy-cookie-choices#129]
Ciao Enea.
Mi sono persa con i nuovi aggiornamenti, nel senso che non so più bene cosa faccia di nuovo il plugin, soprattutto per quei siti che avevo già sistemato con le vecchie versioni. 
1) In uno dovevo bloccare solo la FB fanbox e alcuni video (anche se ho messo il no-cookies a YT). Ho aggiornato il plugin alla 2.3.5 e ho visto che mi blocca correttamente tutt'e due se seleziono entrambi i primi 2 blocchi. Posso lasciare così, che mi va benissimo, o sono deprecati e verranno rimossi?
2) Chrome mi segnala in un sito alcuni elementi come "local storage" e "ID channel". Spero non siano cookies, altrimenti come vanno bloccati?
3) qual è il browser o tool più affidabile per trovare i cookies? Molti dicono Chrome, ma se mi elenca anche quelli che non sono cookies, invece di aiutarmi, mi complica la vita.
Grazie, ciao.

**Comment by overclokk** [comment]
Ciao @kkri 
ogni aggiornamento è documentato sul changelog nel file readme.txt
1-Non abbiamo ancora deciso, ma per ora finché non troviamo una soluzione per NGG rimangono.
2-Dipende, serve un link
3-Chrome e firefox

**Comment by kkri** [comment]
Ciao Enea.
Non mi sono spiegata: poichè alcuni siti li ho sistemati, devo per forza aggiornare la versione e poi eventualmente anche le impostazioni? Quelli che avevo sistemato speravo di non toccarli più.
1) spero rimangano ...
2) perchè "local storage" e "ID channel" non sono uguali in tutti i siti? mi serviva un criterio generale. http://www.caffedelporto.it/
3) ok

**Comment by overclokk** [comment]
E' come quando aggiorni WordPress.
1- NGG è una gatta da pelare
2- tutto a posto, non vedo nulla di cui preoccuparsi

**Comment by kkri** [comment]
Per l'aggiornamento del plugin: è possibile che si debba ricontrollare e cambiare il tipo di blocco dei vari elementi perchè potrebbe essere che una versione nuova si comporti diversamente dalle precedenti?
2) intendi che non sono cookies e quindi non vanno nè bloccati, nè citati? devo sistemare altri 2 siti: posso considerarli "innocui" ugualmente o potrebbero dover essere bloccati in altri siti? Grazie.

**Comment by overclokk** [comment]
Quando aggiorni WordPress devi ricontrollare tutte le impostazioni? Idem con i plugin.
Se cambia qualcosa prima di eliminare la funzionalità viene deprecata e rimane per diverso tempo finché non si è sicuri che chi la stia utilizzando abbia migrato alla nuova.
2-intendo che per ora non ci sono specifiche riguardo a local storage e quindi non dobbiamo fare nulla.
