### ISSUE TITLE
bloccare google map

### ISSUE THREAD

**Issue by Dragonheart84** [overclokk/italy-cookie-choices#130]
Salve, ho provato a bloccare le mappe di google copiando il codice iframe trovato nel sorgente della pagina nella sezione "Scripts to be blocked" ma non mi riesce a bloccare nulla. Qualcuno potrebbe aiutarmi? magari con un esempio. E' un codice iframe

**Comment by overclokk** [comment]
Ciao @Dragonheart84 
hai messo la spunta anche sulla terza checkbox?

**Comment by Dragonheart84** [comment]
Ciao! perfetto. grazie.

**Comment by overclokk** [comment]
Di nulla :+1:
