### ISSUE TITLE
Non viene visualizzato il plugin nel sito

### ISSUE THREAD

**Issue by carist1** [overclokk/italy-cookie-choices#131]
Salve, volevo chiedervi come mai nel mio blog quando attivo il vostro plugin non mi compare nessun messaggio per avvertirmi dei cookie...

Il mio blog è www.paraddi.it

Qui le immagini della configurazione del plugin:

http://i.imgur.com/7ArbZYM.png

**Comment by overclokk** [comment]
Ciao @carist1 molto probabilmente hai il cookie del plugin già settato nel browser scrollando o navigando nel tuo sito, cancella la cache, apri una nuova tab e digita a mano il nome del tuo sito, aspetti che si carichi e non scrollare, così vedrai il banner (che io vedo).
