### ISSUE TITLE
Google maps

### ISSUE THREAD

**Issue by kkri** [overclokk/italy-cookie-choices#132]
Ciao Enea.
Devo creare un nuovo sito per un'associazione che ha 50 circoli. Devo prevedere una mappa di Google per ogni circolo all'interno di ciascuna pagina dedicata e poi una mappa generale con tutti i markers di dove sono posizionati i circoli. Entrambi i tipi di pagine le costruirò con gli elementi di Visual Composer: per la mappa posso utilizzare sia un blocco di testo che un elemento di Visual Composer proprio per le Google maps. Visto che posso ancora scegliere il plugin delle mappa e il tipo di elemento da utilizzare, in tutti i casi riuscirò a bloccare i cookies delle mappe in una botta sola? Come devo impostare ICC o c'è comunque un modo per evitare rogne a monte? Grazie ;)

**Comment by overclokk** [comment]
Ciao @kkri 
se in quel sito non userai NGG allora potrai customizzare cosa bloccare e cosa no, se il plugin carica la mappa nel content allora viene bloccato in automatico, se il codice della mappa è troppo grosso ci potrebbero essere dei problemi https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/Custom-script alla fine della guida ho aggiunto un nuovo paragrafo.

**Comment by kkri** [comment]
Ciao Enea.
Non userò NGG perchè il sito lo sto iniziando adesso e lo eviterò come la peste (qualsiasi altra galleria va bene?). Inserirò però sicuramente le mappe singole e anche quella generale dentro elementi di testo di Visual Composer. Se sono lì dentro ICC li blocca? 
In che caso il codice della mappa diventa troppo grosso? Io gli cambierò solo le dimensioni, non ho idea quali scelte influenzino le dimensioni del codice.

**Comment by overclokk** [comment]
In teoria si ma provale per sicurezza.
Il plugin blocca in automatico tutto ciò che sta nel content del sito.
Il problema era dovuto a troppi marker nella mappa (centinaia).
Ma come sempre, l'unico modo è testare le varie opzioni.

**Comment by kkri** [comment]
1) Proverò con un paio di mappe inserite con VComposer e spero che le blocchi.
2) Si possono scegliere più combinazioni di blocco con ICC o una sola?
3) La mia mappa generale avrà circa 50 markers, potrebbe dar problemi?

**Comment by overclokk** [comment]
1 e 3 Prova e dimmi se è tutto ok
2 ?

**Comment by kkri** [comment]
2) mi fa scegliere più di un blocco contemporaneamente? Mi sembra di averlo fatto in un'altra versione.
3) quelle singole va bene, ne provo un paio, ma quando ne ho caricate 50 è troppo tardi, per questo te lo chiedo adesso ... Ancora posso adottare qualche scappatoia, dopo solo parolacce :)

**Comment by overclokk** [comment]
2) La 3° esclude le altre due
3) Devi provare, non so quale sia il limite.
