### ISSUE TITLE
PHP Notice

### ISSUE THREAD

**Issue by aldolat** [overclokk/italy-cookie-choices#133]
Ciao,
segnalo questa notifica PHP:

```
PHP Notice:  Undefined index: HTTP_ACCEPT in /var/www/html/wpsvn/wp-content/plugins/italy-cookie-choices/classes/class-italy-cookie-choices-front-end.php on line 251
```

Versione 2.3.5 del plugin.

**Comment by floryn90** [comment]
@overclokk si deve solo cambiare i doppi apici con singoli apici.

**Comment by overclokk** [comment]
Grazie @aldolat per la segnalazione
@floryn90 Applicato la modifica, prossima release sarà presente, grazie mille.

**Comment by aldolat** [comment]
@overclokk La notifica è tutt'ora presente:

```
Notice: Undefined index: HTTP_ACCEPT in /var/www/html/wpsvn/wp-content/plugins/italy-cookie-choices/classes/class-italy-cookie-choices-front-end.php on line 252
```

**Comment by overclokk** [comment]
@aldolat non è ancora stata caricata sul repo di WordPress, la modifica è comunque presente nel codice, appena ho un po' di respiro carico tutto.

**Comment by aldolat** [comment]
@overclokk grazie! :)

**Comment by overclokk** [comment]
:+1:

**Comment by aldolat** [comment]
@overclokk solo per tua informazione:

```
[03-Apr-2016 10:28:05 UTC] PHP Notice: Undefined index: HTTP_ACCEPT in /PATH_TO_WP/wp-content/plugins/italy-cookie-choices/classes/class-italy-cookie-choices-front-end.php on line 267
```

Ciao
