### ISSUE TITLE
Problema aggiornamento pagina

### ISSUE THREAD

**Issue by stefanlo** [overclokk/italy-cookie-choices#134]
Complimenti per il puug in davvero ben fatto e conforme alle leggi italiane, l'unico problema che riscontro è che dopo l'accettazione dei cookie non avviene l'aggiornamento automatico e la pagina si blocca mostrando solo alcuni banner pubblicitari, se è possibile ricevere un aiuto per la soluzione di questo problema te ne sarei infinitamente grato,

**Comment by overclokk** [comment]
Ciao @stefanlo in questi giorni non sono ancora attivo ma se intanto vuoi scrivere la tua url e le impostazioni del plugin appena sono libero ci guardo.

**Comment by stefanlo** [comment]
Ciao Enea 
Ti ringrazio per la risposta mi complimento ancora per il plugin davvero efficiente e ben fatto, credo di aver risolto il problema, praticamente andava in conflitto con un altro script che poi ho eliminato.
Vorrei comunque farti una domanda e cioè se il plugin può influire negativamente sugli spider dei motori di ricerca visto che blocca tutto prima del consenso.
Grazie in anticipo per l'eventuale risposta.
Saluti

**Comment by overclokk** [comment]
Ciao @stefanlo no, nessun problema con gli spider.

**Comment by stefanlo** [comment]
Grazie davvero gentilissimo, purtroppo il plugin mi sta dando nuovamente il problema che dopo l'accettazione dei cookie non aggiorna automaticamente la pagina e rimane la pagina bianca fin quando non la si aggiorna manualmente. Non so se riesci a dare un occhiata al mio sito www.stefanlotto.com spero di poter risolvere questo problema se c'è da farti qualche donazione no problem.
Grazie

**Comment by overclokk** [comment]
Vedo che ci sono diversi problemi nel sito, segui queste indicazioni e vedi se riesci a risolvere https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work

**Comment by stefanlo** [comment]
Ciao Enea
Ho seguito tutte le indicazioni della guida ma purtroppo non sono riuscito a risolvere il problema che continua a persistere anche con tutti i plugin disattivati, ho anche disinstallato e reinstallato il tuo plugin ma senza nessun risultato, non essendo molto esperto non riesco a capire quali errori possono esserci nel mio sito, non so se puoi aiutarmi, o non so se il tuo plugin sarà anche in futuro modificato per ovviare a questo problema, ti ringrazio per il tuo supporto

**Comment by overclokk** [comment]
Se hai il problema anche con tutti i plugin disattivati forse allora è il template, prova quello standard di WordPress.

**Comment by stefanlo** [comment]
Ciao, 
Credo di aver risolto in questo modo: ho controllato tutti gli script che generano banner pubblicitari ed in effetti ce ne sono due in particolare che provocavano il problema, eliminandoli sembra che sia ritornato a funzionare tutto correttamente,
solo che purtroppo i banner a cui sono costretto a rinunciare sono proprio quelli che mi generavano i maggiori guadagni, te li elenco qui di seguito non so se puoi dargli un occhiata e darmi qualche indicazione poterli nuovamente inserire senza che vengano provocati problemi:
BANNER 1
Questo è il codice che viene inserito in head: <script type="text/javascript" src="http://c.ad6media.fr/l.js"></script>

e questo è il codice che viene inserito nell’ html pagina per visualizzare il banner: 



<script type="text/javascript">ad6b728('jmquomqhg3');</script>



<script type='text/javascript'>

</script>

<noscript><iframe width="300" height="250" scrolling="no" frameborder="0" framespacing="0" marginheight="0" marginwidth="0" src="http://adv.adsbwm.com/www/delivery/inj.php?zid=MDRkNDAyYmJiZjg2ZWYwYWQwYTQ5ZjMwM2JlYmEyM2Q0ZTc5NmZjNTBiMzgzMTAzMGFhMThjZTA4ZjIzNDY2MzdlZmNmNTNhYmU"></iframe></noscript>

---

Anche cambiando il template il problema non viene risolto, la ma cosa strana è che in un altro mio sito uso comunque i due banner appena elencati e non si riscontra nessun problema,
se riesci a darmi delle indicazioni o dei suggerimenti per poter risolvere questo problema te ne sarei davvero grato.

**Comment by andreapernici** [comment]
Questi AdServer sono pessimi stefanio. Usando JS sincrono e spesso il male di ogni male (document.write) c'è poco che si possa fare per ripristinarli dinamicamente.

L'unica cosa possibile è il refresh o farli vedere solo alla seconda view.
