### ISSUE TITLE
Cannot view the banner after Wordpress 4.3 update

### ISSUE THREAD

**Issue by giuliapettinau** [overclokk/italy-cookie-choices#135]
Dear Support, I cannot see anymore the banner.  I've deleted the cache tick off on the mouse scroll and navigation. www.sportgrandtour.it
Thanks

**Comment by overclokk** [comment]
Hi, please follow these steps https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work and let me know if you resolved the issue.

**Comment by ynnesti** [comment]
stesso problema per me (ma è un impressione, o siamo tutti italiani). Ho disattivato il plugin.. spero si possa risolvere la compatibilità.. (mi segnalano che non funziona nemmeno da BackBerry..) Grazie!

**Comment by floryn90** [comment]
@overclokk penso di aver capito quale è il problema! La variabile per il consenso dei cookie viene confermata a priori se ci sono dei lazyload e le opzioni "attiva sul scroll del mouse" e "attiva se l'utente continua la navigazione". Infatti per riprodurre questo problema, devi usare un qualsiasi plugin/template che fa uso di lazyload e attivare le suddette opzioni. Se disattivi le 2 opzioni, il plugin funziona correttamente.

**Comment by overclokk** [comment]
@ynnesti hai fatto le prove indicate nel link sopra? Senza quelle non posso sapere perché hai quel problema, io ho aggiornato il plugin su decine di siti 4.3 e nessun problema.

@floryn90 sul mio sito ho il lazyload con quelle opzioni attive ma non riscontro il problema, mi puoi dire quale lazy utilizzi?

**Comment by Firstclass70** [comment]
Anche io ho problemi. Nno mi vusualizza il banner :-(
Wordpress ultima versione. Ho attivato i ltema base e disattivato tutti i plugin, ma nulla.
Aiutoooo :-)
