### ISSUE TITLE
Problema con descrizione sito su Bing

### ISSUE THREAD

**Issue by MatLau** [overclokk/italy-cookie-choices#136]
Come faccio ad evitare che Bing metta nella descrizione del mio sito lo script sulla Cookie Law?  
Sotto il titolo del sito compare:
" \r\n\r\nQuesto sito o gli strumenti terzi da questo utilizzati si avvalgono di cookie necessari al funzionamento ed utili alle finalit\u00e0 …

**Comment by overclokk** [comment]
Ciao @MatLau nelle prossime versioni è previsto il check se il visitatore è un motore di ricerca o meno in modo da evitare problemi per siti poco ottimizzati SEO.

Ciao
