### ISSUE TITLE
Colore link Privacy Policy e Chiudi

### ISSUE THREAD

**Issue by Dragonheart84** [overclokk/italy-cookie-choices#139]
Buongiorno, se volessi tenere come opzione dello stile del banner la prima della tendina e modificare solo il colore dei due pulsanti link come posso fare? Si potrebbe avere un esempio di css personalizzato da inserire nel campo? GRazie.

**Comment by overclokk** [comment]
Ciao @Dragonheart84 questo è lo stile di default

```
<style type="text/css">#cookieChoiceInfo{background-color: #ffffff;color: #000000;left:0;margin:0;padding:4px;position:fixed;text-align:center;top:0;width:100%;z-index:9999;}.italybtn{margin-left:10px;}</style>
```

Se la inserisci nella textarea custom CSS  le altre opzioni sono disattivate tranne la scelta per le classi degli elementi.
