### ISSUE TITLE
non compare il banner

### ISSUE THREAD

**Issue by gabri26** [overclokk/italy-cookie-choices#141]
Salve,
se metto il flag su "Attiva l'accettazione se l'utente continua la navigazione" mi scompare il banner, si crea immediatamente il cookie di accettazione.
Anche se cancello il cookie e faccio refresh della pagina, non compare il banner perchè si è immeditamente risalvato il cookie.
uso wordpress 4.3.1 e il tema Divi comprato su elegant theme

**Comment by overclokk** [comment]
Ciao @gabri26 il refresh è considerato come navigazione, per vedere il banner devi ridigitare la url nella barra degli indirizzi e dare invio.

**Comment by gabri26** [comment]
Ok, grazie mille, così funziona.

**Comment by overclokk** [comment]
Ottimo :-)
