### ISSUE TITLE
plugin correctly installed and set, but I cannot see the banner

### ISSUE THREAD

**Issue by maricol24** [overclokk/italy-cookie-choices#142]
Goodmorning everyone,
I installed the plugin on the wordpress website, set it correctly, cleaned cache, but the banner in the homepage does not appear. 
Can anybody help me to understand how to fix it?

**Comment by overclokk** [comment]
Hi @maricol24 ,
have you checked the first checkckbox "Activate"?

**Comment by maricol24** [comment]
Yes, checked!

**Comment by overclokk** [comment]
Can I see your site, please? Is active now?

**Comment by maricol24** [comment]
Yes, sure 
http://www.coppolafoods.com/

**Comment by overclokk** [comment]
Do you use any kind of cache?

**Comment by maricol24** [comment]
Onestly, I don't know, I manage the website in wordpress, but I did not create it

**Comment by overclokk** [comment]
I understod the problem, you have WordPress installed in a directory (/en/) not in the root, Italy Cookie Choices works only in that directory, indeed I can se the banner at the bottom of the page in the http://www.coppolafoods.com/en/
If you want add the banner in http://www.coppolafoods.com/ too you have to add the script cookiechoices in your index.html, you can see how it works in this link https://www.cookiechoices.org/

**Comment by maricol24** [comment]
Ok thank you so much. I have a doubt, in wordpress the index.html is called index.php. Precisely where do I have to add cookiechoices  in the script?

**Comment by overclokk** [comment]
In your root folder is good also index.php (and if I understood well is not WordPress file), you can put the script before </body> at the bottom of the page, is there a body tag in that page? (open with a text editor and see it)
