### ISSUE TITLE
accettazione e navigazione

### ISSUE THREAD

**Issue by stefanorss** [overclokk/italy-cookie-choices#143]
ciao
ho installato il plugin sul mio sito promediabox.com che utilizza wordpress 4.0.1
Riscontro un problema con l'opzione "Attiva l'accettazione se l'utente continua la navigazione"... il banner non scompare se continuo la navigazione cliccando per esempio su un qualsiasi link all'nterno del sito come mi sarei aspettato accadesse.
Possibili soluzioni?
Grazie

**Comment by overclokk** [comment]
Ciao @stefanorss hai già fatto queste prove?
https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work
