### ISSUE TITLE
Accettazione con scroll

### ISSUE THREAD

**Issue by andrea2880** [overclokk/italy-cookie-choices#144]
Buongiorno,

complimenti per il plugin davvero utile.

Avrei però una domanda. Con alcuni template attivando l'opzione "accettazione con scroll" dopo alcuni instanti la pagina effettua un rapido refresh ed autorizza da solo i cookie.

Ho già fatto le prove come da voi indicato in https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work, ma senza successo?

Mi succede con più di un template... Cosa posso fare?

Grazie in anticipo

**Comment by overclokk** [comment]
Ciao @andrea2880 
con il tema standard di WordPress ti da lo stesso problema?

**Comment by andrea2880** [comment]
Ho aggiornato il tema ed ora sembra non farlo più, con il tema standard non lo fa. Ho riscontrato più temi che fanno conflitto in qualche maniera con l'accettazione on scroll.

**Comment by overclokk** [comment]
Ottimo!

Se lo fa solo con alcuni temi allora il problema è proprio nel tema stesso, può essere del codice che crea conflitto e bisognerebbe debuggare per capire cosa sia, ma l'importante è che ora funzioni.

Ciao
