### ISSUE TITLE
firefox non risponde..

### ISSUE THREAD

**Issue by menhir2015** [overclokk/italy-cookie-choices#146]
Ciao dopo l'ultimo aggiornamento si è verificata una situazione strana su firefox 42.0 ( su chrome o opera  e IE9 funziona perfettamente) viene visualizzato il popup (ho impostato il dialog), ma al click il dialog non viene chiuso e cosa ancora piu strana dalla console si vede chiaramente che il cookie displayCookieConsent viene settato  prima ancora che io clicchi su banner!!
questi sono i plugin attualmente attivi
Contact Form 7
Italy Cookie Choices (for EU Cookie Law)
TinyMCE Advanced
UpdraftPlus - Backup/Restore
WooCommerce
WP All Import
WP All Import - WooCommerce Add-On
Yoast SEO
PS ovviamente non sono loggato su FF da admin quando ho fatto i test
PS uso win8.1

**Comment by overclokk** [comment]
Ciao @menhir2015 
potresti indicarmi la url del tuo sito che verifico?

**Comment by menhir2015** [comment]
ciao avevo disattivato il plugin in attesa di risposta..
il sito è questo
http://www.wellcomecomputerchiavari.com/
ps in console (firebug) non vedo errori..

**Comment by overclokk** [comment]
Appena provato con firefox 42 ma non ho avuto nessun problema, il funzionamento mi sembra nella norma, dovresti provare a pulire la cache del browser, ccleaner se sei da Win, oppure provarlo su un altro pc.
Altra cosa, perché usi il banner se il sito non setta nessun cookie?

**Comment by menhir2015** [comment]
ciao fatto pulizia con ccleaner (completa) adesso funziona, ho capito il problema..
avevo cambiato il valore del cookie per fare dei test, e ff si teneva in memoria il vecchio valore, dato che mi dava lo stesso problema con tutti i browser all'inizio a causa di un plugin che avevo installato (Woocommerce Products Per Page) che invece interferiva.
Piu tardi attivo anche iThemes Security e ti faccio sapere..
PS il cliente vuole fb+g+ etc ma non l'ho ancora attivati..

**Comment by overclokk** [comment]
Perfetto, problema risolto :-)

Ok, se li attivi dopo va bene.
