### ISSUE TITLE
Blocchi non richiesti

### ISSUE THREAD

**Issue by kkri** [overclokk/italy-cookie-choices#147]
Ciao Enea. Uso il tuo plugin in diversi siti e tutto OK. Lo stavo inserendo in un sito dove ho solo i cookies Facebook Connect e Facebook Social Plugins che praticamente sarebbero la fanbox di FB che c'è nel footer. Pensavo fosse una passeggiata e invece ho provato tutte le combinazioni, ma non riesco a bloccarli. Se scelgo le prime due possibilità di tipo di blocco, mi crea il banner, ma non mi blocca i cookies, anche integrandoli con il blocco dello script manuale o scegliendo Facebook nel menù a tendina degli script da bloccare. Se scelgo il terzo blocco, funziona, ma, oltre a bloccare FB, crea altri due avvisi di blocco che non capisco cosa siano, perchè in realtà non c'è nessun elemento da bloccare dove c'è quel riquadro con l'avviso, vedi screenshot su https://www.dropbox.com/s/hquj18bwoeeykob/ss-icc-impostazioni.jpg?dl=0
Ho provato tutte le combinazioni possibili, ma nada, mi diresti come posso fare? Mi dispiace disturbarti nel weekend, ma il cliente prima se l'è presa comoda, poi oggi voleva pubblicare il sito al volo. Se ci fossi riuscita, non c'era problema, ma adesso lunedì lo vorranno prontissimo :(
Il sito non è ancora online, ma se serve posso crearti come utente per entrare.
Grazie 1000.
Cristina

**Comment by overclokk** [comment]
Ciao Cristina,
il codice custom e i menù a tendina funzionano solo per il terzo blocco, non per i primi due.
Il banner viene inserito perché in realtà c'è il codice javascript nascosto nel sorgente della pagina in quella posizione quindi devi trovare quel codice e inserirlo nel box "codice da non bloccare" oppure usare i menù a tendina sempre nella stessa sezione.

Prova e dimmi se risolvi.

Ciao

**Comment by kkri** [comment]
Ciao Enea.
Ho capito il criterio ma non so quale codice javascript cercare perchè in realtà non mi sta nascondendo nessun elemento. Ho guardato nel sorgente ma non so dove andare ... Probabilmente ho detto una stupidaggine, ma non sono così brava. Ho scoperto il sito, mi dai un’occhiata per vedere dove prendere gli scripts?
Ho trovato anche un cookie di Twitter sotto ai posts, per quello come devo procedere?
thanx
Cristina

**Comment by kkri** [comment]
Urk, l’indirizzo

http://www.aclipesaro.it/

**Comment by overclokk** [comment]
Per inserire i vari banner che sostituiscono gli script presenti nella pagina (non quello standard) viene creato un elemento `<div class="el"></div>` inserito al posto dello script al cui interno viene "appeso" il codice che mostra il banner del blocco degli script quindi per trovarlo basta cliccare sul banner stesso e cliccare sulla voce "ispeziona elmento", questo ti mostrerà la posizione e il codice del banner incriminato, ora devi salire di un livello rispetto all'elemento `<div class="el"></div>` ovvero clicchi sul div contenitore genitore, per esempio mettiamo che tu hai lo snippet precedente in questo modo:

```
<div class="tua_classe">
    <div class="el">qui c'è il resto del codice</div>
</div>
```

In questo caso clicchi sul div con classe "tua_classe" in modo che venga evidenziato poi clicchi sul pulsante di accettazione (e noterai che il banner sparisce sostituito da un tag `<cookie></cookie>`) e fai un refresh della pagina, quando la pagina sarà totalmente ricaricata troverai magicamente lo script che era stato bloccato, ora puoi fare copia e incolla e potrai inserirlo nel box per il blocco (in teoria il codice inserito così funziona ma in alcuni casi può non funzionare correttamente quindi è da provare).

Il secondo metodo si può fare utilizzando il filtro `icc_output_html` presente nel plugin ma bisogna conoscere il php (seguirà una guida)

Ad ogni modo questo è il codice che ho trovato:

```
<script>var block_td_uid_1_5658b9402eab3 = new td_block();
block_td_uid_1_5658b9402eab3.id = "td_uid_1_5658b9402eab3";
block_td_uid_1_5658b9402eab3.atts = '{"autoplay":"3","installed_post_types":"post","limit":"4","custom_title":"","td_filter_default_txt":"Tutto","class":"td_block_id_2199532288 td_uid_1_5658b9402eab3_rand"}';
block_td_uid_1_5658b9402eab3.td_column_number = "2";
block_td_uid_1_5658b9402eab3.block_type = "td_block_slide";
block_td_uid_1_5658b9402eab3.post_count = "4";
block_td_uid_1_5658b9402eab3.found_posts = "16";
block_td_uid_1_5658b9402eab3.header_color = "";
block_td_uid_1_5658b9402eab3.ajax_pagination_infinite_stop = "";
block_td_uid_1_5658b9402eab3.max_num_pages = "4";
td_blocks.push(block_td_uid_1_5658b9402eab3);
</script>
```

```
<script>var block_td_uid_3_5658ba1e3486b = new td_block();
block_td_uid_3_5658ba1e3486b.id = "td_uid_3_5658ba1e3486b";
block_td_uid_3_5658ba1e3486b.atts = '{"custom_title":"ULTIME NOTIZIE","custom_url":"http:\/\/www.aclipesaro.it\/category\/news\/","category_ids":"-1","limit":"4","offset":"1","td_ajax_filter_type":"td_category_ids_filter","td_filter_default_txt":"Tutto","class":"td_block_id_2746753665 td_uid_3_5658ba1e3486b_rand"}';
block_td_uid_3_5658ba1e3486b.td_column_number = "1";
block_td_uid_3_5658ba1e3486b.block_type = "td_block_7";
block_td_uid_3_5658ba1e3486b.post_count = "4";
block_td_uid_3_5658ba1e3486b.found_posts = "16";
block_td_uid_3_5658ba1e3486b.header_color = "";
block_td_uid_3_5658ba1e3486b.ajax_pagination_infinite_stop = "";
block_td_uid_3_5658ba1e3486b.max_num_pages = "4";
td_blocks.push(block_td_uid_3_5658ba1e3486b);
</script>
```

Eventualmente controlla anche nel sorgente della pagina (ctrl + u) se è scritto corretto.

Ciao

**Comment by kkri** [comment]
Ho seguito il tuo tutorial (eccezionale!) e ho inserito i 2 scripts da non bloccare e attualmente con il blocco 3, non appaiono più i 2 box del blocco ma anche il widget di FB nel footer non viene bloccato. Ho provato a bloccarlo dal menù a tendina –> facebook ma mi incasina tutto il layout il sito (mi è preso un colpo), ho provato ad inserire il codice sotto nel box degli scripts da bloccare e non lo blocca. 

<script>(function(d, s, id) {
                      var js, fjs = d.getElementsByTagName(s)[0];
                      if (d.getElementById(id)) return;
                      js = d.createElement(s); js.id = id;
                      js.src = "//connect.facebook.net/it_IT/all.js#xfbml=1&appId=395202813876688";
                      fjs.parentNode.insertBefore(js, fjs);
                    }(document, 'script', 'facebook-jssdk'));</script>
“Spero” di aver sbagliato a prendere il codice oppure di aver sbagliato qualcos’altro di sintassi o poco grave (il SEP quando c’è solo uno script ci va?)
Mi diresti anche il codice per bloccare il cookie Twitter button che crea da sotto i posts, non lo trovo, credo sia un caso un po’ diverso, o no?
Idee?
--------------------------------------------------------------------------------

**Comment by overclokk** [comment]
Il menù a tendina lavora come la text area per l'inserimento degli script ma ti permette di evitare di inserire i separatori manualmente, inoltre puoi inserire dei valori custom oltre quelli presenti nella tendina, se facebook non funziona puoi vedere nello script da bloccare quale parola usare presente nello script e inserirla in una nuova input vuota.
Però il tuo problema è che ora che hai inserito quei due snippet facebook non te lo blocca più, allora dovresti provare invece di inserire i due snippet interi inserire solo una parte e sfruttando sia i separatori sia il tag something o in alternativa usare le nuove tendine che semplificano l'utilizzo.

**Comment by kkri** [comment]
Sto andando via. Nel pomeriggio provo quello che mi hai detto, ma something non ho mai capito come funziona. Le  tendine posso usarle solo col 3 blocco? Se uso quelle però torno come all’inizio che mi blocca anche gli altri 2 elementi in alto v.dropbox, no?

**Comment by kkri** [comment]
Ciao Enea.
Ho fatto una marea di prove: con gli script da bloccare, quelli da non bloccare, con le tendine, con tutti i tipi di blocco ecc. Credo di aver incrociato tutte le combinazioni possibili, ma o si blocca FB e anche gli altri 2 script, oppure non si blocca nessuno dei 3. Spero comunque di sbagliare qualcosa da qualche parte, ma ormai non so più quale altra prova fare. Ho anche un cookie di Twitter provenineti dai posts da bloccare, ma immagino che se si riesce a bloccare FB, si potrà usare lo stesso metodo. Mi daresti un’occhiata tu, altrimenti non riesco a finire domani, e lunedì quelli del sito saranno agguerriti ... Ti lascio il sito visibile, sperando non si accorgano ...
www.aclipesaro.it

Grazie 1000.
Cristina

**Comment by overclokk** [comment]
Ciao Cristina, ti ho editato il messaggio perché non si mettono mai in pubblico user e password, questa non è una conversazione privata e tutti potrebbero accedere al sito e fare danni.

Io posso aiutarti qui, su questa discussione, ma dovrai agire tu fisicamente sul sito, di più non posso fare.

I menù a tendina funzionano allo stesso modo dei tag `<---------SOMETHING--------->` ma ti danno il vantaggio di saltare la parte di configurazione dello snippet e utilizzare direttamente la tendina inserendo quella piccola porzione di codice che è presente solo in quello snippet, ti faccio un esempio, mettiamo che tu abbia il seguente script (o iframe o embed):

``` javascript
<script>
codice script
var variabile = 1;
faunzione(){
   eseguo qualcosa;
}
</script>
```

Ovviamente è finto codice ma è solo per fare un esempio, ora se osservi bene dentro quello snippet noterai che ci sono delle "parole", codice, script, variabile ecc, bene, ora potresti per esempio creare uno snippet di blocco in questo modo:

``` javascript
<script><---------SOMETHING--------->variabile<---------SOMETHING---------></script>
```

Come vedi ho sfruttato il nome "variabile" presente nello snippet precedente è ho inserito i tag `<---------SOMETHING--------->` alla sua sinistra e alla sua destra, la stessa cosa la possiamo fare con gli script che caricano un file piuttosto che avere il codice al suo interno semplicemente usando il tag `<---------SOMETHING--------->` subito appena dopo "script"

``` javascript
<script<---------SOMETHING--------->NOME DEL FILE<---------SOMETHING---------></script>
```

Vedi la differenza fra i due?
Bene, i vari select (le tendine) svolgono la stessa funzione dello snippet precedente ma ti risparmiano il tempo di dover scrivere tutto quel codice poiché verrà aggiunto in automatico da dentro il programma tu dovrai solo inserire la parole dentro la input vuota che nel nostro caso è "variabile", ora seguendo questa logica puoi applicare il sistema a script più complessi, ovviamente non è infallibile quindi dovrai tentare finché non trovi la combinazione giusta.

**Comment by kkri** [comment]
Grazie Enea, non avevo capito fosse pubblica, comunque ho cancellato l’utente.
Nonostante la tua spiegazione dettagliata, non posso assicurare di aver capito bene. Ho provato a scrivere <script><---------SOMETHING--------->numero ID dell’app di facebook<---------SOMETHING---------></script>e poi l’ho messo nell’input degli script da bloccare, ma senza risultati. Pensavo che, mettendo un dato univoco come l’app ID di FB, avrebbe individuato lo script giusto. 
In realtà l’unica cosa che mi servirebbe, sarebbe bloccare FB e Twitter, se mi funzionavano i blocchi dalle tendine, sarei stata felice, e avrei finito in un secondo. Mi potresti suggerire la porzione di codice o la parola che potrebbe bloccare lo script di FB e di Twitter? 
Grazie, comincio a essere preoccupata perchè sono decisamente in confusione perchè non ci capisco quasi niente, in altri siti a parità di posizione (footer) riusciva a bloccarli.
Cristina 

Ciao Cristina, ti ho editato il messaggio perché non si mettono mai in pubblico user e password, questa non è una conversazione privata e tutti potrebbero accedere al sito e fare danni.

Io posso aiutarti qui, su questa discussione, ma dovrai agire tu fisicamente sul sito, di più non posso fare.

I menù a tendina funzionano allo stesso modo dei tag <---------SOMETHING---------> ma ti danno il vantaggio di saltare la parte di configurazione dello snippet e utilizzare direttamente la tendina inserendo quella piccola porzione di codice che è presente solo in quello snippet, ti faccio un esempio, mettiamo che tu abbia il seguente script (o iframe o embed):

<script>
codice script
var variabile = 1;
faunzione(){
   eseguo qualcosa;
}
</script>Ovviamente è finto codice ma è solo per fare un esempio, ora se osservi bene dentro quello snippet noterai che ci sono delle "parole", codice, script, variabile ecc, bene, ora potresti per esempio creare uno snippet di blocco in questo modo:

<script><---------SOMETHING--------->variabile<---------SOMETHING---------></script>Come vedi ho sfruttato il nome "variabile" presente nello snippet precedente è ho inserito i tag <---------SOMETHING---------> alla sua sinistra e alla sua destra, la stessa cosa la possiamo fare con gli script che caricano un file piuttosto che avere il codice al suo interno semplicemente usando il tag <---------SOMETHING---------> subito appena dopo "script"

<script<---------SOMETHING--------->NOME DEL FILE<---------SOMETHING---------></script>Vedi la differenza fra i due?
Bene, i vari select (le tendine) svolgono la stessa funzione dello snippet precedente ma ti risparmiano il tempo di dover scrivere tutto quel codice poiché verrà aggiunto in automatico da dentro il programma tu dovrai solo inserire la parole dentro la input vuota che nel nostro caso è "variabile", ora seguendo questa logica puoi applicare il sistema a script più complessi, ovviamente non è infallibile quindi dovrai tentare finché non trovi la combinazione giusta.

**Comment by overclokk** [comment]
Facebook lo avevi bloccato, perché ora non riesci?

**Comment by kkri** [comment]
Facebook riesco a bloccarlo solo scegliendo il blocco 3 e nient'altro, ma appare anche il "blocco" degli altri 2 elementi, che in realtà non blocca e non deve bloccare. Questo era il primo tentativo che avevo fatto.

**Comment by overclokk** [comment]
I primi due lavorano solo sui widget e sul contenuto (ovvero gli articoli), il terzo lavora su tutto ma con un criterio differente, header e footer sono lasciati a parte (perché in header e footer molto spesso ci sono script importanti per il funzionamento del sito)
Ti scompongo la pagina seguendo lo schema del plugin con un esempio di HTML dummy:

## Contenuto in header

```
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <?php wp_head(); ?>
    </head>
```

## Contenuto in body

```
    <body>
        <div>
            <div>
                <p>Contenuto</p>
            </div>
        </div>
```

## Contenuto in footer

```
        <?php wp_footer(); ?>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.2.min.js"><\/script>')</script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X');ga('send','pageview');
        </script>
    </body>
</html>
```

Spero che così sia più chiaro.

**Comment by kkri** [comment]
La fanbox di FB che dovrei bloccare è un widget nel footer, col blocco 2 dovrebbe bloccarlo, no? Purtroppo non lo blocca.

**Comment by kkri** [comment]
Mettendo il blocco 3, oltre a "bloccare" gli altri 2 elementi in alto, il sito si vede su Chrome, mentre su FF e su IE si vede una pagina bianca.

**Comment by overclokk** [comment]
Pagina bianca può essere tutto come può essere niente, in queste situazioni devi seguire le indicazioni che ho scritto qui https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work è probabile che sia un conflitto con qualcosa.

**Comment by kkri** [comment]
Sì, ma non capisco perchè su Chrome funziona, ma non ho conoscenze sufficienti per questo. Ho risolto con un altro plugin, purtroppo per questo sito ho una fretta del diavolo, ma per i prossimi ci rriprovo ;). Intanto grazie mille della disponibilità.

**Comment by overclokk** [comment]
Nessun problema :-)
