### ISSUE TITLE
PHP 7.0 - Fatal error: 'continue' not in the 'loop' or 'switch'

### ISSUE THREAD

**Issue by Daneel87** [overclokk/italy-cookie-choices#149]
Fatal error: 'continue' not in the 'loop' or 'switch' context in italy-cookie-choices/admin/class-italy-cookie-choices-admin.php on line 1390

**Comment by overclokk** [comment]
@Daneel87 sostituisci `continue;` con `return;` e dimmi se risolvi.

**Comment by Daneel87** [comment]
risolto

**Comment by Lob516** [comment]
Same fault found in editablefields.module:
PHP Fatal error:  'continue' not in the 'loop' or 'switch' context in ./sites/all/modules/editablefields/editablefields.module on line 186.
Simple solution replacing 'continue' by 'return'. 
Who can implement this solution in the Drupal-sourcecode ?

**Comment by overclokk** [comment]
Hi @Lob516 
I don't know drupal but you can try here https://www.drupal.org/contribute/development
