### ISSUE TITLE
validazione sito

### ISSUE THREAD

**Issue by laurace** [overclokk/italy-cookie-choices#150]
Provando a validare i contenuti del sito su https://validator.w3.org/, gli unici problemi riscontrati sono riconducibili al plugin:

![image](https://cloud.githubusercontent.com/assets/16215835/11672502/6fd554e8-9e11-11e5-8cdb-b0d22bc88aa8.png)
in che modo è possibile risolvere il problema?

Grazie

**Comment by overclokk** [comment]
Ciao @laurace purtroppo seguendo quel **consiglio** (quindi inserendo `scoped` nel tag style) si rompe lo stile del banner, purtroppo non hanno aggiornato le linee guida sulle nuove tecniche di performance che prevedono appunto di inserire stile inline.
Volendo si può escludere il bot del w3c ad analizzare la pagina con il banner, anche perché non ha senso.

**Comment by overclokk** [comment]
Chiudo questa issue perché ne era già stata aperta una -> #96  per qualunque cosa continuiamo di la.
