### ISSUE TITLE
Facebook page plugin non si blocca

### ISSUE THREAD

**Issue by Nuzzina** [overclokk/italy-cookie-choices#151]
Ho un problema con il plugin di facebook https://developers.facebook.com/docs/plugins/page-plugin. L'ho inserito nel mio sito a mano, senza l'utilizzo di plugin di wordpress (in sostanza ho copiato il codice che mi fornisce facebook e l'ho inserito in un widget TESTO). Il problema è che cookie choices non me lo blocca. Ho provato anche a inserire il codice dello script in Script da bloccare>custom, ma non serve a niente. Qualcuno può darmi una mano a risolvere?
Grazie

**Comment by overclokk** [comment]
Ciao @Nuzzina 
vorrei sapere l'attuale configurazione del plugin

**Comment by Nuzzina** [comment]
Ciao Enea,

alla fine spostando lo script in un’altra posizione del body ho ottenuto un risultato: bloccare il caricamento del plugin e far sì che si visualizzi solo il nome della pagina linkato alla stessa. Il che mi basta :)

Ad ogni modo la configurazione del plugin è: Blocco dei cookie di terze parti (Beta): Cookie da tutti gli embed nella tua pagina, eccetto head e footer (Beta) – anche perché le altre 2 opzioni non funzionano. Non ho inserito altri script da bloccare.

Grazie comunque per l’assistenza! Il tuo plugin è una mano santa per sta benedetta cookie law!

Nuzzina

Da: Enea [mailto:notifications@github.com] 
Inviato: lunedì 4 gennaio 2016 18.33
A: ItalyCookieChoices/italy-cookie-choices
Cc: Nuzzina
Oggetto: Re: [italy-cookie-choices] Facebook page plugin non si blocca (#151)

Ciao @Nuzzina https://github.com/Nuzzina  
vorrei sapere l'attuale configurazione del plugin

**Comment by overclokk** [comment]
Ottimo, allora segno come risolto :-)
