### ISSUE TITLE
Ceceppa multilingua - Bug

### ISSUE THREAD

**Issue by david-chiappetta** [overclokk/italy-cookie-choices#152]
Ciao, 
ho installato il plugin Italy Cookie choices, molto bello e fatto bene, purtroppo non funziona correttamente con il plugin multi-lingua Ceceppa 
Infatti come da img allegata si nota che sul banner appare la scritta "Banner anchor textBanner button text" e stessa cosa capita sui contenuti bloccati.
Potete aiutarmi?
Grazie
David

Versione WP:: 4.4
MySQL Versione: 5.1.73
PHP Versione: 5.3.3
Gravity Forms   1.9.13  
All In One WP Security  4.0.3
Ceceppa Multilingua 1.5.13
Easy FancyBox   1.5.7
Horizontal scrolling announcement   8.3
Image Widget    4.2.1
Italy Cookie Choices (for EU Cookie Law)    2.4.2
WPBakery Visual Composer    4.9.1  
Really Simple CAPTCHA   1.8.0.1
UpdraftPlus - Backup/Restore    2.10.3.1  
Yoast SEO   3.0.7

<img width="1039" alt="schermata 2016-01-03 alle 20 03 47" src="https://cloud.githubusercontent.com/assets/11176942/12080282/44f7f786-b256-11e5-9136-6b2dc8864988.png">

**Comment by overclokk** [comment]
Ciao @david-chiappetta 
ho appena caricato sul repo il fix per questo problema, ora le stringhe funzionano correttamente, aggiorna il plugin e fai nuovamente il salvataggio delle impostazioni, dopo troverai le nuove stringhe da tradurre in "Le mie traduzioni".
Se ne era parlato anche qui #124
