### ISSUE TITLE
Undefined index: HTTP_ACCEPT

### ISSUE THREAD

**Issue by deshack** [overclokk/italy-cookie-choices#155]
Utilizzando wp-cli dopo l'aggiornamento di WP dalla versione 4.3.1 alla 4.4.1 mi compare questo notice:

```
PHP Notice:  Undefined index: HTTP_ACCEPT in /var/www/wp-content/plugins/italy-cookie-choices/classes/class-italy-cookie-choices-front-end.php on line 267
```

**Comment by overclokk** [comment]
Prova questa `( isset( $_SERVER['HTTP_ACCEPT'] ) && strpos( $_SERVER['HTTP_ACCEPT'],'html' ) !== false )`

**Comment by deshack** [comment]
@overclokk appena posso ti faccio una PR ;)

**Comment by overclokk** [comment]
@deshack Ottimo :-)
