### ISSUE TITLE
problemi con Safari

### ISSUE THREAD

**Issue by Nuzzina** [overclokk/italy-cookie-choices#159]
Ciao, sto usando il plugin su questo sito www.shoujo-love-blog.net, ma quando cerco di aprire il sito da Safari o Edge, se il plugin è attivo, mi si carica solo una pagina bianca. A cosa può essere dovuto? Come posso risolvere?
Grazie

**Comment by Nuzzina** [comment]
Nessuno è in grado di aiutarmi? È un problema piuttosto grave :( Da ulteriori test che ho fatto, sembra che la causa sia l'opzione "Cookie da tutti gli embed nella tua pagina, eccetto head e footer (Beta)", infatti se è spuntata mi carica una pagina bianca, se tolgo la spunta il sito viene caricato normalmente, però ovviamente vengono visualizzati elementi che invece andrebbero bloccati (come i banner adsense). Ho anche provato a disattivare gli altri plugin e a cambiare tema, ma il problema rimane. E per la cronaca, ho l'ultima versione di Wordpress: 4.4.2.

**Comment by overclokk** [comment]
Ciao @Nuzzina 
prova queste soluzioni e dimmi se risolvi: https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work

**Comment by Nuzzina** [comment]
Provato tutto, ma non è servito a niente. Col debug però mi ha dato questo errore:

_Notice: ob_end_flush(): failed to send buffer of zlib output compression (0) in /home/hnomtwqy/public_html/wp-includes/functions.php on line 3464_

Ovviamente questo errore lo vedo solo da Firefox, da Safari e Edge continuo a vedere solo la pagina bianca. Ti riassumo tutte le caratteristiche del sito:

PHP 5.4.x
Wordpress 4.4.2
Plugin attivi: seo yoast
sito normale

e come dicevo, se deflaggo l'opzione "Cookie da tutti gli embed nella tua pagina, eccetto head e footer (Beta)" funziona tutto

**Comment by overclokk** [comment]
Non è un problema da poco, dovresti fare questa prova, disabilitare il modulo zlib e abilitare il modulo mod_deflate, visto che è una procedura non semplice e che si fa sul server puoi chiedere direttamente al tuo hosting che ci pensino loro, se questa procedura non ha alcun effetto allora l'unico modo è usare le altre due opzioni di blocco.

Ad ogni modo se vuoi approfondire l'argomento qui avevo scritto due articoli:

## zlib

http://www.overclokk.net/abilitare-compressione-gzip-senza-modulo-apache-mod_gzip-attivato.html

## mod_deflate

http://www.overclokk.net/abilitare-la-compressione-gzip-deflate-wordpress-htaccess.html

**Comment by Nuzzina** [comment]
Grazie per l’aiuto, allora contatto il mio hosting e chiedo a loro. Poi ti farò sapere.

Da: Enea [mailto:notifications@github.com] 
Inviato: lunedì 15 febbraio 2016 10.29
A: ItalyCookieChoices/italy-cookie-choices
Cc: Nuzzina
Oggetto: Re: [italy-cookie-choices] problemi con Safari (#159)

Non è un problema da poco, dovresti fare questa prova, disabilitare il modulo zlib e abilitare il modulo mod_deflate, visto che è una procedura non semplice e che si fa sul server puoi chiedere direttamente al tuo hosting che ci pensino loro, se questa procedura non ha alcun effetto allora l'unico modo è usare le altre due opzioni di blocco.

Ad ogni modo se vuoi approfondire l'argomento qui avevo scritto due articoli:

zlib

http://www.overclokk.net/abilitare-compressione-gzip-senza-modulo-apache-mod_gzip-attivato.html

mod_deflate

http://www.overclokk.net/abilitare-la-compressione-gzip-deflate-wordpress-htaccess.html

**Comment by overclokk** [comment]
Si, perfetto :-)

**Comment by Nuzzina** [comment]
L’assistenza dell’host ha provveduto ad apportare le modifiche che mi hai suggerito, e ora funziona tutto perfettamente. Grazie mille per l’aiuto!

Da: Enea [mailto:notifications@github.com] 
Inviato: lunedì 15 febbraio 2016 11.18
A: ItalyCookieChoices/italy-cookie-choices
Cc: Nuzzina
Oggetto: Re: [italy-cookie-choices] problemi con Safari (#159)

Si, perfetto :-)

**Comment by overclokk** [comment]
Perfetto :-)
