### ISSUE TITLE
Possibilità di aggiungere una classe al link della policy

### ISSUE THREAD

**Issue by maupet** [overclokk/italy-cookie-choices#16]
Sarebbe utile poter aggiungere una classe al link che porta alla policy, in modo da poter utilizzare ad esempio in combinazione con "easy fancybox".

**Comment by overclokk** [comment]
Sicuramente lo inserirò in una prossima release, prima devo fare un aggiornamento per fixare il bug #15

**Comment by acardinale** [comment]
In attesa dell'aggiunta (non so se è stata fatta) ed utilizzi jquery puoi individuare l'elemento in questo modo:
$('#cookieChoiceInfo').find('a').not('#cookieChoiceDismiss')

**Comment by overclokk** [comment]
Non è ancora stato aggiunto, prima meglio scorporare il css dai 3 files :-P

**Comment by overclokk** [comment]
Funzionalità aggiunta con la versione 2.2.0
