### ISSUE TITLE
Banner desktop in modalità mobile

### ISSUE THREAD

**Issue by ghost** [overclokk/italy-cookie-choices#162]
Buongiorno, ho riscontrato un problema nella visualizzazione mobile, il banner non risulta responsive.

Ho fatto dei test con tutti i tipi di visualizzazione sia in footer che header e banner.

Grazie mille per l'assistenza

**Comment by ghost** [comment]
Trovato il problema, non è compatibile con layerslider

**Comment by overclokk** [comment]
Grazie della segnalazione @lupett
