### ISSUE TITLE
Problema Traduzione WPML

### ISSUE THREAD

**Issue by fionda85** [overclokk/italy-cookie-choices#169]
Ciao,

io ho provveduto a tradurre in inglese tramite string translation del pacchetto WPML il messaggio popup che appare appena si entra nel sito, il tasto ok e maggiori informazioni (e le relative pagine di destinazione)... Quando però visito il sito in inglese, il messaggio e tutto il resto continua ad essere visualizzato in italiano.

Puoi fornirmi supporto?
Le stringhe sono correttamente tradotte.

**Comment by fionda85** [comment]
Risolto, grazie mille!

**Comment by overclokk** [comment]
Ciao @fionda85 
potresti condividere come hai risolto il problema? Potrebbe essere utile anche ad altri, grazie.

**Comment by fionda85** [comment]
Certo.. Il punto è che bisogna impostare dalla dashboard del plugin tutt le frasi in inglese e poi, importandolo tramite string translation, inserire la traduzione in italiano.

Se invece si inseriscono dal plugin tutte le specifiche in lingua italiana, quando si va a tradurre in inglese con strting translation, non funziona.

Tutto qui :)

**Comment by overclokk** [comment]
Grazie per aver condiviso come hai risolto, non l'ho aggiunto alla wiki poiché questa parte è indicata nella documentazione di [WPML](https://wpml.org/it/faq/utilizzare-string-translation-con-una-lingua-predefinita-diversa-dallinglese/) ma visto che può essere utile aggiungo i colegamenti.
Ciao
