### ISSUE TITLE
Siti ibridi (WP + HTML)

### ISSUE THREAD

**Issue by fedemarkez** [overclokk/italy-cookie-choices#17]
Nell'eventualità che un sito web abbia sia pagine basate su Wordpress, sia pagine indipendenti in html o php (scollegate da WP) c'è un modo per far funzionare lo script anche sulle pagine in html? Magari integrando un codice a parte

**Comment by overclokk** [comment]
Bella domanda, vedo come si può risolvere il problema.

Nello specifico le pagine in HTML come sono gestite? Semplici file modificati a mano?

**Comment by fedemarkez** [comment]
Nel mio caso sono semplici pagine html scritte da me con estensione PHP. Nella root ho wordpress mentre in alcune sotto-cartelle ci sono le vecchie pagine del sito.

**Comment by overclokk** [comment]
Quindi direi semplice da gestire, in questo caso potresti copiare lo snippet che genera il plugin e metterlo nel footer prima della chiusura di body.

**Comment by fedemarkez** [comment]
Ho provato a copiare lo snippet e funziona alla grande! Grazie :)

**Comment by overclokk** [comment]
Ottimo, allora chiudo come risolto :-)

Aggiungo anche questo trick nella documentazione
