### ISSUE TITLE
Script Formilla

### ISSUE THREAD

**Issue by cassy79** [overclokk/italy-cookie-choices#172]
E'stato fatto davvero un ottimo lavoro con questo plugin. Lo sto usando molto. Complimenti.
Ho solo un problema nel bloccare lo script di formilla. Provo a inserirlo nel campo "script da bloccare" ma non viene bloccato. http://www.formilla.com/wordpress-live-chat-plugin.aspx
Lo script è inserito prima nella head.
Grazie per l'attenzione

P.S. se uso l'opzione blocco cookie di terze parti "Cookie da tutti gli embed nella tua pagina, eccetto head e footer (Beta)", non viene caricato il css e il sito non viene mostrato nella maniera giusta. Sono costretta ad usare le prime due opzioni deprecate.

**Comment by overclokk** [comment]
Ciao @cassy79 e grazie dei complimenti, continuiamo la discussione sul forum di supporto qui https://wordpress.org/support/topic/script-formilla?replies=1
Chiudo questa discussione.
