### ISSUE TITLE
Problema con Firefox

### ISSUE THREAD

**Issue by alessandroime** [overclokk/italy-cookie-choices#182]
Ciao ragazzi, mi sono accorto di un problema che si verifica solo su Firefox. 
Fase 1) il plugin blocca correttamente tutti i cookie;
Fase 2) Dopo lo scroll o dopo aver premuto il pulsante chiudi, la pagina si aggiorna ma non vengono mostrati annunci adsense e gli script bloccati preventivamente non vengono sbloccati. Anche aggiornando manualmente la pagina il problema rimane. Il banner non compare ma il blocco cookie rimane attivato.
La console di Firefox segnala tra gli avvisi:
La risorsa “http://pagead2.googlesyndication.com/pagead/show_ads.js” è stata bloccata in quanto è attiva la protezione antitracciamento.

Mentre nella TAB errori non compare nulla.

Questo problema l'ho riscontrato su 3 siti diversi tutti su server diversi. WordPress 4.5.4 e Italy Cookie Choices  Versione 2.4.4.

Grazie

**Comment by alessandroime** [comment]
Ho provato anche su una installazione wordpress con tema Twenty Fourteen e solo Italy Cookie attivato. 
Wordpress versione 4.6.1, Plugin Italy Cookie Choices (for EU Cookie Law) Versione 2.4.4. 
Su Firefox il blocco cookie rimane attivato anche dopo aver cliccato su chiudi o dopo aver scrollato la pagina.

Ho provato anche senza queste opzioni ma non va comunque:
Aggiorna la pagina dopo l'accettazione (DEPRECATA)
Cookie da tutti gli embed nel tuo contenuto (Beta) (DEPRECATA)  
Cookie da tutti gli embed nei tuoi widget (Beta) (DEPRECATA)

Potete controllare per favore?
Grazie

**Comment by overclokk** [comment]
Ciao @alessandroime scusa il ritardo nella risposta ma mi ero perso questa issue, puoi mettere un link del sito con il plugin attivo?

**Comment by alessandroime** [comment]
Ciao @overclokk ho scoperto che il problema riscontrato non riguarda il plugin per il blocco cookie ma Firefox, che in modalità anonima, attiva la protezione antitracciamento:
https://support.mozilla.org/it/kb/antitracciamento-navigazione-anonima

Ti chiedo scusa se non ho aggiornato questa Issue
Grazie

**Comment by overclokk** [comment]
Ciao @alessandroime grazie per aver aggiornato la issue, chiudo come risolto.
