### ISSUE TITLE
Verifica blocco preventivo

### ISSUE THREAD

**Issue by gbarbagallo** [overclokk/italy-cookie-choices#184]
Salve ragazzi @overclokk @acardinale @andreapernici e complimenti per questo splendido plugin.
Ho seguito la guida e vorrei sapere se il tutto funziona correttamente.
Potreste verificare?

www.graficab.net
Vi ringrazio in anticipo.
Giuseppe

**Comment by overclokk** [comment]
Ciao @gbarbagallo grazie dei complimenti, ho guardato il sito e vedo il banner quindi per me è ok, se hai altri dubbi chiedi pure.
