### ISSUE TITLE
Fatal Error:  Il plugin non può essere attivato perché genera un errore fatale.

### ISSUE THREAD

**Issue by belliniphotoart** [overclokk/italy-cookie-choices#187]
Ciao,
appena ho fatto l'ultimo aggiornamento, mi si è bloccato il sito. ho dovuto rinominare la cartella del plugin dall'FTP.
una volta avuto nuovamente accesso, non riesco più a riattivarlo e l'errore è il seguente:

Warning: require(/xxx/xxxx/xxxxxx/xxxxx/wp-content/plugins/italy-cookie-choices/vendor/overclokk/minimum-requirements/minimum-requirements.php): failed to open stream: No such file or directory in /xx/xxxx/xxx/xxx/wp-content/plugins/italy-cookie-choices/bootstrap.php on line 13

Fatal error: require(): Failed opening required '/xxx/xxx/xxx/xxx/wp-content/plugins/italy-cookie-choices/vendor/overclokk/minimum-requirements/minimum-requirements.php' (include_path='.:/usr/local/php56/pear') in /xxxx/xxxxx/xxxx/xxxx/wp-content/plugins/italy-cookie-choices/bootstrap.php on line 13

ho cercato ma la cartella "vendor" non esiste, nè tantomeno i file citati all'interno.

Che posso fare?
Grazie mille in anticipo
Igor

**Comment by overclokk** [comment]
Ciao @belliniphotoart 
è strano perché la cartella è presente nel repository di WordPress https://plugins.svn.wordpress.org/italy-cookie-choices/tags/2.5.0/
Fai questa prova, cancella il plugin e prova a reinstallarlo dal tuo WordPress e dimmi se risolvi.

**Comment by belliniphotoart** [comment]
RISOLTO - Ti ringrazio Overclokk, in effetti ho fatto proprio così e ho risolto, inoltre da ftp avevo prima salvato la vecchia cartella, dopo la nuova installazione vi ho sovrascritto i file con la vecchia cartella e ho recuperato le personalizzazioni. quindi tutto ok. probabilmente per qualche strano motivo era stata cancellata la cartella "vendor"

**Comment by overclokk** [comment]
Ottimo che sia risolto.
Ad ogni modo le impostazioni sono salvate sul database non nella cartella del plugin.

Ciao.

**Comment by belliniphotoart** [comment]
Ecco perchè :-)

Scusa la mia scarsa conoscenza.

Comunque grazie di tutto e complimenti per l'ottimo plugin.

Ciao Igor

Il 21/11/2016 21:34, Enea ha scritto:
