### ISSUE TITLE
il banner non viene visualizzato

### ISSUE THREAD

**Issue by famarinu** [overclokk/italy-cookie-choices#189]
Salve, ho il seguente problema con il plugin.
Ho installato il plugin "Italy cookies choices" e all'inizio funzionava. Poi il patatrac!! 
Ho installato Yoast SEO e verificato le proprietà. Come hosting il sito appoggia su aruba. Ora il banner non viene piu visualizzato.
Se controllo la console mi da questo errore:
`
util.js:210 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keysSA.j @ util.js:210(anonymous function) @ js?ver=4.6.1:126(anonymous function) @ js?ver=4.6.1:46(anonymous function) @ js?ver=4.6.1:43(anonymous function) @ js?ver=4.6.1:46(anonymous function) @ js?ver=4.6.1:98(anonymous function) @ js?ver=4.6.1:43(anonymous function) @ js?ver=4.6.1:98(anonymous function) @ js?ver=4.6.1:43(anonymous function) @ js?ver=4.6.1:98(anonymous function) @ js?ver=4.6.1:43(anonymous function) @ js?ver=4.6.1:98hc @ js?ver=4.6.1:45gc.jb @ js?ver=4.6.1:98(anonymous function) @ common.js:1
js?ver=4.6.1:34 Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error_.jb @ js?ver=4.6.1:34(anonymous function) @ common.js:50(anonymous function) @ common.js:204c @ common.js:44(anonymous function) @ maps.googleapis.com/maps/api/js/AuthenticationService.Authenticate?1shttp%3…mcpandpartners.it%2F%23come-lavoriamo&callback=_xdc_._9s0l7s&token=20832:1`

Il plugin è settato bene perchè l'ho installato in un altro sito di prova e tutto funziona.
HO anche disattivato "Yoast SEO" ma continuo a non visualizzare il banner.
Cosa devo fare?
Grazie per l'aiuto!!!

**Comment by overclokk** [comment]
Ciao @famarinu fai come indicato nella wiki https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work e dimmi se risolvi.

**Comment by famarinu** [comment]
Ho risolto grazie.
Il problema era che non avevo verificato la proprietà nella Console Google.
Ora tutto sembra funzionare, ma se avrò problemi vi contatterò di nuovo.
Grazie

**Comment by overclokk** [comment]
Ottimo.
Chiudo come risolto
