### ISSUE TITLE
Accettazione con scroll

### ISSUE THREAD

**Issue by yoghi** [overclokk/italy-cookie-choices#19]
Siamo sicuri che sia lecito? è possibile introdurre questa cosa parametrica da pannello di config? 

Per spiegarmi se accedo alla pagina vedo la barra con il testo, scrollo e la barra scompare per non tornare mai più. Di fatto è una accettazione per il sistema ma io non ho mai cliccato "accetto"

**Comment by overclokk** [comment]
SI, sto implementando la possibilità di poter scegliere da admin se far accettare allo scroll o meno, dovrei riuscire nella prossima release.

**Comment by overclokk** [comment]
Aggiunto alla versione 1.2.0

Chiudo come risolto
