### ISSUE TITLE
Compatibilità con Wp Fastest Cache

### ISSUE THREAD

**Issue by Kurtafterjim** [overclokk/italy-cookie-choices#191]
Ciao,
ho applicato le modifiche suggerite qui http://www.wpfastestcache.com/tutorial/italy-cookies-choices-fix/ ma comunque il problema rimane. Il cookie banner non viene mostrato se una determinata pagina è cachata senza il banner.

**Comment by overclokk** [comment]
Ciao @Kurtafterjim 
il fix serve proprio per bypassare la cache, hai seguito tutti i passaggi? Puoi debuggure il codice e vedere dove hai problemi?

**Comment by Kurtafterjim** [comment]
Ciao @overclokk , ho risolto. La modifica allo script php dava problemi perchè l'editor non ha tenuto il carattere "a capo", e quindi tutta la riga risultava commentata...fail
Grazie lo stesso e scusa il disturbo

**Comment by overclokk** [comment]
Ok, perfetto, allora chiudo.
Ciao.
