### ISSUE TITLE
Plugin Instagram-feed

### ISSUE THREAD

**Issue by Filoz** [overclokk/italy-cookie-choices#192]
Ciao,
complimenti innanzi tutto per il tuo plugin... 

sto tentando, per ora invano, di bloccare il cookie rilasciato dalle api di instagram; il plugin che le interroga è questo: https://it.wordpress.org/plugins/instagram-feed/
ho tentato sia immettendo "instagram", che "instagram-feed" negli script da bloccare 
ho inoltre tentato una simil regex ma nulla comunque...

se invece attivo l'opzione "blocca tutti gli embed della pagina" allora quel plugin viene correttamente bloccato, purtroppo vengono bloccati anche tutti i css e quindi la pagina diventa inutilizzabile

**Comment by Filoz** [comment]
Ho appena prpovato ad abilitare le due funzionalità deprecated:
Cookie da tutti gli embed nel tuo contenuto (Beta) (DEPRECATA)	
 Cookie da tutti gli embed nei tuoi widget (Beta) (DEPRECATA)	

e... funziona tutto alla perfezione!
ha bloccato il plugin e ha lasciato i css...

posso chiederti come mai sono state deprecate quelle due opzioni?

**Comment by Filoz** [comment]
risolto!
grazie mille!

**Comment by overclokk** [comment]
Ciao @Filoz e grazie dei complimenti, sei stato più veloce di me, come hai risolto quindi?

Per quanto riguarda la domanda sul perché quelle due opzioni sono state deprecate è che con il sistema nuovo non erano più necessarie, sono state mantenute poiché alcuni potevano usare solo quelle.

**Comment by Filoz** [comment]
hem...la colpa era mia! :)
durante uno dei test ho lasciato che venisse bloccato "wp", ciò ha comportato che mi bloccasse tutti i css...  mea culpa!

Posso chiederti un chiarimento riguardo una wiki?
https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/Analytics-and-Cookie-Law
Dalle infografiche che avevo letto in passato...sembrava che fosse sufficiente utilizzare 
`ga('set', 'anonymizeip', true);` ... nella wiki pubblicata qui invece sembra che sia necessario una differente modifica...
qual'è il motivo?

**Comment by overclokk** [comment]
Si, è sufficiente quello, l'altro snippet è per il remarketing.
