### ISSUE TITLE
Google Analytics viene comunque attivato

### ISSUE THREAD

**Issue by sineverba** [overclokk/italy-cookie-choices#194]
Ciao a tutti,
uso su diversi wordpress questo fantastico plugin ma purtroppo noto che analytics viene comunque attivato, installando i 3 cookies _ga, _gat e _gid (anche se lo uso con la versione dell'anonimizzatore).

In dettaglio il codice di Analytics lo inserisco con il plugin "GA Google Analytics" di Jeff Starr.

Ho provato anche a inserirlo direttamente nella functions.php del tema (come da script trovato su un altro issues) ma non risolvo nulla.

Ho provato anche a disinstallare e reinstallare il tutto, ma essendo su multipli domini trovo difficile un problema su tutti.

Se ci sentiamo in privato, posso fornire anche il Json e/o l'indirizzo di uno dei siti internet..........

Grazie intanto, e buona giornata!

**Comment by overclokk** [comment]
Ciao @sineverba 
hai già seguito le indicazioni nella wiki https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/Analytics-and-Cookie-Law ?

**Comment by sineverba** [comment]
Ciao @overclokk ,
si, come scrivevo uso già la versione con l'anonymizer.

Inoltre ho provato anche a seguire quanto riportato qui: https://wordpress.org/support/topic/blocking-google-analytics-2/

E' per questo motivo che ti chiedevo se potevamo sentirci in privato, ti mandavo un link ad un sito ed il json...

Grazie intanto!

**Comment by overclokk** [comment]
Ciao @sineverba ho aggiunto nella wiki lo screenshot con la configurazione minima che ho usato per il sito http://demo.italystrap.it purtroppo bisogna fare un po' di prove per arrivare alla configurazione finale, quello che ti posso consigliare è che se hai il codice minificato nel sorgente è più semplice poi bloccarlo perché il sistema per fare il matching lo trova più facilmente (meno errori con il copia incolla).

Nella configurazione del mio sito io appendo lo snippet minificato a wp_footer, uso un mio plugin per fare questo ma tu puoi farlo semplicemente con una tua funzione php.

Puoi anche provare a copiare lo snippet che uso io (quello nel sorgente) cambiando l'UA code ovviamente.

**Comment by sineverba** [comment]
Ciao @overclokk . Alla fine ho "rinunciato" nel senso che anche con le tue impostazioni, il cookie veniva mostrata comunque. Alla fine ho scritto un plugin che prende in ingresso un javascript da mettere nel footer (l'analytics del caso), lo minimizza tutto su una riga e se è presente il tuo ` $_COOKIE['displayCookieConsent']  ` allora mostra l'analytics. Diciamo che quindi il mio plugin dipenderà strettamente dalla presenza del tuo.

Proverò nei prossimi giorni a pubblicarlo. MI consenti di mettere un link al tuo invitando (non so chi lo scaricherà il mio :D ) chi installa il mio a installare pure il tuo visto che serve come .... paracadute? :D

========================================================

Intanto ho pubblicato il plugin mio. avrei il piacere di mandarti i link in un pm perchè non voglio farti spam :)

Ho messo comunque il link al tuo plugin:

`This plugin add Google Analytics script in the footer, removing all spaces. Useful to use with [Italy Cookie Choices (for EU Cookie Law)](https://github.com/ItalyCookieChoices/italy-cookie-choices). If isset the Wp Italy Cookies "Display Cookie Consents", it prints the code, otherwise the Javascript code will NOT BE printed.`

**Comment by overclokk** [comment]
Ciao @sineverba 
se nel sorgente era stampato correttamente vuol dire che non era stato bloccato, quando uno script è bloccato viene inserito dentro un json nel sorgente ed eseguito nel momento dell'accettazione.

Nessun problema per il tuo plugin, fai pure ;-) e grazie per il link.

Ciao
