### ISSUE TITLE
FB e Instagram

### ISSUE THREAD

**Issue by kkri** [overclokk/italy-cookie-choices#196]
Ciao.
[Ho un sito](http://www.ilmetauro.it/v-home-2/) che ha una sidebar con un video, la Facebook box e una di Instagram. Il tuo plugin, settato su “Cookie da tutti gli embed nella tua pagina, eccetto head e footer”, blocca correttamente il video ma non FB e Instagram, ho anche un widget de “Il Meteo” che credo però non vada bloccato perché non vedo cookies generati. FB e Instagram li ho inseriti tramite appositi widgets del [tema Publisher](https://themeforest.net/item/publisher-magazine-blog-newspaper-and-review-wordpress-theme/15801051?s_rank=1). Ho provato tutte le impostazioni e inizialmente erano posizionati nel footer (come ancora puoi vedere [nella home “ufficiale”), ](http://www.ilmetauro.it/)poi ho provato a ricreare la pagina senza, ma inserendoli nella pagina richiamando la sidebar (Visual Composer, elemento Widgetised sidebar) sperando che me li bloccasse.Ho un Doubleclick che non so da dove venga perché c’è anche quando il video YT è ancora bloccato. Mi illumini? Grazie.
p.s. avevo posto lo stesso quesito anche nel supporto del plugin nella repository di Wordpress qualche giorno fa.

**Comment by overclokk** [comment]
Ciao @kkri la discussione sul forum mi è scappata, possiamo continuare li https://wordpress.org/support/topic/fb-e-instagram/
