### ISSUE TITLE
Informativa cookie displayCookieConsent

### ISSUE THREAD

**Issue by cassy679** [overclokk/italy-cookie-choices#197]
Buongiorno, per ogni cookie che elenco nella mia informativa, inserisco il link alla relativa policy.
Es. _GA ---> https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage

Per il cookie displayCookieConsent c'è un'informativa a cui linkare? Grazie

**Comment by overclokk** [comment]
Ciao @cassy679 
non c'è nessuna informativa perché è un cookie tecnico.
