### ISSUE TITLE
Traduzione text default option

### ISSUE THREAD

**Issue by widoz** [overclokk/italy-cookie-choices#2]
Non so se sbaglio ma il testo di default per le opzioni non è sotto funzione di traduzione.

'text' => 'Cookies help us deliver our services. By using our services, you agree to our use of cookies.' - linea 166

**Comment by overclokk** [comment]
Quello è un messaggio di default che non va bene su tutti i siti, stavo appunto pensando di cambiarlo con "Inserisci qui la tua informativa breve" e dare la possibilità di tradurre quello.

**Comment by widoz** [comment]
Ah, scusami in effetti localizzarlo tutto in ita ha piú senso.

**Comment by overclokk** [comment]
Non mi devi chiedere scusa, la tua domanda era più che legittima :-)
Chiudo come risolto.
