### ISSUE TITLE
Il plugin applica il banner soltanto alle pagine

### ISSUE THREAD

**Issue by smargarita** [overclokk/italy-cookie-choices#20]
Il plugin visualizza il banner soltanto nei Post e nella Home page.
Non viene visualizzato se si accede direttamente a Pagine, Ricerche, Categorie, Archivio, ...
Si riesce quindi a navigare in alcuni contenuti del sito senza mai vedere il banner.

**Comment by overclokk** [comment]
Ciao, ho appena provato e a me funziona correttamente, vedo il banner in tutte le pagine, per caso hai scrollato prima di cliccare sulle altre pagine?

**Comment by smargarita** [comment]
Ciao, non mi sembra di avere scrollato, forse mosso il mouse.
Ho provato su una macchina diversa con un browser diverso (Mac con Safari)
e effettivamente funziona.

Dopodomani potrò riprovare sul PC dove mi era capitato (Win7 con Firefox).

Il giorno 27 maggio 2015 12:28, Enea notifications@github.com ha scritto:

**Comment by overclokk** [comment]
Ok, fammi sapere

Ho aggiornato il plugin, ora l'evento scroll è solo su opzione

**Comment by smargarita** [comment]
Ho riprovato e effettivamente non capita più. Probabilmente avevo visto
male.

In compenso mi sembra (a questo punto, dico "sembra"!) di aver riscontrato
una stranezza (provato con Win7 e Firefox 38.0.1).

Se sono nella home page e clicco su OK presente nel banner, navigando in
altre pagine, non visualizza più il banner.

Se sono in una pagina diversa dalla home page e clicco su OK presente nel
banner, navigando in altre pagine, visualizza sempre il banner.

Per ricreare il problema:

1.

andare su http://ladefense.it

cliccare su Ok nel banner

cliccare sul link “arte” in alto

non visualizza più il banner

 Cancellare tutta la cronologia

 2.

andare su http://ladefense.it/glossario

cliccare su Ok nel banner

cliccare sul link “arte” in alto

visualizza di nuovo il banner

Ti risulta?

Sergio

2015-05-27 23:29 GMT+02:00 Enea notifications@github.com:

**Comment by overclokk** [comment]
Ho visto e sembra che nelle categorie non setti bene il path della root, devo fare ulteriori verifiche su altri siti.

**Comment by overclokk** [comment]
Ok, fixato con la nuova versione 1.2.2, aggiorna e dimmi se funziona tutto correttamente così posso chiudere come risolto.

**Comment by smargarita** [comment]
Nelle prove fatte funzioni correttamente.

2015-05-29 10:58 GMT+02:00 Enea notifications@github.com:

**Comment by overclokk** [comment]
Ottimo @smargarita , allora chiudo come risolto.

Grazie mille.
