### ISSUE TITLE
Non riesco a visualizzare l'avviso sul sito

### ISSUE THREAD

**Issue by stefanozambon** [overclokk/italy-cookie-choices#203]
Buongiorno,
tempo fa ho installato il plugin su https://prosecco-tour.com e funziona tutto correttamente.
Ora l'ho installato allo stesso modo su https://sanimarca.com ma invece non riesco a visualizzare nulla, come mai?
Grazie
Stefano

**Comment by stefanozambon** [comment]
ok ora funziona correttamente, grazie

**Comment by overclokk** [comment]
Ciao @stefanozambon 
perfetto, di cosa si trattava?

**Comment by stefanozambon** [comment]
Non si vedeva il popup dei cookies ma ora funziona.. forse bisognava aspettare un po.
Grazie
Stefano

⁣Sent from Mobile ®​

Il giorno 28 mar 2018, 10:11, alle ore 10:11, Enea <notifications@github.com> ha scritto:
