### ISSUE TITLE
Blocco cookie da tutti gli embed nel tuo contenuto e nei tuoi widget

### ISSUE THREAD

**Issue by jap003** [overclokk/italy-cookie-choices#205]
Buongiorno Enea,
innanzitutto grazie per il plugin, non mi blocca tutti i cookie ma si sta avvicinando più di tutti quelli provati in precedenza.
Sto provando a flaggare queste due funzionalità (quelle in oggetto) per bloccare il più possibile ma quando vado a salvare la configurazione del plugin non mi mantiene il flag, non salvando l’impostazione.
E’ per via del fatto che vengono indicate come in “beta”?
Ci sono in vista aggiornamenti che vadano a risolvere il problema in tempi utili?

**Comment by overclokk** [comment]
Ciao @jap003 continuiamo qui https://wordpress.org/support/topic/blocco-cookie-da-tutti-gli-embed-nel-tuo-contenuto-e-nei-tuoi-widget/
