### ISSUE TITLE
Posizione e colori del banner

### ISSUE THREAD

**Issue by ghost** [overclokk/italy-cookie-choices#210]
Nel mio sito le pagine sono state costruite con Elementor free.
Il plug-in Italy Cookie Choices, correttamente, inibisce lo scroll e l’accesso al menu della pagina sottostante se il banner è posizionato al centro (Dialog), il colore dello Sfondo è bianco, il Testo è colore #473727 e i bottoni piccoli. 
Invertendo i colori (Sfondo #473727 e Testo bianco), il banner continua ad essere correttamente mostrato. Lo Slug di colore azzurro si legge correttamente ma il Testo non è più visibile perché erroneamente assume il colore dello Sfondo.
Il plug-in, erroneamente, non inibisce lo scrool e l’accesso al menu della pagina sottostante se il banner è posizionato in alto (Top) o in basso (Botton), indipendentemente dai colori nel banner. Inoltre, nella posizione in alto (Top) il Testo è troppo in alto e i caratteri sono un po’ tagliati.
Vorrei posizionare il banner (Sfondo #473727 e Testo bianco) in basso purché lo scroll e l’accesso al menu della pagina sottostante siano inibiti finché non si Accetta il Testo del banner. Per ora utilizzo il plug-in con il banner in posizione Dialog, con i colori opportuni dove non ho riscontrato problemi. Grazie per la cortese risposta.

**Comment by overclokk** [comment]
Ciao @ghost 
Se selezioni dal menù a tendina "My custom CSS" puoi inserire il tuo stile personalizzato.
