### ISSUE TITLE
Popup con sfondo bianco e testo illeggibile

### ISSUE THREAD

**Issue by servizifotograficipordenone** [overclokk/italy-cookie-choices#22]
Salve. Ho appena installato il plugin su Wordpress 4.22. La finestra popup centrale appare bianca e il testo grigio chiaro e quindi illeggibile Allego screenshot. 
![screen_popup_bianco](https://cloud.githubusercontent.com/assets/12630191/7842308/96f63186-04a2-11e5-84d5-8c62e64281ce.jpg)
Grazie.

**Comment by overclokk** [comment]
Ciao, il problema è che il template imposta il colore #C7CFD1 su tutto il testo e quindi viene ereditato anche dal testo nel popup del plugin, in futuro ci sarà la possibilità di aggiungere colori personalizzati ma al momento è possibile solo inserendo una propria regola CSS nel foglio di stile:

```
#cookieChoiceInfo{
    color: #999;
}
```

Provala e dimmi se risolvi in questo modo.

**Comment by servizifotograficipordenone** [comment]
Non mi funziona. Non mi cambia il colore del testo della popup

**Comment by overclokk** [comment]
In che file l'hai messa?

**Comment by servizifotograficipordenone** [comment]
wordpress/wp-content/themes/pictorico/style.css

**Comment by overclokk** [comment]
Io vedo utilizzato solo questo file: http://www.servizi-fotografici-pordenone.it/fotografo/wp-content/themes/sfpn/style.css

**Comment by servizifotograficipordenone** [comment]
Scusami, sono rinco io! Avevo caricato il tuo stile nel css di un altro tema di quel sito. Funziona! Grazie :)

**Comment by overclokk** [comment]
Ottimo, perfetto, chiudo come risolto
