### ISSUE TITLE
Z-index

### ISSUE THREAD

**Issue by marcosiino** [overclokk/italy-cookie-choices#25]
Ciao, ho visto che in alcuni casi il tuo top banner appare dietro altri elementi in overlay. Per es. se sei loggato come amministratore, il banner dei cookie appare dietro la barra di amministrazione di wordpress. So che questo non ha importanza, ma potrebbe succedere che in qualche sito qualcuno ha degli elementi in overlay e questi appaiano sopra il banner.

La soluzione dovrebbe essere semplice (ho provato a modificare il css inline che hai messo nel tuo plugin) e basta aggiungere z-index con un valore molto alto, per es. z-index: 1000000 per risolvere.

Puoi upgradare il plugin con questo aggiornamento al CSS per favore ? 

Grazie!

**Comment by overclokk** [comment]
Ciao @marcosiino si, so che sta dietro la barra admin che comunque solo chi è loggato la vede (admin e altri ruoli) che comunque dovrebbe aver consentito i cookie, metterla sopra non ha senso perché non ha nessuna utilità come quella admin che invece ha i vari link per il pannello di controllo, visto che sto già sviluppando la parte relativa alla modifica dello stile valuterò se dare la possibilità di inserire un valore personalizzato.

**Comment by marcosiino** [comment]
Si lo so che per la barra Admin non ha senso, era x fare un esempio, ma
potrebbe succedere che su un sito ci sono altri banner overlay nel frontend
e in quel caso il banner dei cookie dovrebbe stare sopra di tutti, per
questo ti suggerivo questa cosa. Si se riesci a dare la possibilità di
mettere un valore personalizzato sarebbe ottimo.

Il giorno sab 30 mag 2015 16:43 Enea notifications@github.com ha scritto:

**Comment by overclokk** [comment]
Lo terrò in considerazione per una prossima release.
Grazie
Qui l'altra discussione #5

**Comment by Skyflash** [comment]
Mi aggiungo alla discussione perche', nel mio caso, lo z-index servirebbe e non poco :)
Oppure, gradirei la possibilità di spostare il banner a fondo pagina (visualizzata)

Sto usando in qualche sito il template Divi 2.0 di ET e, con le modifiche che ho fatto all'header, la topbar non viene visualizzata, cosi' ho dovuto ripiegare sull'overlay.

Se vuoi un link per testare sul mio sito, chiedi e ti sarà dato :)

Grazie ;)

**Comment by overclokk** [comment]
@Skyflash vedrò cosa posso fare :-)

Grazie

**Comment by overclokk** [comment]
Dalla versione 2.2.0 è possibile personalizzare tutto il CSS

**Comment by marcosiino** [comment]
Ottimo! La provo al piú presto. PS: non ho ancora provato il blocco
preventivo dei cookie, sai se funziona con adsense e i social
buttons/widgets ? Scusa se scrivo qui, ma sono sul cell e mi viene piú
comodo rispondere a questo post :)

Il giorno mer 24 giu 2015 22:25 Enea notifications@github.com ha scritto:

**Comment by overclokk** [comment]
Il blocco se ben impostato funziona su tutto.

**Comment by Skyflash** [comment]
Grazie. Appena posso, lo provo pure io :+1:

**Comment by overclokk** [comment]
:+1:
