### ISSUE TITLE
Possibilità di cambiare il colore del banner e del testo (e dei link possibilmente), e possibilità di aprire i link nella stessa pagina (senza target="_blank").

### ISSUE THREAD

**Issue by marcosiino** [overclokk/italy-cookie-choices#27]
Ciao, un'altra cosa che ti chiedo è se gentilmente puoi implementare queste possibilità nel tuo plugin. Le implementerei io, ma se lo faccio le modifiche verrebbero sovrascritte al tuo prossimo aggiornamento:
- Possibilità di impostare un colore di sfondo a scelta del banner e un colore per il testo (va bene anche un campo di testo dove scrivo il colore in hex, per es. #00ff00, non necessariamente con un colorpicker). Questo perché la normativa dice che il banner deve essere "disconnesso" dal resto del sito, nel senso che deve risultare ben visibile e quindi anche di colore diverso rispetto allo sfondo. Attualmente il banner è grigio chiaro, se ho un sito bianco o grigio chiaro si nota poco e potrebbero fare contestazioni...quindi non si sa mai :) meglio dare la possibilità di cambiare colore! :)
- Possibilità di impostare un colore anche per i link che appaiono sul banner. Come sopra, basta un semplice campo di testo dove mettere il colore in hex.
- Possibilità di scegliere se i link devono aprirsi in una nuova pagina o nella stessa pagina. Attualmente quando clicco sul link che dovrebbe portarmi all'informativa me lo apre in una nuova pagina (target="_blank"). Sarebbe meglio se potessi scegliere, io per es. vorrei aprirlo nella stessa pagina. Andrebbe benissimo un flag del tipo "Apri link su una nuova pagina SI/NO" e se l'utente sceglie si mette target="_blank" sul link, altrimenti no.

Grazie mille! :)

**Comment by overclokk** [comment]
Con la versione 1.2.3 ho aggiunto la possibilità di scegliere se aprire in una nuova finestra o meno

**Comment by marcosiino** [comment]
Grande!!! Grazie mille, se riusciresti a fare anche la possibilità di
cambiare colore di sfondo del banner, del testo e dei link ti faccio una
statua ehehe :) attualmente ho risolto mettendo un custom CSS con regola
!important per sovrascrivere il CSS scritto dal tuo plugin, ma siccome
dovrei implementare il plugin su un bel po di siti sarebbe più comodo se si
potesse scegliere il colore direttamente dal plugin :)

Il giorno dom 31 mag 2015 12:40 Enea notifications@github.com ha scritto:

**Comment by overclokk** [comment]
Si, certo, piano piano le aggiungo tutte :-)

**Comment by marcosiino** [comment]
grazie! :)

Il giorno dom 31 mag 2015 alle ore 15:04 Enea notifications@github.com ha
scritto:

**Comment by overclokk** [comment]
:-)

**Comment by yaku78** [comment]
Ciao.
Ho installato il tuo ottimo plugin (su wordpress 4.2.2).
C'è però un malfunzionamento sulla scelta di visualizzare il link per la policy cookies nella stessa pagina o in una pagina nuova.
Nonostante io scelga di visualizzarlo nella stessa pagina mi apre comunque una nuova pagina aggiungendo al link "%u200E" che poi diventa sulla nuova pagina "%E2%80%8E" trovando ovviamente una pagina inesistente. In ogni modo il link è errato anche se scelgo di visualizzarlo in una pagina nuova.
Sai come posso risolvere?
Ti ringrazio e complimenti per il tuo lavoro.

Gabriele.

**Comment by overclokk** [comment]
Ciao @yaku78 ho appena provato su diversi siti su cui lo utilizz e funziona correttamente, prova a fere questa prova:

disattiva tutti i plugin e prova
se ancora ti dovesse dare problemi attiva il tema standard e riprova

Dimmi com'è andata.

**Comment by yaku78** [comment]
Grazie per la tua pronta risposta.
Ho provato a disattivare e riattivare tutti i plugin e ricaricare il tema, ora funziona, ma solo al primo passaggio. 
Mi spiego: al primo accesso compare il banner e il link è corretto, se clicco sul link della privacy cookies mi apre una nuova pagina (nonostante abbia scelto di aprirlo sulla stessa pagina) compare sempre il banner e il link viene nuovamente modificato con il codice finale "%u200E".
Il tema in uso è "Kitchener", e l'ho testato su firefox, chrome e safari.
In realtà andrebbe bene anche così, dato che al primo accesso funziona, ed è quello che conta. Se però riusciamo a risolvere la questione della scelta di aprire il link sulla stessa pagina, e della modifica del link stesso, sarebbe perfetto.

**Comment by overclokk** [comment]
Ma disattivando tutti i plugin e attivando il tema standard il problema si presenta?

**Comment by yaku78** [comment]
Ho riprovato. Diattivato plugin, cambiato tema, niente...
Alla fine ho aggiornato la pagina relativa all'informativa sui cookies e tutto è andato a posto.
Mistero!
Comunque grazie per il tuo tempo e la tua pazienza.

**Comment by overclokk** [comment]
Quindi ora hai risolto? @yaku78

**Comment by yaku78** [comment]
Si, risolto e installato su diversi template.
Funziona perfettamente.

**Comment by overclokk** [comment]
Ottimo @yaku78 :-)

@marcosiino dalla versione 2.0 molte delle tue richieste sono state aggiunte, dimmi se così va bene.
