### ISSUE TITLE
Possibilità di ridurre la scadenza del cookie da un anno a un mese

### ISSUE THREAD

**Issue by giowile** [overclokk/italy-cookie-choices#29]
È possibile? E già che ci sono, c'è la possibilità di eliminare il cookie in maniera tale che non verrà salvata la presa visione del banner per accessi effettuati nei 30 giorni successivi al primo collegamento al sito? Grazie mille!

**Comment by overclokk** [comment]
Posso tenerla in considerazione, ma non ho capito la seconda domanda, potresti rispiegarmela?

**Comment by giowile** [comment]
Scusa, hai ragione. Ho esposto la questione in maniera maldestra.
In sostanza, chiedevo la possibilità (eventualmente da inserire come link all'interno dell'informativa estesa) di "resettare" il cookie in maniera tale che se viene effettuato nuovamente l'accesso ricompare il banner. Cioè, il cookie non tiene memoria (per un anno, come adesso) dell'accesso effettuato dallo stesso utente. In pratica, è quello che si può fare già manualmente adesso cancellando il cookie con i comandi del browser.

**Comment by overclokk** [comment]
Quindi vorresti che l'utente abbia la possibilità di poter "non accettare più" l'informativa eliminando la preferenza?

**Comment by giowile** [comment]
Forse sto dicendo/chiedendo una sciocchezza. Ma in sintesi, vorrei che succedesse questo:
1) mi collego al sito per la prima volta;
2) appare il banner che mi chiede se accettare i cookie o no;
3) che accetto o no, per un anno (tutte le volte che mi ricollego al sito in questione) il banner non appare più perché ha memorizzato la richiesta;

> > > a questo punto mi piacerebbe ci fosse la possibilità di fare dimenticare al cookie la mia scelta, in modo tale che la successiva volta che mi ricollego al sito il banner si ripropone (come se fosse la prima volta).
> > > Spero di essere stato più chiaro. Grazie per la pazienza ;)

**Comment by overclokk** [comment]
> 3) che accetto o no, per un anno (tutte le volte che mi ricollego al sito in questione) il banner non appare più perché ha memorizzato la richiesta;

Il banner verrà visualizzato finché non si accetta l'informativa.

Era questo che intendevi?

**Comment by giowile** [comment]
Perfetto! Ecco il passaggio che mi mancava.
Grazie ancora per l'infinita pazienza ;)

**Comment by overclokk** [comment]
Ottimo, allora ci siamo :-)
