### ISSUE TITLE
Simboli speciali

### ISSUE THREAD

**Issue by mmassarenti** [overclokk/italy-cookie-choices#3]
Provando ad inserire simboli come ' " & / nel campo Text to display non vengono ben convertiti sul front end.
Compaiono infatti in codice ASCII come ad esempio &#039; &amp; &quot;

**Comment by overclokk** [comment]
Grazie mille @mmassarenti per la segnalazione, vedo come risolvere il problema al più presto.

**Comment by overclokk** [comment]
@mmassarenti con la versione 1.1.0 dovrebbe essere risolto il problema, se mi puoi dare conferma, grazie.

**Comment by mmassarenti** [comment]
Perfetto direi che è risolto!
Grazie!

Un altro suggerimento: sarebbe utile poter cambiare i colori del testo, di sfondo e dare la possibilità di sostituire il semplice link "Close" con un tasto più elegante ;-)

**Comment by overclokk** [comment]
Ottimo :-)

Per quanto riguarda la personalizzazione degli elementi sarà disponibile nelle prossime versioni.

Chiudo come risolto.
