### ISSUE TITLE
Non visualizzo il banner

### ISSUE THREAD

**Issue by coriweb** [overclokk/italy-cookie-choices#30]
Non visualizzo il banner nella top bar e nemmeno con il pop up.
Ho configurato tutto come da guida.
Ecco il sito: http://www.betaplanet.it/
Grazie.

**Comment by overclokk** [comment]
Ciao, in questa situazione devi fare queste prove:

Disattiva tutti i plugin e riprova
Se ancora non funziona attiva il tema standard e riprova

A volte ci può essere qualche conflitto o con plugin o con il tema ma bisogna fare dei test per capire cosa sia.

**Comment by overclokk** [comment]
Ciao @coriweb hai poi risolto?

**Comment by lucapreziati** [comment]
Ciao, 
anch'io ho il medesimo problema.
Ti posso già confermare che è il tema. Ho provato a vedere se trovavo il codice html che dovrebbe essere aggiunto all'interno della pagina, ma non ho trovato niente.
Hai qualche indicazione da darmi? Credo possa essere il tema utilizzato che è ha qualche porcata. Posso provave a cablare direttamente nel footer della pagina l'attivazione del plugin?

**Comment by overclokk** [comment]
Ciao @lucapreziati prova a seguire questi passaggi e dimmi se risolvi https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work

**Comment by lucapreziati** [comment]
Ciao, 
confermo la mancanza della chiamata da parte del tema della funzione wp_footer();
Me lo sono perso proprio nel leggere, mi ha attratto il fatto che mettessi wordpress in DEBUG e mi sono perso la chiamata wp_footer.
Per quel che riguarda il mio tema, Amplify, ho aggiunto per l'appunto la seguente stringa prima della chiusura del tag html <body>

Esempio della modifica

<?php wp_footer(); ?>

</body>
</html>

Grazie mille

**Comment by overclokk** [comment]
Ottimo, perfetto :+1:
