### ISSUE TITLE
Banner top in piu lingue per sito multilingua

### ISSUE THREAD

**Issue by matty81** [overclokk/italy-cookie-choices#31]
Ciao, prima di tutto COMPLIMENTI!!! ho appena testato il plugin e debbo dire ottimo, veloce e di facilissima installazione. Ti faccio però una domanda magari banale. Ho un sito multilingua con la scelta lingue sul top tramite semplice linguetta. Se accedo trovo il banner in italiano. E' possibile far apparire il banner in inglese ecc.. quando cambio la linguetta delle lingue. Per la traduzione uso wpml. Grazie mille

**Comment by overclokk** [comment]
Ciao @matty81 grazie dei complimenti :-)

Non ci avevo ancora pensato, valuto una eventuale integrazione, il problema in questo caso è che non essendo gestito da WordPress il multilingua ma da plugin (e neanche uno solo) vedo se può essere fattibile.

Grazie mille :-)

**Comment by dagostoni** [comment]
Ciao @matty81,
anche io ho lo stesso problema.

Questa sotto è una soluzione temporanea e non molto elegante ma chi ha bisogno del supporto multilingua può forzare le traduzioni direttamente nel codice del plugin. Occhio agli aggiornamenti che vanno a cancellare la forzatura.

Nell'esempio specifico utilizzo Polylang. Spero possa essere d'aiuto almeno fino a quando non ci sarà il supporto direttamente nel plugin.

https://gist.github.com/dagostoni/e5a070df23aa996d85fb

**Comment by overclokk** [comment]
Grazie @dagostoni per il tuo contributo, lo studierò appena possibile in modo di poterlo adattare anche ad altri plugin.

**Comment by overclokk** [comment]
Con la versione 2.2.0 sono supportati i plugin WPML, Ceceppa e Polylang

**Comment by eli-mar** [comment]
Ottimo, ma... in WPML dove inserisco le traduzioni?

**Comment by overclokk** [comment]
@elisa-studioand devi usare l'estensione aggiuntiva per la traduzione delle stringhe.

**Comment by eli-mar** [comment]
Ecco perchè non vedevo l'opzione, al momento abbiamo la versione Multilingual Blog, valuteremo se fare l'upgrade, grazie!

**Comment by overclokk** [comment]
Purtroppo per garantire una compatibilità maggiore quello è l'unico modo.
