### ISSUE TITLE
Possibilità di incorporare codice

### ISSUE THREAD

**Issue by mattiafrigeri** [overclokk/italy-cookie-choices#32]
Ciao, IUBENDA (versione free) mi impone che il link alla policy nel banner sia un "tasto embed", e non un semplice link. È possibile aggiungere questa funzionalità?

Grazie

**Comment by overclokk** [comment]
Ciao @mattiafrigeri la posso valutare per una prossima release.

Grazie

**Comment by mattiafrigeri** [comment]
Grazie

**Comment by overclokk** [comment]
Aggiunto con la versione 2.3.0
