### ISSUE TITLE
In caso di disintallazione plugin

### ISSUE THREAD

**Issue by mattiafrigeri** [overclokk/italy-cookie-choices#34]
In caso di disintallazione, ci pensa il plugin a "ripulire" tutto in autonomia, o il database va pulito manualmente? E in questo caso, quali tabelle vanno eliminate?

Grazie mille.

**Comment by overclokk** [comment]
Ciao @mattiafrigeri al momento non è ancora presente quella funzionalità ma è comunque in lista delle cose da fare.

**Comment by mattiafrigeri** [comment]
Grazie, mi diresti quindi l'elenco corretto delle tabelle che devo andare a cancellare manualmente in modo da lasciare il database "pulito"?

**Comment by overclokk** [comment]
Si, me lo avevi anche chiesto nel messaggio prima :-)
la tabella è wp_options e l'opzione da cancellare è italy_cookie_choices

**Comment by mattiafrigeri** [comment]
Grazie

**Comment by mattiafrigeri** [comment]
Scusa, pensavo non te ne fossi accorto, infatti non avevi risposto.
Grazie della pazienza.

**Comment by overclokk** [comment]
Lo avevo letto ma poi nel rispondere anche ad altri messaggi mi sono dimenticato :-P

**Comment by overclokk** [comment]
Aggiunto con la versione 2.2.0
