### ISSUE TITLE
Mettere il messaggio in fondo alla pagina

### ISSUE THREAD

**Issue by lvaghi** [overclokk/italy-cookie-choices#35]
Manca un' opzione per mettere il messaggio in fondo alla pagina... se un domani gli stili non saranno più inline il problema si risolverà da solo... comunque un' opzione bottom anzichè top sarebbe carina.

In ogni caso molte grazie per questa utile extension!!!

**Comment by overclokk** [comment]
Ciao @lvaghi è una funzionalità in sviluppo, spero nelle prossime release di poterla implementare.

**Comment by overclokk** [comment]
Ciao @lvaghi questa funzione è stata aggiunta con la versione 2.1.0

**Comment by lvaghi** [comment]
Grazie mille!

Leo
