### ISSUE TITLE
Supporto versioni precedenti di Wordpress

### ISSUE THREAD

**Issue by riccarbi** [overclokk/italy-cookie-choices#36]
Ciao
ho provato ad installare il plugin ma, essendo la mia versione di WP la 3.7, come mi aspettavo non visualizza il banner (anche se si fa installare).
Per ora non vorrei aggiornare WP (troppi plugin mi darebbero problemi), ma questo plug-in mi pare sia l'unico in giro a fare tutto quello che davvero serve. 
Pensi per caso di rilasciare una versione compatibile con le versioni precedenti alla 4.1 di WP?
Se in caso invece l'adattamento lo dovessi fare io, mi potresti dare qualche dritta sulle parti di codice php incompatibili con le versioni dalla 3.7 alla 4.1? Se fattibile, l'adattamento lo farei più che volentieri. 
Ciao, Riccardo

**Comment by overclokk** [comment]
Ciao, purtroppo per questioni di sicurezza devo mantenere una compatibilità minima dalla 4.1, nel caso usassi versioni precedenti di WordPress quello che puoi fare è generare lo snippet di codice su una installazione anche in locale, copiarlo e inserirlo a mano nel tuo tema prima della chiusura di </body>, però così dovrai copiare lo snippet ad ogni aggiornamento del plugin.

**Comment by riccarbi** [comment]
Grazie overclokk!
Ok, provo a fare così.

**Comment by overclokk** [comment]
Perfetto :-)
