### ISSUE TITLE
Informazioni cookie

### ISSUE THREAD

**Issue by solofferte** [overclokk/italy-cookie-choices#37]
Salve ho installato nel mio sito www.solofferte.com il vostro plugin vorrei una verifica se tutto ok 
grazie

**Comment by overclokk** [comment]
Ciao @solofferte puoi verificare direttamente tu che il cookie venga generato correttamente utilizzando gli strumenti per sviluppatore presenti nel browser, ad ogni modo se chiudendo l'informativa breve non viene più mostrata allora il cookie è installato correttamente.
