### ISSUE TITLE
Possibilità di accettare informativa cliccando su u n link

### ISSUE THREAD

**Issue by thinkaboutit** [overclokk/italy-cookie-choices#39]
Ciao Enea,

complimenti per il tuo lavoro.
Chiedo se è possibile fare in modo che l'informativa sia accettata anche cliccando un qualunque link al di sotto del banner.

Grazie
Ciao
Federico

**Comment by overclokk** [comment]
Ciao @thinkaboutit  grazie mille :-)

E' una funzionalità in fase di sviluppo.

Ciao

**Comment by overclokk** [comment]
@thinkaboutit dalla versione 2.1.0 è possibile attivare l'opzione per l'accettazione se l'utente continua la navigazione, quindi cliccando i link interni del sito.

**Comment by thinkaboutit** [comment]
grazie!

2015-06-08 15:25 GMT+02:00 Enea notifications@github.com:
