### ISSUE TITLE
banner che si riapre

### ISSUE THREAD

**Issue by viviana2015** [overclokk/italy-cookie-choices#40]
Ciao e bravi.
Ho un problema: quando si cambia pagina ricompare nuovamente il banner, nonostante si sia cliccato su "chiudi", quindi durante la navigazione continua a ricaricarsi. E' una cosa risolvibile? In modo che uno, entrando nel sito, clicchi "Chiudi" (ossia acconsente) e poi la finestra scompare.
Grazie

**Comment by overclokk** [comment]
Ciao @viviana2015 il banner ovviamente non deve essere ripresentato se l'informativa è accettata, hai verificato che il cookie venga creato regolarmente?

**Comment by viviana2015** [comment]
No, non sono in grado di fare questa verifica...sentirò un programmatore...grazie

**Comment by overclokk** [comment]
E' facile, te lo spiego, dimmi prima che browser usi.

**Comment by viviana2015** [comment]
io uso chrome, ma ho riscontrato lo stesso problema con explorer. Oltretutto la banda dell'avviso mi copre del tutto il menu principale...un disastro insomma :)

**Comment by overclokk** [comment]
Con crome se premi ctrl + maiusc + i accedi alla consolle per sviluppatori, nella tab resource a sinistra clicca so cookie e quindi sul tuo sito, il cookie impostato dal plugin si chiama displayCookieConsent (a meno che tu non gli abbia cambiato nome).

In questa versione c'è la possibilità di aggiungere un bordo di 36px, nella prossima l'altezza sarà automatica.

**Comment by andreapernici** [comment]
Ricordiamoci che l'obiettivo della barra è che ci clicchino per non vederla più per un anno...quindi per come la vedo io deve dare fastidio all'utente per acquisire il consenso.

**Comment by overclokk** [comment]
Ciao @viviana2015 hai poi risolto?
