### ISSUE TITLE
Layout corrotto con versione 2

### ISSUE THREAD

**Issue by dharmann** [overclokk/italy-cookie-choices#41]
Sto usando il plugin dalla versione 1.2. L'ho configurato e lo sto usando insieme a qtranslateX.
In seguito all'aggiornamento alla versione 2.0, il layout precedente è completamente corrotto. Inoltre le stringhe che prima funzionavano in modalità multilingua adesso non funzionano più e tutto viene scritto in ogni lingua che supporto.
P.es.: anziché scrivere "Accetto" oppure "Accept", a seconda della lingua, viene stampata la stringa "[:it]Accetto[:en]Accept[:]"

Ho dovuto ripristinare la vecchia versione 1.2.3.

**Comment by overclokk** [comment]
Ciao @dharmann 
per capire cosa sia successo dovrei vedere il problema, almeno uno screenshot.

Per la seconda parte in teoria non è cambiato nulla a livello di input dei testi comunque verifico al più presto con qtranslateX (che non uso ma che è interessante quella funzionalità).

Duplicato: https://wordpress.org/support/topic/layout-corrotto-con-versione-2

**Comment by dharmann** [comment]
Sì, cert...scusa il cross.

**Comment by dharmann** [comment]
Ok...ti allego due screenshot: prima/dopo l'aggiornamento
![v1 2 3](https://cloud.githubusercontent.com/assets/6182373/8007293/15d172f0-0b9b-11e5-8854-2465138d5bf3.png)
![v2 0 0](https://cloud.githubusercontent.com/assets/6182373/8007294/15d33e00-0b9b-11e5-8898-a314fa0ab69b.png)

**Comment by alealeb** [comment]
ciao, invece a me genera questo errore la versione 2:
Il plugin non può essere attivato perché genera un errore fatale.
Parse error: syntax error, unexpected T_FUNCTION in /web/htdocs/www.protezionecivilevarazze.it/home/1/wp-content/plugins/italy-cookie-choices/italy-cookie-choices.php on line 1093

Ho attivo il tema Zerif Lite con wordpress versione 4.2.2–it_IT

**Comment by overclokk** [comment]
@dharmann Nella versione 2.0 hai la possibilità di impostare un colore per il background e per il testo, dimmi se così risolvi.
Per Il plugin multilingua dici questo? https://wordpress.org/plugins/qtranslate/

@alealeb c'è già una issue aperta continuiamo di la #42

**Comment by dharmann** [comment]
No, quello è il plugin originario che ha poi dato vita ad un progetto più strutturato e mantenuto, con una piccola comunità dietro: https://wordpress.org/plugins/qtranslate-x
Molto più evoluto e stabile.

**Comment by overclokk** [comment]
@dharmann ok, perfetto, provo quello e vedo cosa sia successo
Grazie

**Comment by fmonts** [comment]
Stesso problema, come si può ritornare al layout precedente (quello del Google Cookie Choices)? Così non va assolutamente bene, il background trasparente rende il testo illeggibile e i tasti sono troppo grandi...

**Comment by overclokk** [comment]
@fmonts il colore del background lo puoi cambiare dal pannello del plugin, nel prossime versioni ci sarà la possibilità di poter scegliere o creare una propria grafica.

**Comment by fmonts** [comment]
Sì ho visto, però secondo me occupa troppo spazio, va a coprire il logo che quasi sempre è in quella posizione (soprattutto nelle versioni mobili), se la gente non vede il brand non sa su che sito si trova e se ne va...

**Comment by fmonts** [comment]
L'ho messo in basso sostituendo semplicemente il top: 0 con bottom: 0, potresti aggiungere questa opzione

**Comment by overclokk** [comment]
@fmonts nella prossima release abbiamo ripristinato anche il template originale con l'aggiunta dell'opzione per la bottom bar

**Comment by yaku78** [comment]
Anche a me da lo stesso problema, in attesa di miglioramenti ho reinstallato la versione 1.2.3

**Comment by andreapernici** [comment]
Non dovrebbe corrompersi nulla. Basta impostare il colore di sfondo e del testo dalle impostazioni.

**Comment by yaku78** [comment]
In ogni caso sarebbe perfetto avere la possibilità di accedere comodamente al css oppure direttamente dalle impostazioni del plugin per modificarne l'aspetto (e non solo i colori di sfondo). Rispetto alla versione 1.2.3 la nuova versione è troppo ingombrante, e sta su due linee (c'è un "hr" di mezzo). La versione precedente era molto più discreta, le scritte erano in minuscolo, stava tutto su una riga e non c'era nessun bottone, ma solo i link.

**Comment by andreapernici** [comment]
Nella nuova versione ci sarà la possibilità di selezionare tra vari template.

Stiamo lavorando inoltre anche alla possibilità di custom css...un po' di pazienza che facciamo tutto ;)

**Comment by yaku78** [comment]
Piena fiducia! State facendo un ottimo lavoro...

**Comment by acardinale** [comment]
@overclokk @andreapernici nella versione PHP che sto sviluppando sto facendo in modo che se il banner è in posizione "top" automaticamente mette sposta il body sotto il banner (in pratica inserisco un margin-top). E' qualcosa che avevate fatto e poi è stata rimossa o non è ancora implementata?

**Comment by overclokk** [comment]
@acardinale si, l'ho fatto in js, aggiunto una classe al tag HTML e la tolgo all'accettazione

**Comment by acardinale** [comment]
@dharmann nella prossima release si potrà impostare l'opzione AutoMarginTop. In questo modo il banner non copre l'header

**Comment by overclokk** [comment]
@dharmann potresti dirmi se con la versione 2.2.0 (quella nuova) il problema è risolto?

**Comment by yaku78** [comment]
@overclokk ho ancora qualche problemino coi css. L'opzione di default (centered with text link) non rimane centrata, ma allineata a sinistra, e il css personalizzato che aggiungo nell'apposito specchietto non sovrascrive quello "inline".
Vedi immagine:
![cookie](https://cloud.githubusercontent.com/assets/12694352/8359896/9009b0e0-1b69-11e5-83b9-f04a9bdc2a2b.png)

**Comment by overclokk** [comment]
@yaku78 il testo centrato mi sono dimenticato io di metterlo :-)
Per poter usare il css custom devi selezionarlo anche dalla select box, e sotto agli altri tre template

**Comment by yaku78** [comment]
Ok. Perfetto!
Ora posso perfezionare il mio style!
Grazie. Ottimo lavoro.

**Comment by overclokk** [comment]
Perfetto :-)
