### ISSUE TITLE
Il plugin non può essere attivato perché genera un errore fatale.

### ISSUE THREAD

**Issue by mikelinos** [overclokk/italy-cookie-choices#42]
Ho installato il plugin su wp 4.2.2 e non riesco ad attivarlo.
Esce questo:
Parse error: syntax error, unexpected T_FUNCTION in /web/htdocs/www.michelebindi.it/home/wp-content/plugins/italy-cookie-choices/italy-cookie-choices.php on line 1093
Come mai? Per precisione dico che sto' usando il programma ProPhoto per impostare il mio sito WP....
grazie..

**Comment by overclokk** [comment]
Ciao @mikelinos che versione di PHP hai sul server?

**Comment by Drake92** [comment]
Anche io ho lo stesso problema ed ho la versione 5.2.14 (worldpress)

**Comment by overclokk** [comment]
@Drake92 Ilplugin è compatibile da PHP 5.3 in poi, non supporta le versioni precedenti, nella description è scritto, comunque svilupperò un check così visualizza un messaggio durante l'attivazione se c'è compatibilità o meno.

**Comment by Drake92** [comment]
Ok, grazie mille per la risposta :+1:

**Comment by mikelinos** [comment]
Non conosco la versione PHP... ho provato a creare un php ma con textedit non riesco...come faccio a vederla?

**Comment by litionstudio** [comment]
Salve, dopo aver installato la versione 2.0 anche io ho un errore simile, utilizzando wordpress 4.2.2 e PHP 5.3.29:
Fatal error: Using $this when not in object context in /web/htdocs/www.falconarabasket.it/home/wp-content/plugins/italy-cookie-choices/italy-cookie-choices.php on line 1103

Mentre su un altro sito (stessa versione wordpress e PHP) in cui ho installato il plugin, non mi esce nessun errore, ma non compare neanche il box informativo, nemmeno dopo aver cancellato i cookies, o aprendolo da altri browser.

Grazie in anticipo! :)

**Comment by litionstudio** [comment]
UPDATE: facendo qualche prova ho scoperto che entrambi i problemi che ho riportato qui sopra erano causati attivando l'opzione "Cookie di terze parti nei widget (Beta)". Spegnendo questa opzione il banner viene visualizzato e non mi compaiono errori.

Spero sia una informazione utile per aggiustare il problema! ;)

**Comment by overclokk** [comment]
@mikelinos 
<?php phpversion(); ?>

Ciao @litionstudio rettifico con la versione 5.4.4 nessun problema, invece come succede a te con la versione 5.3.29 c'è quel problema, quindi cambio la versione minima alla 5.4, chiedo scusa per il mio errore nello scrivere la versione.

Sviluppo un check per il controllo di versione prima dell'installazione.

**Comment by garmellino** [comment]
come posso avere la versione precedente prima dell'aggiornamento. Ho PHP 5.2.6 la versione precedente funzionava.
grazie

**Comment by overclokk** [comment]
@garmellino ovviamnte ti consiglio di aggiornare subito il PHP perché la 5.2.6 ha diversi problemi di sicurezza, comunque se vuoi una versione precedente le ho caricate tutte qui https://github.com/ItalyCookieChoices/italy-cookie-choices/releases

**Comment by garmellino** [comment]
grazie

**Comment by mikelinos** [comment]
@overclokk ma con mac come creo il php da mettere poi sul server.... scusa non sono ferrato in questa materia! ;-)

**Comment by overclokk** [comment]
@mikelinos puoi semplicemente creare un file di testo con estensione .php con qualsiasi editor di testo puro (non word e company), per esempio su windows c'è il classico notepad, lo chiami per esempio info.php e dentro ci metti la riga che ho scritto sopra, metti il file nella root e da browser digitila url del tuo sito più il nome del file come fosse una pagina interne, es www.miosito.tld/info.php

**Comment by mikelinos** [comment]
@overclokk non ho windows...solo mac!

**Comment by overclokk** [comment]
@mikelinos MAC non ha un editor di testo semplice?
Da pannello del tuo hosting non puoi vedere la versione di PHP?

**Comment by mikelinos** [comment]
@overclokk si ha TextEdit ma non slava in php....
Ho Aruba, vado a vedere nel pannello di controllo..

**Comment by overclokk** [comment]
@mikelinos i file di testo si possono rinominare anche dopo averli salvati cambiando l'estensione.
Dal pannello di aruba fai prima :-)

**Comment by litionstudio** [comment]
@overclokk perfetto grazie, ho aggiornato a PHP 5.6.9 e adesso nessun problema! :+1:

**Comment by mikelinos** [comment]
@overclokk avevo gia' provato a rinominare campiando estensione ma mi modifica il testo cosi':
\rtf1\ansi\ansicpg1252\cocoartf1347\cocoasubrtf570
{\fonttbl\f0\froman\fcharset0 Times-Roman;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720

\f0\fs24 \cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 <?php phpversion(); ?>}

**Comment by mikelinos** [comment]
@overclokk comunque sono entrato nel pannello di controllo di Aruba: ver. 5.3.29

**Comment by floryn90** [comment]
@mikelinos prova a installarti sul mac sublime text 3 (gratis per uso privato) e quello ti permette di fare tutto quello che vuoi tu

**Comment by overclokk** [comment]
@litionstudio ottimo, perfetto :-)
@mikelinos quella versione non va bene, aggiorna il PHP almeno ad una 5.4 o superiore.

**Comment by mikelinos** [comment]
@overclokk ok! ma tanto ci siamo come faccio ad aggiornare il PHP? :-)

**Comment by mikelinos** [comment]
@overclokk .....trovato dal pannello di controllo: posso scegliere varie versioni, la cui ultima e' la 5.6.9
puo' andar bene? aggiornando posso creare danni al sito??

**Comment by mikelinos** [comment]
aruba consiglia la 5.3.29......
ecco la schermata della scelta PHP:
5.6.9        PHP5.6.x Nuova versione della serie 5.6.x che comprende nuove caratteristiche.
5.5.25       PHP5.5.x Nuova versione della serie 5.x che comprende nuove caratteristiche.
5.4.41       PHP5.4.x Nuova versione della serie 5.x che comprende nuove caratteristiche.
5.3.29       PHP5.3.x La versione attuale e maggiormente supportata. Caldamente consigliata.
5.2.17       PHP5.2.x La versione non è più supportato da PHP.net. Si consiglia di utilizzare la versione 5.3.x

**Comment by overclokk** [comment]
@mikelinos aruba non è un hosting serio ;-) comunque ti consiglio almeno la 5.4.41

**Comment by mikelinos** [comment]
@overclokk e lo so'....ma per ora questo ho!!! :-(
cosa mi consigli tu??

**Comment by mikelinos** [comment]
@overclokk e comunque puo' creare problemi a mio sito e blog cambiare versione di PHP?

**Comment by mikelinos** [comment]
@floryn90 grazie!! ;-)

**Comment by overclokk** [comment]
@mikelinos se fai un avanzamento non hai problemi, i problemi li hai quando torni indietro :-)

**Comment by mikelinos** [comment]
@overclokk ok grazie! ;-)

**Comment by mikelinos** [comment]
@overclokk solo per curiosita'... ho fatto il file info.php e caricato, apro la pagina del sito ma compare una pagina bianca.. ??

**Comment by overclokk** [comment]
@mikelinos se il file è vuoto è normale.

**Comment by acardinale** [comment]
@mikelinos @Drake92 @litionstudio @garmellino la prossima release sarà funzionante anche con PHP < 5.3

**Comment by overclokk** [comment]
Confermata compatibilità con PHP < 5.3 dalla versione 2.1.0
