### ISSUE TITLE
Banner informativo non visualizzato

### ISSUE THREAD

**Issue by gaianorm** [overclokk/italy-cookie-choices#43]
Ho appena installato la versione 2.0 non appare il banner, anche dopo aver pulito la cache di wp-supercache  e browser cache+cookies
Problema già riscontrato nella versione precedente. Problema analogo con cookies law info, risolto spostando il banner nel footer del template.

**Comment by overclokk** [comment]
Ciao @gaianorm da quello che mi dici sembra che nella tua pagina sia presente un elemento con z-index superiore a 9999, mi confermi questo?

Hai provato la dialog?

**Comment by gaianorm** [comment]
Ciao @overclokk , intanto di linko il sito www.luxemozione.com (mi ero scordato).
Se dai un occhio ora ho settato su Dialog, ma a me non compare nulla... ho provato anche a disattivare il wp supercache ma  non cambia. Sullo z index francamente non saprei il template è acquistato su themeforest,

**Comment by gaianorm** [comment]
ho controllato il discorso dello z-index: 9999 cercando con F12 nei CSS ci sono un paio di righe con z-index: 99999...

**Comment by litionstudio** [comment]
Ciao @gaianorm , anche a me non veniva visualizzato in nessun modo il banner, e facendo qualche prova ho notato che spegnendo l'opzione "Cookie di terze parti nei widget (Beta)" il banner poi compariva correttamente. Forse è un piccolo bug da correggere ;)

**Comment by overclokk** [comment]
@gaianorm dovresti fare queste prove:
disattiva tutti i plugin e prova a vedere se si visualizza
se non si visualizza attiva anche il tema standard e riprova

Secondo me è più probabile un problema con qualche plugin (forse quelli di cache)

Ciao @litionstudio il tuo problema molto probabilmente è causato da una versione di PHP precedente alla 5.4, se fai aggiornare il PHP dal tuo hosting sicuramente risolvi.

**Comment by gaianorm** [comment]
ciao @overclokk allora operazioni che ho eseguito:
1)disattivato wp supercache pulito cache manualmente >dopo aver pulito anche cache chrome+cookies > banner visibile (con accettazione con scrolling disattivata)
2)Riattivato wpsupercache > restart di chrome pulito > banner visibile (con accettazione con scrolling disattivata)
3)Attivato autoscrolling >pulito cache di wpsc> banner non visibile
4)disattivato autoscrolling> pulito cache> banner visibile
Questo è quanto...un conflitto con wpsupercache l'avevo notato anche con un altro plugin di weepie che bloccava i cookies ga gat di analytics solo al primo avvio a cache WPSC pulita. Poi continuava a caricare anche a cookies e cache browser ripuliti.
Ciao
G.

**Comment by overclokk** [comment]
@gaianorm immaginavo ci fosse un problema di cache, nella prossima release dovrebbe essere risolto

**Comment by gaianorm** [comment]
Installata versione 2.1
Le seguenti opzioni attivate singolarmente:
Accetta l'informativa sull'evento scroll del mouse >spuntata  Avvio a nuovo del browser non appare il banner
Attiva l'accettzazione se l'utente continua la navigazione >spuntata Appare il banner, a cambio pagina scompare, ma riavviando a cache e cookie browser puliti non riappare è Necessaria pulizia cache di WPSC
Ho un altro problema ma lo inserisco in un altro ticket.
ciao e grazie
G.

**Comment by gaianorm** [comment]
Aggiorno ... ho seguito le indicazioni suggerite da @acardinale  da inserire .htaccess per wp super cache. 
Il banner appare e funziona su autoscroll..

**Comment by acardinale** [comment]
:+1:

**Comment by gaianorm** [comment]
Però con la spunta su  Attiva l'accettzazione se l'utente continua la navigazione  il cookie rimane li, cancello ricarico ed è ancora li....poco importa tolgo la spunta.
 (a proposito manca una (A) in accettazione) 
Grazie per il supporto!

**Comment by acardinale** [comment]
@gaianorm attenzione! Se fai F5 o refreshi è come se continui la navigazione (già sei nella pagina).
O chiudi la finestra/scheda e la riapri, oppure vai nella barra degli indirizzi e dai invio.
