### ISSUE TITLE
Attivare i cookie per tutti i script

### ISSUE THREAD

**Issue by floryn90** [overclokk/italy-cookie-choices#44]
Possibilità di attivare i cookie per tutti i script e non solo a quello che è stato cliccato.

P.s. se vuoi vedo di darti una mano con lo sviluppo del plug-in.

**Comment by andreapernici** [comment]
Dovrebbe già essere così.

**Comment by floryn90** [comment]
Io l'ho provato sul mio blog e quando ho accettato i cookie si è attivato solo lo script dove ho accettato i cookie
Il 05/giu/2015 21:02, Andrea notifications@github.com ha scritto:Dovrebbe già essere così.

**Comment by floryn90** [comment]
Ho ricontrollato e di default fa sparire la barra dei cookie ma non attiva i cookie dei widget dove per esempio ho la pubblicità.
Questo è il link del blog: www.floryn90.it
Il 05/giu/2015 21:02, Andrea notifications@github.com ha scritto:Dovrebbe già essere così.

**Comment by andreapernici** [comment]
Io invece vedo l'inverso. 

La barra non appare mai, ma cliccando sul bottone che rimpiazza Adsense fa comparire il banner adsense.

**Comment by overclokk** [comment]
Forse ho capito, se clicchi solo sulla topbar rimangono i box nella sidebar giusto?
Se fosse così dalla prossima versione è risolto il problema.

**Comment by floryn90** [comment]
Si Enea, la topbar si chiude anche facendo il semplice scroll ma rimangono i box nella sidebar. Ho controllato i cookie e facendo il scroll viene impostato il cookie con y ma i box se ne fregano di quella impostazione e si attivano solo se clicco sui box

**Comment by overclokk** [comment]
@floryn90 ok, allora ho capito bene, dalla prossima release il problema è risolto :-)

**Comment by overclokk** [comment]
@floryn90 dimmi se con la 2.1.0 hai risolto.

**Comment by floryn90** [comment]
Sisi, sembra che adesso funzioni bene!

Il 08/06/2015 15:31, Enea ha scritto:

**Comment by overclokk** [comment]
Ottimo :-)
