### ISSUE TITLE
errore jquery su admin Wordpress

### ISSUE THREAD

**Issue by papaboys** [overclokk/italy-cookie-choices#46]
La Versione 2.0.0 mi crea problemi sulla dashboard di Wordpress
si tratta penso di qualche conflitto con il jquery, infatti caricando immagini o inserendo tag, la schermata resta bloccata (non sono funzioni del plugin, ma il plugin interferisce con queste funzioni) disattivando il plugin il pannello di amministrazione riprende subito a funzionare.

L'errore della console è: Uncaught TypeError: $ is not a function

(il tipico errore di conflitto tra versioni jquery differenti...)

grazie e complimenti per il plugin, le versioni precedenti sono davvero molto buone, qui credo sia solo un bug da correggere...

**Comment by overclokk** [comment]
Ciao @papaboys prova ad inserire nel tuo wp_config `define('CONCATENATE_SCRIPTS', false);` prima di `/* Finito, interrompere le modifiche! Buon blogging. */` e dimmi se risolvi.

**Comment by papaboys** [comment]
grazie, purtroppo non basta, avevo già fatto questa prova che ho trovato online. Per caso il plugin ricarica una versione di Jquery? forse inserendo jquery.noconflict si potrebbe risolvere a livello di plugin... 
grazie!

**Comment by overclokk** [comment]
Su una installazione in locale dava anche a me questo problema che però non si presentava su altri siti online, in locale avevo risolto nel modo consigliato, ad ogni modo `jQuery.noConflict()` è già presente nel JS e l'unica dipendenza del file è `'wp-color-picker'` , se hai la possibilità prova a fare questa prova, apri il file `italy-cookie-choices.php` cerca il metodo `enqueue_color_picker` e decommenta  jquery solo nella funzione  `wp_enqueue_script` dove viene incluso il file js per l'admin (non quella precedente dove c'è solo jquery), e dimmi se così risolvi qualcosa o se hai altri errori.

**Comment by papaboys** [comment]
...fatto, ma purtroppo mi da ancora errore...
![senzanome](https://cloud.githubusercontent.com/assets/12768104/8024387/d13a9f70-0d31-11e5-9124-dd0ad1bee2e6.png)

**Comment by overclokk** [comment]
Si, quello è l'errore che dava a me in locale ma non sui siti in produzione, comunque lo segno come bug e appena possibile vedo come risolvere.

**Comment by acardinale** [comment]
@papaboys forse il blocco blocca (scusa il gioco di parole) lo script jquery

**Comment by overclokk** [comment]
@acardinale ma nel BE non viene eseguito il blocco

**Comment by acardinale** [comment]
@overclokk ops...  mi ero concentrato sulla console :)

**Comment by overclokk** [comment]
@acardinale :-)
