### ISSUE TITLE
Plugin non funzionante - Fatal error: Using $... 

### ISSUE THREAD

**Issue by Slimcrazy87** [overclokk/italy-cookie-choices#49]
Ciao,
ho provato ad utilizzare il vostro plugin sul mio sito web ma purtroppo non funziona quando attivo le due funzioni di blocco.
Dopo l'attivazione il footer, le slide e le progress bar non si visualizzano più. Se può tornare utile ho attivato la funzionalità define( 'WP_DEBUG', true ); e mi fornisce il seguente errore (naturalmente il dominio è oscurato - se volete vi invio tutto in privato)

Fatal error: Using $this when not in object context in /var/www/vhosts/xxx.it/httpdocs/xxx/wp-content/plugins/italy-cookie-choices/italy-cookie-choices.php on line 1103

Inoltre in futuro inserirete la possibilità di bloccare gli script (tipo Analytics) tramite  o shortcodes?

Spero di riuscire a trovare una soluzione perchè il plugin sembra davvero ben strutturato. Buon lavoro

**Comment by overclokk** [comment]
Ciao @Slimcrazy87 il problema dell'errore è discusso qui #42 

Per la seconda richiesta ci stiamo lavorando e direi la prossima release sarà disponibile.

**Comment by Slimcrazy87** [comment]
Ciao Enea,
grazie per la celere e cortese risposta.
Ho letto la discussione, io ho WP versione 4.2.2 e php 5.3.29.
Purtroppo non posso aggiornarla da linuxboard e quindi niente plugin! :(

Vabè grazie comunque

**Comment by overclokk** [comment]
Chiedi al tuo hosting.
