### ISSUE TITLE
Typo in una stringa

### ISSUE THREAD

**Issue by aldolat** [overclokk/italy-cookie-choices#51]
Correggere la frase "Advanced settngs" in "Advanced settings" nella pagina delle opzioni.

**Comment by floryn90** [comment]
Fixed!

**Comment by aldolat** [comment]
Ottimo, chiudo. :+1:

**Comment by aldolat** [comment]
It seems the issue is not fixed. Reopening it...

**Comment by floryn90** [comment]
È stato corretto ed ho fatto anche il pull request delle modifiche. Puoi consultare la modifica da te interessata qui: https://github.com/floryn90/italy-cookie-choices/blob/romanina-translations/lang/italy-cookie-choices.pot alla riga 83

**Comment by overclokk** [comment]
Risolto con la versione 2.1.0
