### ISSUE TITLE
pur senza cookie non vedo banner

### ISSUE THREAD

**Issue by claudinski** [overclokk/italy-cookie-choices#54]
Ciao! Intanto grazie! Sono molto contento di aver trovato una soluzione italiana. Ho appena installato ma non vedo il banner! Ho provato a cercare il cookie per rimuoverlo ma non l'ho?

Come posso fare?

**Comment by andreapernici** [comment]
Hai compilato tutte le impostazioni?

**Comment by claudinski** [comment]
Il 06/06/2015 20:46, Andrea ha scritto:

> Hai compilato tutte le impostazioni?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ItalyCookieChoices/italy-cookie-choices/issues/54#issuecomment-109633446.
> 
> Grazie Andrea!

Credo di sì ma non essendo uno smanettone ti allego le schermate della 
pagina impostazioni.

Claudio

**Comment by andreapernici** [comment]
Non vedo l'allegato

**Comment by claudinski** [comment]
Il 06/06/2015 21:43, Andrea ha scritto:

**Comment by andreapernici** [comment]
Continuo a non vedere l'allegato.

**Comment by claudinski** [comment]
Il 07/06/2015 13:11, Andrea ha scritto:

> Continuo a non vedere l'allegato.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ItalyCookieChoices/italy-cookie-choices/issues/54#issuecomment-109738205.
> 
> ti allego i file pdf. se non li vedessi mi puoi specificare in che 
> formato li preferiresti?

Grazie

Claudio

**Comment by acardinale** [comment]
@claudinski alleghi il file via mail? In questo modo non vengono allegati automaticamente su github.
Nella email clicca su **"view it on GitHub"** e poi lo alleghi nel commento.

**Comment by claudinski** [comment]
Ho cancellato gli allegati! Funziona ora senza problemi! Grazie per l'assistenza!

**Comment by andreapernici** [comment]
Devi spuntare l'opzione "Visualizza il banner nel frontend"

**Comment by overclokk** [comment]
Chiudo come risolto.
