### ISSUE TITLE
banner visibile solo da mobile

### ISSUE THREAD

**Issue by uroboroprogetti** [overclokk/italy-cookie-choices#55]
ciao, il mio banner su www.san-italia.it è visibile solo da mobile (ho testato con Iphone 4S IOS7), mentre risulta invisibile su Chrome/Safari/Firefox, ho provato a disattivare le funzioni in beta e anche l'accettazione con scroll, ho provato a disattivare WP Super Cache..ma niente da fare :(

**Comment by andreapernici** [comment]
Questo è un problema di Cookiechoices di Google che non funziona se il sito utilizza cose in jquery che agiscono su alcuni eventi.

Bisognerà fare un'opzione che fa usare un Cookiechoice in jquery per ovviare il problema.

**Comment by overclokk** [comment]
Vorrei vedere un link con il plugin attivo però.

**Comment by uroboroprogetti** [comment]
Grazie mille ad entrambi, 

ma non avendo capito dalla vostra precedente risposta come potevo risolvere il problema ho momentaneamente disattivato il plugin e ne sto utilizzando un altro; 
vi ricontatterò quando potrò mostrarvi direttamente il vostro plugin installato.

Buona domenica e complimenti per il lavoro che state facendo,
katia

**Comment by overclokk** [comment]
@uroboroprogetti presto verrà rilasciata la nuova release, se avrai la possibilità di testarla a farci sapere se il problema è risolto sarebbe fantastico :-)

**Comment by uroboroprogetti** [comment]
Grazie, resto in attesa e appena disponibile l’aggiornamento lo provo senz’altro!
buona giornata
k

**Comment by uroboroprogetti** [comment]
ho reinstallato il plugin e lo sto testando, adesso il banner è visibile ed i contenuti sembrano bloccati anche su fisso, quando però dò l'accettazione i cookie vengono accettati "permanentemente" cioè il banner non appare più neanche se cancello cache e cookies.
Mi sono detta che forse può dipendere dal valore predefinito "y" dato ai cookie (..è la durata, se ho ben capito) ma la cosa strana è che i cookie sembrano accettati non solo sul browser con cui ho fatto la prima visita ma anche sugli altri "puliti"...
questa cosa oltretutto mi impedisce di verificare se effettivamente i contenuti da bloccare sono bloccati ovunque anche nelle altre pagine, l'unico modo che ho per controllare è visitare una pagina per volta previa disinstallazione e reinstallazione del plugin..quale può essere il problema?
grazie

**Comment by andreapernici** [comment]
Usi un plugin di cache?

**Comment by uroboroprogetti** [comment]
sì, WP Super cache :(

**Comment by uroboroprogetti** [comment]
...e adesso il banner è invisibile anche dagli altri terminali (notebook e smartphone)

**Comment by andreapernici** [comment]
Hai letto la documentazione su Wp Super Cache nel wiki?
https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/Compatibilit%C3%A0-W3TC-fix

**Comment by uroboroprogetti** [comment]
no, scusami, la vedo solo adesso!
faccio le modifiche e poi ri-testo il tutto, grazie ancora
p.s. ti segnalo un'altra cosa strana, analizzando la pagina non visualizzo il cookie del plugin, neanche quando funziona :O

**Comment by acardinale** [comment]
Attenzione sempre alla storia dell'F5 ;)

**Comment by andreapernici** [comment]
Da dove li controlli i cookie?

**Comment by uroboroprogetti** [comment]
li controllo in diversi modi, se ho aperto Chrome clicco sull'icona accanto all'url, oppure su Firefox li leggo prima di cancellarli attraverso il pannello preferenze > privacy >rimuovere i singoli cookie.
P.S. cos'è la storia dell'F5?

**Comment by uroboroprogetti** [comment]
ho bisogno di un altro chiarimento, perché nel wiki si fa riferimento a diversi plugin di cache:
la prima modifica che suggerite di apportare ad . htaccess, cioè 

Aggiungere

RewriteCond %{HTTP_COOKIE} displayCookieConsent [NC]

# BEGIN W3TC Page Cache core

<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase /
    (etc etc)

va apportata anche per WP Super Cache?..facendola quindi seguire alla specifica modifica in advanced-cache.php? e poi controllando anche di nuovo .htaccess per apportare l'aggiunta in caso di Mod rewrite??

a me la cosa non è chiarissima perché non ho grandi competenze tecniche ed ho paura di fare dei grossi danni :)

**Comment by uroboroprogetti** [comment]
(certo che no, scusate!..si fa riferimento al nome dell'altro plugin!)
..però la guida è un po' incasinata, o forse sono io che non ci posso arrivare ;)

**Comment by acardinale** [comment]
@uroboroprogetti ho sistemato un po la guida.

Ti isolo la parte che ti interessa:

Per WP SUper Cache

se si utilizza 
**Utilizza PHP per servire i file in cache.**
aggiungere in advanced-cache.php (in principio)

```
if ( !isset( $_COOKIE['displayCookieConsent'] ) ){
    return;
}
```

**Verificare ugualmente che non vi sia lo snippet di WPSuperCache nel file .htaccess**

Se si utilizza
**Utilizza mod_rewrite per servire i file in cache. (Raccomandato)**

aggiungere nell'.htaccess
prima della riga

```
RewriteCond %{HTTP:Cookie} !^.*(comment_author_|wordpress_logged_in|wp-postpass_).*$
```

la riga

```
RewriteCond %{HTTP:Cookie} displayCookieConsent [NC]
```

P.S.:
vi fornisco anche anche un'altra possibilita (alternativa alla modifica in advancedd-cache.php)
nel wp-config.php
**sostituire la riga

```
define('WP_CACHE', true);
```

**con**

```
if ( !isset( $_COOKIE['displayCookieConsent'] ) ){
    /** Disable Cache */
    define('WP_CACHE', false); // Added by ItalyCookieChoices
} else {
    /** Enable W3 Total Cache */
    define('WP_CACHE', true); // Added by W3 Super Cache
}
```

**Comment by uroboroprogetti** [comment]
...comunque niente da fare, ho modificato .htaccess, niente banner, niente cookie.
Forse è bene che io faccia pulizia e provi a cancellare del tutto e reinstallare il plugin?

**Comment by acardinale** [comment]
@uroboroprogetti prova a disabilitare "Accettazione tramite navigazione"

**Comment by uroboroprogetti** [comment]
adesso ci sono 2 cookie "wordpress_test_cookie"..ma niente banner, niente blocco

**Comment by uroboroprogetti** [comment]
P.S. lo snippet di WPSuperCache c'è perché ho usato il mod rewrite
P.S. 2..ma la modifica in advanced cache (o in WP config) non va fatta solo per il plugin W3 Total Cache??

**Comment by acardinale** [comment]
@uroboroprogetti nel commento precedente ti ho estrapolato esclusivamente le istruzioni per WP Super Cache

**Comment by uroboroprogetti** [comment]
Grazie ancora;
devo dire che la necessità di dover apportare modifiche alle impostazioni del plugin di cache per far funzionare il vostro m'ha messa un po' in confusione, com'è evidente da questi messaggi :)
è sicuramente a causa delle mie limitate competenze, ma temo d'aver già fatto qualche danno applicando queste modifiche "a pezzi".
Proverò a fare un po' di pulizia e ripristinare la situazione del sito a qualche giorno fa, poi forse ritenterò di installare e configurare il vostro plugin. Per il momento mi arrendo
