### ISSUE TITLE
FRONTEND NON VISIBILE 

### ISSUE THREAD

**Issue by Pr1zma3** [overclokk/italy-cookie-choices#59]
Ciao 
da back end tutto funziona a meraviglia ma quando disconetto e controllo l'online il banner non c'è?
Perchè? - premetto cancellato cache, cronologia, visualizzato su altri dispositivi e pc ma non si vede

Marzia

**Comment by overclokk** [comment]
Ciao @marziadimeo hai settato correttamente le opzioni del plugin? In particolare la prima?

**Comment by overclokk** [comment]
Ciao @marziadimeo hai poi risolto?

**Comment by Pr1zma3** [comment]
Si
grazie mille
Mz

Il 27/06/2015 10:04, Enea ha scritto:

**Comment by overclokk** [comment]
:+1:
