### ISSUE TITLE
Nuova struttura file php e classi plugin

### ISSUE THREAD

**Issue by overclokk** [overclokk/italy-cookie-choices#60]
Come abbiamo visto è diventato un po' troppo dispendioso da mantenere e aggiungere codice quindi per la prossima release pensavo ad una struttura così:

italy-cookie-choices.php (init)
..admin/
....classi per il BE
....classi per la sanitizzazione
..class/
....classe per il FE

Che ne dite? @acardinale @andreapernici

**Comment by acardinale** [comment]
Per me è uguale.
Logicamente concordo nel passare ad una struttura più organizzata.

**Comment by overclokk** [comment]
Ok, perfetto, intanto vedo di lavorarci nei prossimi giorni :-)

**Comment by overclokk** [comment]
Visto che ora c'è la libreria php dici che puoi essere utile l'utilizzo di interfacce e classi astratte? Così da usare questa per il porting sulle altre piattaforme e non quella di WP (che diventerebbe più scomodo), che ne dici?

**Comment by acardinale** [comment]
Umhh, dipende da come lo si vuole impostare. Io ho dovuto replicare (non al 100%) alcune funzioni WP (esc_js, esc_ur, wp_json_encode, etc...)

**Comment by overclokk** [comment]
Si, ho visto, quelle sono le funzioni per l'escape dal DB, ogni CMS in teoria dovrebbe avere le proprie quindi per esempio i metodi per la sicurezza in una libreria a parte, chi non ne ha bisogno usa solo la classe per il banner e per la sicurezza quelle fornite dal CMS usato, questo per rendere più flessibile e facilmente portabile la classe php.

**Comment by acardinale** [comment]
Non ho utilizzato nessun CMS/Framework... php pure.
Quei metodi in questo caso servono per fare l'escape per le stringhe del javascript.
Quelle di WP in più credo abbiano il supporto per diversi charset.
Comunque si può fare.
