### ISSUE TITLE
Osservazioni su nuova versione

### ISSUE THREAD

**Issue by thinkaboutit** [overclokk/italy-cookie-choices#61]
Ciao Enea,

Ho un problema con il pulsante maggiori informazioni, in quanto se lo clicco nella pagina di destinazione non appare più l'avviso (come se avessi accettato quindi)

Vorrei chiederti se è possibile decidere l'altezza del banner informativo (ora è ridotto ad una linea nel mio caso) 

nel backend c'è un refuso (Accettazione continuando la navigazione):
Attiva l'accettzazione se l'utente continua la navigazione 

Nel testo da mostrare non riesco a dare uno spazio tra la fine del testo e il pulsante Maggiori informazioni.

sempre grazie e complimenti.

**Comment by acardinale** [comment]
Ciao @thinkaboutit ,
l'opzione che indichi come refuso è attiva?

**Comment by thinkaboutit** [comment]
Si  è attiva. Penso che possa essere considerato l' unico link che se
cliccato non deve dare il consenso in quanto devo ancora leggere l'
informativa estesa. corretto?
Il 08/giu/2015 21:42, "acardinale" notifications@github.com ha scritto:

**Comment by acardinale** [comment]
No,
attiva quel comportamento che hai indicato: se l'utente naviga sul sito accetta e dunque "non appare più l'avviso (come se avessi accettato quindi)" ;)

Se non vuoi che sia così, disattivala :)

**Comment by thinkaboutit** [comment]
Ok grazie!
Il 08/giu/2015 21:50, "acardinale" notifications@github.com ha scritto:

**Comment by acardinale** [comment]
@thinkaboutit figurati

**Comment by overclokk** [comment]
@thinkaboutit la mia grammatica non è eccelsa :-P tu come lo scriveresti?

**Comment by acardinale** [comment]
@overclokk credo intendesse la parola "l'accett**z**azione"

**Comment by overclokk** [comment]
trovato :-P
#62 

Corretto :-)

**Comment by thinkaboutit** [comment]
Si era la z ;)
Il 08/giu/2015 22:39, "Enea" notifications@github.com ha scritto:
