### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by aldolat** [overclokk/italy-cookie-choices#62]
La frase "Attiva l'accettzazione se l'utente continua la navigazione" dovrebbe essere "Attiva l'accettazione se l'utente continua la navigazione".

**Comment by overclokk** [comment]
@aldolat grazie mille ora correggo e la prossima release carico

**Comment by aldolat** [comment]
Ottimo! :)
Ne ho trovato un altro:

"Script inseriti nella head e nel footer non automaticmente bloccati."
che dovrebbe essere:
"Script inseriti nella head e nel footer non **automaticamente** bloccati."

**Comment by overclokk** [comment]
Corretto anche questo, grazie mille :-)
