### ISSUE TITLE
Il click sull'OK del banner non genera l'accettazione della cookie policy 

### ISSUE THREAD

**Issue by stockton78** [overclokk/italy-cookie-choices#64]
Ciao,

Ho un sito web ospitato da OVH (PHP 5.4, ma ho provato anche la 5.5), non ho avuto problemi con la versione "separata" dei due plugin Italy Cookie Choice e Third-Party Eraser.

Ieri ho installato la versione "unificata" (la 2.1.0), e al momento non si riesce a chiudere il banner al click dell'OK. Cliccando sul link dell'informativa (o su qualsiasi altro link interno del sito), i cookie vengono accettati e dalla pagina successiva tutti i banner/video vengono mostrati.

L'attuale configurazione è: 
- Attiva l'accettazione se l'utente continua la navigazione
- Stile, nome e valore del Cookie a default
- Cookie da tutti gli embed nella tua pagina, eccetto head e footer (Beta)

Se attivo lo scroll del mouse o il reload della pagina, il problema si presenta ugualmente, peggiorato dalla schermata bianca del sito.

**Comment by acardinale** [comment]
Ciao @stockton78 puoi fornire l'url del sito?

**Comment by stockton78** [comment]
Ciao,

Eccola http://webpointzero.com
Specifico che al momento ho disabilitato anche ogni plugin di caching.

Grazie,

**Comment by acardinale** [comment]
@stockton78 non riesco ad aprirlo. Credo che l'opzione bodyBlock blocchi qualcosa di "vitale"

**Comment by overclokk** [comment]
Io ho provato ora e continuando la navigazione ha creato il cookie correttamente, browser chrome, al click effettivamente non parte l'evento, che non ci sia un jQuery che crea conflitto?

**Comment by stockton78** [comment]
@acardinale Non ho capito cosa non riesci ad aprire (il sito, il banner...)
@overclokk Sì, è come ho scritto nell'apertura dell'issue, ma nella versione precedente (quella con i due plugin separati) funzionava correttamente, il banner si chiudeva al click e il consenso veniva acquisito. Cos'è stato cambiato?

**Comment by acardinale** [comment]
@stockton78 si, il sito. E' molto lento.

**Comment by stockton78** [comment]
@overclokk Allora, ho provato a impostare lo scroll del mouse + reload della pagina, ed effettivamente su Chrome funziona correttamente, nel senso che scrollando ricarica la pagina con i contenuti sbloccati, e cliccando OK sul banner lo chiude ricaricando la pagina. Su IE11 permane invece il problema del reload in "pagina bianca".

**Comment by overclokk** [comment]
Disabilita tutti i plugin e riprova
Se funziona devi riabilitare un plugin alla volte e vedere quale va in conflitto
Se non funziona attiva il tema standard e riprova

**Comment by stockton78** [comment]
@overclokk Ok, pare fosse il banner AdSense nella header del sito, gestito direttamente dal template WP. Dopo averlo disabilitato, funziona anche da Explorer.

**Comment by overclokk** [comment]
Ok, perfetto :-)
