### ISSUE TITLE
Sito che scompare.

### ISSUE THREAD

**Issue by andreapernici** [overclokk/italy-cookie-choices#65]
E' possibile che se uno usa jquery da qualche CDN il blocco totale lo elimini causando il blocco di tutto il sito?

Forse potremmo pensare delle eccezioni?

**Comment by acardinale** [comment]
E' prevista nella prossima release.
Nella versione PHP c'è già.
Non solo c'è "esclusione dal blocco body" "inclusione blocco head"
ma si possono utilizzare le espressioni regolari (guarda il config-sample.php)
