### ISSUE TITLE
Non compare,messaggio d'errore dopo il Footer.

### ISSUE THREAD

**Issue by ghost** [overclokk/italy-cookie-choices#66]
Gentilissimo Enea Overclokk,
innnazitutto complimenti per il plugin ben fatto,l'ho sperimentato su 2 temi custom e funziona a meraviglia.
Ho pero' un problema con un tema, sempre custom, che avevo fatto 1m anno fa.
Attivando il plugin,mi compare dopo il footre del sito il seguente messaggio d'errore:
Fatal error: Call to undefined function wp_json_encode() in D:\inetpub\webs\lecavedelceppoit\wp-content\plugins\italy-cookie-choices\italy-cookie-choices.php on line 1448

Il sito e' il seguente: http://www.lecavedelceppo.it/

Penso che il problema sia dovuto in qualche errore nel file functions.php o da qualche altra parte,
se, quando hai tempo, potevi per favore dare un'occhiata.
Ti ringrazio in anticipo dell'attenzione,
Buon lavoro
Andrea

**Comment by overclokk** [comment]
Ciao @andreavicari e grazie dei complimenti :-) che anche @andreapernici e @acardinale apprezzeranno :-)

Quell'errore ce l'hai perché hai una versione di WordPress precedente alla 4.1, per risolvere ti basta semplicemente fare l'aggiornamento.

**Comment by ghost** [comment]
Gentilissimi Enea e collaboratori,
grazie davvero per l'aiuto (pensavo di aver fatto qualche pasticcio io..) e per il plugin che 
e' davvero il migliore per i Cookies tra quelli provati fin ora.
Grazie ancora e buon lavoro!! :)
Andrea

**Comment by overclokk** [comment]
Ottimo :-)
