### ISSUE TITLE
Aggiunta possibilità di chiusura banner

### ISSUE THREAD

**Issue by massimomarazzi** [overclokk/italy-cookie-choices#67]
Ciao, sto provando il plugin su alcuni siti. Vorrei chiedere se è possibile aggiungere la conferma anche cliccando sul banner in qualsiasi punto o anche nel corpo del sito in qualsiasi punto, in pratica aggiungere un evento click in qualsiasi parte del sito per dare la conferma.

**Comment by overclokk** [comment]
Ciao @massimomarazzi nella versione 2.1.0 c'è l'opzione per l'accettazione al proseguimento della navigazione, quindi cliccando su qualsiasi link interno alla pagina, altrimenti c'è l'accettazione allo scroll, già queste due attive direi siano sufficienti, aggiungere anche il click ovunque non avrebbe senso.
