### ISSUE TITLE
Da valutare: blocco preventivo cookie

### ISSUE THREAD

**Issue by overclokk** [overclokk/italy-cookie-choices#7]
Devo valutarlo molto bene, sia da un punto di vista legale (se non dovesse bloccare tutto sono grane), sia da un punto di vista tecnico, ci sono cookie php, js e ajax.

**Comment by avionicom** [comment]
Ciao overclokk, penso si sia chiarito il fatto che purtroppo la legge italiana richiede il blocco preventivo dei cookie... quindi secondo me il tuo plugin dovrebbe proprio implementare questa parte come prioritaria, altrimenti esso non è complaint con la legge italiana.

**Comment by overclokk** [comment]
Ciao @avionicom il blocco dei cookie è in fase di sviluppo, al momento puoi integrare la funzionalità con il plugin di Andrea Pernici https://wordpress.org/plugins/third-party-cookie-eraser/ che blocca i cookie dei vari embed.

**Comment by avionicom** [comment]
OK grazie! Proverò anche il plugin di Andrea Pernici.

**Comment by overclokk** [comment]
Perfetto :-)

**Comment by d4lecooper** [comment]
Third party cookie eraser, se configurato bene e in coppia con un plugin 
che imposta il bannerino, funziona alla grande per la cookielaw. Attendo 
comunque anch'io aggiornamenti da questo interessante progetto. Sarebbe 
bello inserire la funzionalità di analisi dei cookies da tutte le pagine 
di un sito, così da avere un tool completo e autonomo una volta per 
tutte. Se ho tempo ed è ben accetta farò una pull request a questo 
proposito :D
Saluti, Matteo

Il 28/05/2015 17:33, avionicom ha scritto:

> OK grazie! Proverò anche il plugin di Andrea Pernici.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/overclokk/italy-cookie-choices/issues/7#issuecomment-106415596.

## 

_ML_

**Comment by overclokk** [comment]
@d4lecooper Di forza lavoro ce n'è sempre bisogno, apri pure una issue con la tua proposta e la valutiamo insieme (più che altro per tenerne traccia così posso chiudere quelle risolte)

**Comment by marcosiino** [comment]
Ciao, sto valutando se usare il tuo plugin nei miei siti. Attualmente non userò il blocco preventivo dei cookie (c'è molta confusione a riguardo e la legge a mio avviso e secondo alcuni legali con cui ho parlato va ancora interpretata e bisogna capire come si comporteranno anche gli altri siti). Intanto ho deciso di adeguarmi con banner e informativa ma senza bloccare preventivamente i cookie, anche perché la maggior parte dei siti, compresi molti siti istituzionali, (quasi tutti, tranne forse quello del governo e pochi altri) non fanno il blocco preventivo ma mostrano solo il banner e l'informativa.

Volevo chiederti: siccome ho letto che stai lavorando al blocco preventivo, ti prego, nel caso in cui lo implementerai nelle successive release, di dare la possibilità di scegliere al gestore del sito se vuole usare il blocco preventivo o meno, e di renderlo disattivo di default. Questo perché se io decido di non voler usare il blocco preventivo (giusto o sbagliato che sia a livello legale), non vorrei ritrovarmi poi con il blocco preventivo attivato quando aggiornerò il tuo plugin nel momento in cui rilascerai questa feature, ma vorrei essere io ad abilitarla nel caso in cui decidessi di farlo. Puoi confermarmi ciò prima che installo il tuo plugin su parecchi siti che ho ? :)

**Comment by overclokk** [comment]
Ciao @marcosiino assolutamente, ogni nuova opzione sarà sempre disattivata di default proprio perché è l'utente che deve decidere cosa fare del suo sito :-) quindi installa pure il plugin :-)

**Comment by lopinsjk** [comment]
Peccato sia solo per wordpress. Consigli per un sito html5 puro?

**Comment by overclokk** [comment]
Blocco preventivo dei cookie di terze parti installati dagli embed in content e widget aggiunto con la versione 2.0.0

@lopinsjk Per siti in puro HTML puoi semplicemente copiare lo snippet generato dal plugin

**Comment by avionicom** [comment]
Overclokk grazie per aver reso questo plugin molto completo (io sono stato uno dei primi a credere in questo plugin!)!! Ho visto nella versione 2 hai aggiunto un pò di cose e quindi ti faccio due domande:
1) Io avevo già configurato il plugin di pernici come da tua indicazione, ma ora è integrato nel tuo plugin... questo significa che va cancellato o posso lasciare tutto così com'è?
2) Ho visto che l'opzione "Aggiorna la pagina dopo l'accettazione" è ora DEPRECATA. Perchè? Io credo sia importante l'aggiornamento poichè solo così posso sbloccare quelle funzioni e blocchi che hanno tanti cookie di terze parti e profilanti, o sbaglio?
Grazie anticipatamente.

**Comment by overclokk** [comment]
Ciao @avionicom grazie a te per la fiducia :-)

1) si, puoi cancellarlo

2) E' deprecata perché ora all'accettazione tutto ciò che è bloccato viene eseguito nella pagina senza più bisogno del refresh.

**Comment by avionicom** [comment]
OK grazie per le tue rapide risposte @overclokk 
Saluti ;-)

**Comment by overclokk** [comment]
Di nulla :-)
