### ISSUE TITLE
Blocco preventivo cookie

### ISSUE THREAD

**Issue by cassy79** [overclokk/italy-cookie-choices#70]
Salve, sto testando il blocco preventivo dei cookie e non mi è chiara una cosa...
Effettuo questi passaggi:

1) Svuoto la cache di Chrome
2) Apro il mio sito su cui ho installato il plugin e configurato il blocco cookie ma non clicco su Accetta cookie (quindi non tocco nulla e non procedo nella navigazione)
3) Apro le impostazioni avanzate di Chrome e vado in Cookie e dati dei siti.
In questa cartella trovo i 4 cookie inviati dal mio sito.

Domanda.... il blocco preventivo impedisce l'invio effettivo dei cookie se non si accettano nè si procede con la navigazione? Se sì, perchè nella cartella di chrome trovo i 4 cookie inviati dal mio sito?

Grazie

**Comment by overclokk** [comment]
Ciao @cassy79 il blocco preventivo è per i cookie di terze parti installati dagli script che usi sul tuo sito, per esempio youtube, facebook, twitter, ecc.

**Comment by cassy79** [comment]
Anche per Adsense è previsto il blocco preventivo e sul mio sito uso i banner adsense. Quindi sono andata nella cartella cookie di chrome e mi sono ritrovata i cookie di doubleclick, nonostante sul sito il banner sia oscurato..

**Comment by cassy79** [comment]
http://www.michelepisani.it/articoli/cookie-policy-come-gestire-analytics-adsense-e-i-bottoni-social/#comment-115

**Comment by overclokk** [comment]
Anche AdSense può essere bloccato preventivamente, è possibile vedere una URL di una pagina del tuo sito con il plugin attivo a AdSense?

**Comment by cassy79** [comment]
link

**Comment by overclokk** [comment]
A quanto vedo funziona correttamente, AdSense è bloccato e non c'è nessun cookie oltre quelli tecnici e di google analitycs.

Il refresh lo puoi togliere.

**Comment by cassy79** [comment]
ma infatti ho detto poco sopra che nel frontend vedi che blocca il contenuto (appare il messaggio per sbloccare i contenuti). Però se segui i passaggi che ho fatto io e vai a vedere la cartella dei cookie di chrome, ti ritrovi i cookie di doubleclick nella cartella, ancora prima di accettare. Hai provato pure tu??
Hai svuotato la cache di chrome e poi hai aperto semplicemente il sito senza cliccare su Accetto?

**Comment by cassy79** [comment]
Aspetta... se è corretto questo elenco, vuol dire non c'è problema:

Elenco cookie:
Nome sito: doubleclick.net 
Dati memorizzati localmente: ID canale
(ID canale è giusto? cioè non installa cookie?)

Nome sito: nomesito.it
Dati memorizzati localmente: 2 cookie (ga e gat)
questi sono cookie tecnici e quindi non vengono bloccati perchè non c'è necessità di farlo....
visto che ho anche reso anonimo lo script di analitycs. 

Confermi?

**Comment by andreapernici** [comment]
I dati di doubleclick forse sono impostati nell'head o footer quindi devi usare il box di testo nel pannello admin del plugin.

**Comment by cassy79** [comment]
Le opzioni sono tre:
1)Cookie da tutti gli embed nel tuo contenuto (selezionata)
2)Cookie da tutti gli embed nei tuoi widget (selezionata) 
3)Cookie da tutti gli embed nella tua pagina, eccetto head e footer (questa non posso selezionarla perchè blocca tutti i cookie eccetto quelli di head e footer. Se dico bene...)

Ora ho fatto un test vedendo la cartella dopo lo sblocco dei contenuti.
Funziona egregiamente. Mi ero solo impressionata vedendo ID canale. 
ID canale non è un cookie, se dico bene anche qui....
Grazie!

**Comment by cassy79** [comment]
@andreapernici grazie per la risposta. No, sono impostati nei contenuti... Però grazie, mi hai ricordato che volendo posso bloccare anche quelli, inserendoli manualmente nel pannello...

**Comment by andreapernici** [comment]
Non ho capito nulla :D
Puoi farmi un riepilogo della tua situazione attuale?
Hai risolto?

**Comment by andreapernici** [comment]
Ho visto il tuo sito recuperando il link via mail e a me sembra tutto correttamente bloccato. L'unico cookie che hai è quello di Google Analytics.

**Comment by cassy79** [comment]
Sì, ho risolto..
perchè vedevo questo nell'elenco dei cookie di chrome:

Nome sito: doubleclick.net 
Dati memorizzati localmente: ID canale
("ID canale" non è un cookie)

Ho visto la cartella cookie dopo aver cliccato su Accetto e la situazione cambia:
doobleclick.net installa due cookie (_drt_ e id)
