### ISSUE TITLE
Widget Social & YouTube

### ISSUE THREAD

**Issue by Tommylip** [overclokk/italy-cookie-choices#71]
Ciao
io ho installato il plugin su due miei siti (socialmedialife.it e mobilitapubblicoimpiego.it) e sta funzionando correttamente eccezion fatta per:
widget twitter
youtube embedded video
facebook connect

Ho provato anche ad inserire gli script ma credo di sbagliare qualcosa.

Qualche suggerimento a riguardo?

**Comment by overclokk** [comment]
Ciao @Tommylip ho appena creato la wiki con degli esempi https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki prova a vedere se così risolvi.

**Comment by Tommylip** [comment]
Ho provato a usare lo script di FB Connect

```
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : 'your-app-id',
      xfbml      : true,
      version    : 'v2.3'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
```

ma non funziona, non lo blocca

**Comment by overclokk** [comment]
Questo è tale a quale quello che hai nel sorgente della pagina?
E' uno script che hai aggiunto a mano tu o è generato da un plugin?
Hai plugin di cache abilitati?

**Comment by Tommylip** [comment]
Forse hai ragione, sono stato un pò superficiale, indago e ti dico, al massimo lo aggiungi poi nel wiki

**Comment by Tommylip** [comment]
Allora, il codice sorgente mostra questo:

<div id="fb-root"></div>

<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/it_IT/sdk.js#xfbml=1&version=v2.3&appId=507545929334655";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>  <div style="display:none">
    </div>

non ho plugin Cache e credo sia generato da un plugin terzo, perchè io di certo non l'ho inserito.
La cosa strana e che blocca senza problemi il classico widget Fb Page Like ma Ghostery continua a mostrare questo cookie su mobilitapubblicoimpiego.it

**Comment by overclokk** [comment]
Nella wiki ci sono già gli esempi, c'è anche l'esempio dello script non minificato.

comunque prova a:
Pulisci cache e cookie del browser ed eventuale plugin di cache
Disabilita tutti i plugin  e riprova
Se funziona riattiva i plugin uno alla volta
Se non funziona riattiva il tema standard e riprova

**Comment by overclokk** [comment]
Ciao @Tommylip hai poi risolto?

**Comment by Tommylip** [comment]
Beh diciamo in parte, nel senso che blocca quasi tutto, ma non Twitter Button (che parte, credo, dal Widget Twitter)

**Comment by overclokk** [comment]
Hai provato a seguire la guida per gli script personalizzati? https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/Custom-script
