### ISSUE TITLE
Sanitize & escape custom CSS

### ISSUE THREAD

**Issue by overclokk** [overclokk/italy-cookie-choices#74]
Non ho trovato molto in merito, l'obiettivo è quello ovviamente di ridurre al minimo eventuali attacchi XSS

**Comment by acardinale** [comment]
Quello dovrebbe essere lato server. Gli escape utilizzati per il print_inline_script, servono solo per visualizzare lo script inline "escappato" correttamente

**Comment by overclokk** [comment]
Si, si, ovviamente, andavo di fretta e non ho potuto spiegare meglio, la semplice sanitize_text_field non è sufficiente, stavo cercando qualcosa di specifico che  facesse anche un controllo sulla corretta sintassi inserita, per ora ho trovato questo https://github.com/Schepp/CSS-Parser che però è vecchio di 6 anni, altrimenti in jetpack usano una classe specifica per sanitizzare correttamente il css, qui comunque ci sono anche altri metodi http://wordpress.stackexchange.com/questions/53970/sanitize-user-entered-css

Per quanto riguarda l'escape devo verificare che esc_attr() sia sufficiente, altrimenti bisogna valutare altro.

**Comment by overclokk** [comment]
Ho provato con sanitize_text_field e esc_attr e sembra funzionare correttamente, per ora chiudo
