### ISSUE TITLE
No banner

### ISSUE THREAD

**Issue by SoniaBertinat** [overclokk/italy-cookie-choices#77]
Allora avevo impostato il plugin di Andrea Pernici con Cookie Law info prima del 2 giugno. Ora noto però che nonostante io clicchi su ok i contenuti bloccati rimangono tali.
Allora leggo che avete collegato i due plugin e attivo ItalyCookieChoices disattivando CLI.
Però non mi appare il banner nè su browser nè su iphone.
Ovviamente quindi se attivo TPE mi blocca i cookie ma non posso sbloccarli :(
Cosa sbaglio?
Grazie mille

**Comment by overclokk** [comment]
Qual'è la configurazione attuale del plugin che hai settato?

**Comment by SoniaBertinat** [comment]
Italy Cookie Choices Versione 1.2.2 
Third Party Cookie Eraser Versione 1.0.2

**Comment by SoniaBertinat** [comment]
Aggiornamento: ho scaricato l'ultima versione di ICC e ho notato che non era compatibile con le mie versioni di wp :/ Ho aggiornato WP e tutto è andato al suo posto.
Grazie mille a tutti e due per l'ottimo servizio!

**Comment by SoniaBertinat** [comment]
Ne approfitto... come posso cambiare il colore delle scritte Maggiori informazioni e Chiudi senza che mi cambi l'impostazione colore in altri elementi del sito? E separare le suddette scritte di almeno uno spazio dalla fine dell'informativa?

**Comment by andreapernici** [comment]
Nelle future release metteremo del custom CSS.

**Comment by overclokk** [comment]
@SoniaBertinat :+1:

**Comment by SoniaBertinat** [comment]
Grazie mille! Aspetto allora i css ma davvero è un dettaglio :) 

Inviato da iPhone
