### ISSUE TITLE
Problema con i feed RSS

### ISSUE THREAD

**Issue by ClaudiaDeLuca** [overclokk/italy-cookie-choices#78]
Ciao, grazie per aver creato questo plugin che è molto utile. Lo sto usando sul mio sito ma purtroppo mi crea dei seri problemi con i feed di Feedburner che non sono più visibili!
Il link ai feed è questo  -> http://feeds.feedburner.com/thingsiliketoday/TILT
L'errore che ricevo è il seguente:

Errore interpretazione XML: contenuto illegale dopo l’elemento
Indirizzo: http://feeds.feedburner.com/thingsiliketoday/TILT
Riga numero 1, colonna 66:<style>.icc{margin-top:36px}</style><script>var coNA="displayCookieConsent",coVA="y";scroll="1",elPos="fixed",infoClass="",closeClass="",htmlM="",rel="1",tar="1",bgB="#212121",btcB="#ffffff",bPos="top:0",jsArr = [];function allowCookie(){var a,b=document.getElementsByClassName("el"),c=new RegExp("<script.*?");for(a=0;a<b.length;a++){b[a].removeChild(b[a].childNodes[0]);var d=c.test(jsArr[a]);if(d){var e=/<script.*?src="(.*?)"/,f=e.test(jsArr[a]);f&&(f=e.exec(jsArr[a]),loadJS(f[1]));var g=/<script\b[^>]_>([\s\S]_?)<\/script>/gm,h=g.exec(jsArr[a]);h[1]&&appendJS(h[1])}else{var i=b[a].innerHTML;d=i.replace(/<cookie>/g,jsArr[a]),b[a].innerHTML=d}}}function loadJS(a){var b=document.createElement("script");b.type="application/javascript",b.src=a,document.body.appendChild(b)}function appendJS(a){var b=document.createElement("script");b.type="text/javascript";var c=a;try{b.appendChild(document.createTextNode(c)),document.body.appendChild(b)}catch(d){b.text=c,document.body.appendChild(b)}}!function(a){if(a.cookieChoices)return a.cookieChoices;var b=a.document,c=b.documentElement,d="textContent"in b.body,e=function(){function a(a,d,e,f){htmlM&&(c.className+=" icc");var k="color:"+btcB+";position:"+elPos+";width:100%;background-color:"+bgB+";margin:0; left:0;"+bPos+";padding:2px;z-index:9999;text-align:left;",l=b.createElement("div"),m="max-width:980px;margin-right:auto;margin-left:auto;padding:15px;";l.id=t,l.style.cssText=k;var n=b.createElement("div");return n.style.cssText=m,n.appendChild(h(a)),n.appendChild(g()),e&&f&&n.appendChild(j(e,f)),n.appendChild(i(d)),l.appendChild(n),l}function e(a,c,d,e){var f="position:fixed;width:100%;height:100%;z-index:999;top:0;left:0;opacity:0.5;filter:alpha(opacity=50);background-color:#ccc;",k="z-index:9999;position:fixed;left:50%;top:50%;bottom:0%;",l="position:relative;left:-50%;margin-top:-25%;background-color:"+bgB+";padding:20px;box-shadow:4px 4px 25px #888;",m=b.createElement("div");m.id=t;var n=b.createElement("div");n.style.cssText=f;var o=b.createElement("div");o.style.cssText=l;var p=b.createElement("div");p.style.cssText=k;var q=i(c);return o.appendChild(h(a)),o.appendChild(g()),d&&e&&o.appendChild(j(d,e)),o.appendChild(q),p.appendChild(o),m.appendChild(n),m.appendChild(p),m}function f(a,b){d?a.textContent=b:a.innerText=b}function g(){var a="clear:both;border-color:transparent;margin-top:5px;margin-bottom:5px",c=b.createElement("hr");return c.style.cssText=a,c}function h(a){var c=b.createElement("span");return f(c,a),c}function i(a){var c="color: "+btcB+";padding: 3px 7px;font-size: 14px;line-height: 14px;text-decoration: none;text-transform: uppercase;margin:0;margin-bottom:2px;letter-spacing: 0.115em;display: inline-block;font-weight: normal; text-align: center;  vertical-align: middle;  cursor: pointer;  border: 1px solid "+btcB+";background: rgba(255, 255, 255, 0.03);",d=b.createElement("a");return f(d,a),d.id=u,d.className=closeClass,d.href="#",d.style.cssText=c,d}function j(a,c){var d="color: "+btcB+";padding: 3px 7px;font-size: 14px;line-height: 14px;text-decoration: none;text-transform: uppercase;margin-right: 20px;margin-bottom:2px;letter-spacing: 0.115em;display: inline-block;font-weight: normal; text-align: center;  vertical-align: middle;  cursor: pointer;  border: 1px solid "+btcB+";background: rgba(255, 255, 255, 0.03);",e=b.createElement("a");return f(e,a),e.className=infoClass,e.href=c,tar&&(e.target="_blank"),e.style.cssText=d,e}function k(){return r()&&(htmlM&&c.classList.remove("icc"),allowCookie(),q(),o()),rel&&b.location.reload(),!1}function l(c,d,f,g,h){if(r()){var i=h?e(c,d,f,g):a(c,d,f,g),j=b.createDocumentFragment();j.appendChild(i),b.body.appendChild(j.cloneNode(!0)),b.getElementById(u).onclick=k,scroll&&(b.onscroll=k)}}function m(a,b,c,d){l(a,b,c,d,!1)}function n(a,b,c,d){l(a,b,c,d,!0)}function o(){var a=b.getElementById(t);null!==a&&a.parentNode.removeChild(a)}function p(){k()}function q(){var a=new Date;a.setFullYear(a.getFullYear()+1),b.cookie=s+"="+coVA+"; expires="+a.toGMTString()+";path=/"}function r(){return!b.cookie.match(new RegExp(s+"=([^;]+)"))}var s=coNA,t="cookieChoiceInfo",u="cookieChoiceDismiss",v={};return v.showCookieConsentBar=m,v.showCookieConsentDialog=n,v.removeCookieConsent=p,v}();return a.cookieChoices=e,e}(this);document.addEventListener("DOMContentLoaded", function(event) {cookieChoices.showCookieConsentBar("Questo sito utilizza cookie, anche di terze parti, per inviarti pubblicit\u00e0 e servizi in linea con le tue preferenze. Chiudendo questo banner, scorrendo questa pagina o cliccando su qualunque suo elemento acconsenti all\u2019uso dei cookie. Se vuoi saperne di pi\u00f9 o negare il consenso a tutti o ad alcuni cookie leggi la Privacy Policy.", "OK", "Privacy Policy", "https://www.iubenda.com/privacy-policy/562783");});</script><noscript><style>html{margin-top:35px}</style><div id="cookieChoiceInfo" style="position:absolute;width:100%;margin:0px;left:0px;top:0px;padding:4px;z-index:9999;text-align:center;background-color:rgb(238, 238, 238);"><span>"Questo sito utilizza cookie, anche di terze parti, per inviarti pubblicit\u00e0 e servizi in linea con le tue preferenze. Chiudendo questo banner, scorrendo questa pagina o cliccando su qualunque suo elemento acconsenti all\u2019uso dei cookie. Se vuoi saperne di pi\u00f9 o negare il consenso a tutti o ad alcuni cookie leggi la Privacy Policy."</span><a href="https://www.iubenda.com/privacy-policy/562783" target="_blank" style="margin-left:8px;">Privacy Policy</a><a id="cookieChoiceDismiss" href="#" style="margin-left:24px;display:none;">OK</a></div></div></noscript><?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
-----------------------------------------------------------------^

Grazie per l'aiuto.

**Comment by overclokk** [comment]
Ciao @ClaudiaDeLuca oltre alla versione PHP e WP vorrei sapere anche la configurazione attuale del plugin.

**Comment by ClaudiaDeLuca** [comment]
Ciao Enea, la versione PHP è la 5.3.29, quella di WP è la 4.2.2
Ti allego lo screenshot con le impostazioni del plugin.
Cmq ho provato a disattivarlo e riattivarlo e dopo numerosi tentativi ora mi sembra che il problema si sia risolto... se vado sul link dei feed ora l'errore è scomparso.
Non so come sia possibile non ho fatto altro! 
Grazie comunque per la risposta. 
![cookie-plugin](https://cloud.githubusercontent.com/assets/12859232/8133337/16092e10-1128-11e5-8edb-76b2087b213d.png)

**Comment by overclokk** [comment]
@ClaudiaDeLuca non vorrei che ci fosse stato un problema con la chache? Usi plugin per la cache?

Ad ogni modo se mi confermi che ora  non hai più problemi metto risolto.

Ciao

**Comment by ClaudiaDeLuca** [comment]
Si uso W3 Total Cache ma non credo che il problema fosse quello perchè avevo cancellato la cache durante le prove. Comunque per ora sembra a posto. Scusa il falso allarme.
Ciao

**Comment by overclokk** [comment]
Ottimo, perfetto :-)
