### ISSUE TITLE
Opzioni Blocco Cookie non vengono salvate

### ISSUE THREAD

**Issue by ClaudiaDeLuca** [overclokk/italy-cookie-choices#82]
Un piccolo problema riguardante il blocco.
Nella sezione Blocco dei cookie di terze parti ho provato a selezionare Cookie da tutti gli embed nel tuo contenuto (Beta) o Cookie da tutti gli embed nei tuoi widget (Beta) anche se sono deprecate ma non è possibile salvare l'opzione! L'unica opzione che riesco a salvare è Cookie da tutti gli embed nella tua pagina, eccetto head e footer (Beta). E' normale?
Grazie

**Comment by overclokk** [comment]
Ciao @ClaudiaDeLuca se la terza opzione è selezionata le prima due non vengono salvate, se la terza non è selezionata le prime due vengono salvate, prova solo con le prime due.

**Comment by ClaudiaDeLuca** [comment]
Perfetto, grazie!
