### ISSUE TITLE
Mozilla FF per PC

### ISSUE THREAD

**Issue by gleenk** [overclokk/italy-cookie-choices#83]
Su Firefox (PC),  il consenso pare non andare. Prende l'input ma finchè non refresho non accade nulla :)

Purtroppo su PC la console non mi dà segni di vita per debuggare...

**Comment by overclokk** [comment]
Ciao, e' possibile vedere una url?
Che impostazioni hai settato?

**Comment by overclokk** [comment]
Ciao @gleenk hai poi risolto?

**Comment by gleenk** [comment]
Ciao in realtà no ma non abbiamo più avuto modo di fare altri test per mancanza di tempo e, ahimè, abbiamo dovuto optare per un'altra soluzione. Se ci risarà occasione riaprirò la issue.

**Comment by overclokk** [comment]
Ok, alla prossima.
