### ISSUE TITLE
Funziona anche su Blogger?

### ISSUE THREAD

**Issue by agiorgia062** [overclokk/italy-cookie-choices#84]
Sorry, funziona anche su Blogger/Blogspot? Potreste suggerirmi il procedimento?

**Comment by overclokk** [comment]
Mi sa che ti ho risposto anche su g+ se sei tu che mi hai fatto la domanda, comunque la ripeto anche qui, se puoi agire sull'HTML devi inserire lo snippet generato dal plugin all'interno del tuo HTML prima della chiusura di body, quindi devi avere comunque un WordPress da qualche parte.
