### ISSUE TITLE
bug chiusura banner

### ISSUE THREAD

**Issue by ghostdog6022** [overclokk/italy-cookie-choices#86]
Salve!

Vorrei segnalare un bug, se si clicca su "maggiori informazioni" sul banner, e si apre così la policy in un altra pagina, è impossibile chiudere il banner sulla pagina originaria.

il link al mio sito per provare la cosa

http://gamic.altervista.org/

ciao e grazie per l'ottimo lavoro!!

**Comment by overclokk** [comment]
Ciao @ghostdog6022 
prova a fare questi test https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work e dimmi se continui ad avere lo stesso problema o no.

**Comment by ghostdog6022** [comment]
ciao,

ho fatto varie prove

con chrome e explorer, senza estensioni, con cookie e cache puliti

il tema standard di wordpress e senza altri plugin di wordpress attivati

il problema persiste

**Comment by overclokk** [comment]
Molto strano, mi potresti indicare la configurazione del plugin? Versione di WP e PHP?

**Comment by ghostdog6022** [comment]
La configurazione del plugin è:

blocco preventivo cookie disabilitato

uniche opzioni abilitate

Bottom Bar (Visualizza una barra nel footer con il tuo messaggio)
Accetta l'informativa sull'evento scroll del mouse
Attiva l'accettzazione se l'utente continua la navigazione
Apri la tua pagina per la Cookie policy in una nuova

il blocco dei cookie preventivo non è abilitato, ho giusto modificato il colore del banner e impostato il messaggio sul banner.

wordpress 4.2.2
php 5.3

se c'è bisogno di altro fammi sapere

**Comment by overclokk** [comment]
Ho provato quelle impostazioni su altri siti e non ho avuto lo stesso problema, in questi giorni comunque dovrei riuscire a pubblicare la nuova release, vediamo se aggiornando si mette a posto.

**Comment by ghostdog6022** [comment]
ok grazie

magari è un incopatibilità con qualche impostazione di altervista (uno di questi siti con cui hai provato è sotto altervista?) o magari il mio è un caso particolare (e vabbè in questo caso sarà un problema mio :) )

grazie XD

**Comment by overclokk** [comment]
Ciao @ghostdog6022 prova la nuova versione 2.2.0 e dimmi se hai ancora il problema

**Comment by ghostdog6022** [comment]
si c'è ancora

e provando anche a reinstallare il plugin (le si provano tutte XD) è saltato fuori questo

Fatal error: Call to undefined function deregister_string() in /membri/gamic/wp-content/plugins/italy-cookie-choices/uninstall.php on line 56

un altro bug?

**Comment by overclokk** [comment]
Farò ulteriori test per quel problema.

Il fatal error si è un bug conosciuto e fixato con la versione 2.2.1 appena caricata.
