### ISSUE TITLE
Banner e refresh pagina

### ISSUE THREAD

**Issue by AlexTorre13** [overclokk/italy-cookie-choices#87]
Salve a tutti, per prima cosa complimenti per il plugin davvero ottimo.

Un piccolo problema. Utilizzo per alcuni siti il tema Quadrum, e ho notato che non mettendo la spunta sul refresh della pagina si hanno problemi con i banner gestiti dal tema stesso. Vengono riposizionati, in posti anomali.

Il layout del banner informativo infine con Ie non mantiene le specifiche del colore. Tutto il resto si ma diventa sempre trasparente.

Grazie
Alex Torre

**Comment by overclokk** [comment]
Ciao @AlexTorre13 
purtroppo molti temi (in particolare quelli premium) non sono sviluppati benissimo (anzi) e inseriscono il tag script proprio sotto per esempio al codice dello slider, se questo è il tuo caso allora probabilmente il plugin lo blocca essendo nel corpo pagina, nella prossima release dovrebbe essere stata aggiunta l'opzione per non bloccare certi script (o la prossima o quella dopo).

La modifica dello stile è prevista con la prossima.

**Comment by AlexTorre13** [comment]
Ti ringrazio della risposta. Per ora ho potuto ristabilire il tutto tramite l'opzione di refresh della pagina dopo l'optin.

**Comment by overclokk** [comment]
Se hai modo di provare la nuova versione 2.2.0 e dirmi se hai risolto sarebbe fantastico :-)

**Comment by sitiwebitalia** [comment]
Ciao Enea, io ho installato la 2.2 e se lascio i valori di default (non caricamento pagina) il sito scompare e rimane il banner tradedaubler, se imposto di ricaricare la pagina, va quasi bene, si ricarica, vedo per due secondi il banner tradedoubler e il sito si ricarica regolarmente. Se vuoi quando hai 2 min possiamo provarlo indiretta.

**Comment by overclokk** [comment]
@sitiwebitalia prima segui questi passaggi e dimmi se cambia qualcosa https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work

**Comment by andreapernici** [comment]
Molto probabilmente viene bloccato qualche script di terze parti vitale per il funzionamento del sito.

Usi jquery da librerie esterne o simili? Che tema usi?

**Comment by sitiwebitalia** [comment]
Puo darsi eccolo http://www.theitalianglam.com
se provate ad accettare i cookie vedreto che ricarica ma il banner Expo rimane rimane qualche secondo.

**Comment by andreapernici** [comment]
Non capisco quale è il problema. Hai attivato il refresh di pagina oppure no?

**Comment by sitiwebitalia** [comment]
Si lo riattivato perché senza il refresh il sito dopo l'accettazione spariva e rimaneva solo il banner Expo.

**Comment by sitiwebitalia** [comment]
Cosi comunque ok, solo ho visto che c'è scritto Deprecata e pensavo poi che venisse disabilitato negli upgrade futuri

**Comment by andreapernici** [comment]
Bisognerebbe capire come è fatto il codice in questione. Riesci ad incollarlo?

**Comment by sitiwebitalia** [comment]
ci certo ci provo

![screen_siti_web_italia16](https://cloud.githubusercontent.com/assets/13055427/8387262/72f80814-1c57-11e5-86f4-38324d3def45.jpg)
