### ISSUE TITLE
Template corrotto attivando il Plug-in

### ISSUE THREAD

**Issue by Airesdesign** [overclokk/italy-cookie-choices#88]
Ciao, ho installato e configurato Italy-cookie-choices ma quando l'attivo il sito non si visualizza bene. In pratica mi fa vedere solo header e footer ma tutto il corpo delle pagine scompare, oltre al fatto che non viene fuori in nessun modo (top, bottom o pop-up). Se avete bisogno dei dati per accedere all'admin per controllare ve li invierei tramite mail basta che mi date un indirizzo. Grazie!

**Comment by overclokk** [comment]
Ciao @Airesdesign 
dovresti indicare: versione WP, versione PHP, plugin installati
Ma prima di ogni altra cosa hai provato a eseguire queste operazioni? https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work

**Comment by Airesdesign** [comment]
Ciao!
Si ho provato e niente. Comunque dopo aver aggiornato WP funziona correttamente.
Grazie!
Saluti.

Il giorno 17/giu/2015, alle ore 09:43, Enea notifications@github.com ha scritto:

Ciao @Airesdesign https://github.com/Airesdesign 
dovresti indicare: versione WP, versione PHP, plugin installati
Ma prima di ogni altra cosa hai provato a eseguire queste operazioni? https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work <https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/If-it-doesn't-work>

**Comment by overclokk** [comment]
Ottimo, perfetto :+1:
