### ISSUE TITLE
Cookie che sfugge al blocco e tracciabilità del consenso espresso

### ISSUE THREAD

**Issue by Lukaks** [overclokk/italy-cookie-choices#89]
Ciao Enea, innanzitutto grazie a te e a Pernici per il rimedio trovato, ma vorrei sottoporti due quesiti fra cui una novità che ho riscontrato oggi: 

1) quando installai pochi giorni fa su un sito wordpress i vostri due plugin, veniva bloccato tutto (mappe, adsense, twitter, facebook, ecc.) rimanendo solo i cookie statistici di prima parte, il che come sappiamo non crea problemi ai fini della normativa. Oggi però sono andato a fare una nuova prova, eliminando tutti i cookie dalle Opzioni Privacy del mio browser Mozilla e poi entrando sul mio sito. Il banner è comparso regolarmente, io non ho fatto alcuna azione, ma contemporaneamente mi ritrovo nella cartella cookie del browser una cartellina targata Google.com contenente il cookie NID...come si spiega questo fatto? Pochi giorni fa non residuavano affatto cookie di terze parti, quindi il blocco funzionava alla grande, e ora invece questa sorpresa....cosa bisogna fare? 

2) La seconda cosa che volevo chiederti è se per favore puoi spiegarmi dove viene registrato il consenso espresso dall'utente? Il garante chiede ''un evento documentabile sul server del sito"...cosa intende dire?

Grazie...e scusami, ma le mie nozioni tecniche sono estremamente limitate...Ciao,Lukaks﻿

**Comment by andreapernici** [comment]
1) Ci fai vedere un esempio?

2) è una funzionalità ancora da implementare perché non è affatto chiaro cosa dovrebbe fare.

**Comment by Lukaks** [comment]
Ciao Andrea, grazie per aver risposto.
In merito al quesito del punto 1, oggi ho rifatto la prova e stranamente sembra tornato di nuovo tutto normale, nel senso che trovo solo i cookie del rilevatore statistico di prima parte (cioè il plugin installato direttamente sul sito), ossia cookie del plugin WassUp...che essendo appunto di tipo analitico e senza interazioni con terze parti mi sono limitato a citarli nella informativa. Quindi oggi niente cookie di google.com...

2) Per quanto riguarda il punto 2, ossia la tracciabilità del consenso...posso riportarti quello che si legge nelle dichiarazioni del Garante, il quale chiede che il consenso dell'utente - che avvenga scrollando la pagina o navigando nel sito - debba rimanere registrato sul server di ciascun sito. Quindi credo che intenda la necessità che di quel consenso espresso in quel modo debba rimanere traccia riconoscibile e stabile sul server. Come questo debba o possa avvenire, non ho proprio idea. Ti riporto cosa scrive il garante in una nota di chiarimento sulla normativa, al punto 5, mettendo in evidenza in stampatello la parte più importante:
- 5) Modalità di acquisizione del consenso
  Come noto, nel Provvedimento è stato stabilito che "la prosecuzione della navigazione mediante accesso ad altra area del sito o selezione di un elemento dello stesso (ad esempio, di un'immagine o di un link) comporta la prestazione del consenso all'uso dei cookie" (cfr. punto 1, lett. e), del dispositivo). Al riguardo, si rappresenta che soluzioni per l'acquisizione del consenso basate su "scroll", ovvero sulla prosecuzione della navigazione all'interno della medesima pagina web, da molti prospettate e in effetti particolarmente rilevanti nel caso di dispositivi mobili, sono considerate in linea con i requisiti di legge, qualora queste siano chiaramente indicate nell'informativa e siano in grado di GENERARE UN EVENTO, REGISTRABILE E DOCUMENTABILE PRESSO IL SERVER DEL GESTORE DEL SITO (prima parte), CHE POSSA ESSERE QUALIFICATO COME AZIONE POSITIVA DELL'UTENTE.

Grazie per l'attenzione. Ciao, Lukaks

**Comment by andreapernici** [comment]
Ciao Lukaks,

si ho letto la questione del punto 2 e dobbiamo capire come farla visto che non è molto chiaro cosa si debba registrare per ricondurre tale azione a tale utente visto che il cookie è client side mentre la registrazione è server side e l'utente non è registrato in nessun modo con un account utente.

**Comment by saxcbr** [comment]
Ciao a tutti.
Per il punto 2) avevo pensato ad una soluzione di questo tipo: 
- creare un file di log sul sito 
- all'accesso dell'utente inserire un cookie tecnico con un id univoco random durata lunga 
- registrare questo id univoco in un log sul server con pagina, url provenienza, data, ora e ip 
- allo scroll (= accettazione privacy) registrare sul log che l'id ha fatto lo scroll
- al cambio pagina  (= accettazione privacy) registrare sul log che l'id ha cliccato con pagina, url provenienza, data, ora e ip 
- al click su bottone x accettare registrare sul log che l'id ha accettato con pagina, url provenienza, data, ora e ip 
  In caso di contenzioso dovrà essere prodotto il cookie installato sul pc del richiedente che è l'unico modo per rintracciarlo, dato che il solo ip non è un dato univoco.

Cosa ne pensate ?
Sara

**Comment by Lukaks** [comment]
Ciao Sara,
grazie per il contributo, ma credo che Andrea meglio di me possa valutare la tua proposta.
Un cordiale saluto,
Lukaks

**Comment by Lukaks** [comment]
Ciao Enea, ciao Andrea,
scusate se torno sul tema dei cookie che sfuggono al blocco, ma accogliendo il vostro invito a segnalare stranezze successive all'installazione dei vostri plugin, vi informo che dopo una verifica con Google Chrome (l'ho installato apposta per fare la verifica) per vedere quali cookie vengono bloccati sul mio sito...ho scoperto che mi rimane non bloccato un cookie di Pinterest (ho il tastino Pin.it) . La cosa strana è che mentre Mozilla non lo rileva, Google Chrome lo rileva. Io infatti ero convinto fino ad oggi che fosse tutto bloccato...e invece ho dovuto ricredermi. Insomma, ci sono queste differenze passando da un browser all'altro...
Saluti,
Lukaks

**Comment by andreapernici** [comment]
Ci posti un link.
