### ISSUE TITLE
problema attivando plugin

### ISSUE THREAD

**Issue by Dubbo82** [overclokk/italy-cookie-choices#90]
Ciao,

su questa pagina:
http://www.avvocatogianlucamengoni.it/693/danni-insidie-stradali-come-ottenere-risarcimento

attivando il plugin la quasi totalità del codice non viene visualizzata, e questo avviene anche su altre pagine simile con molto testo e dati. Attivando il debug di wp non riscontro grosse problematiche o per lo meno mi sembra niente che possa causare questo problema. Il bello è che, se tolgo parte del testo – non codice, ma proprio porzioni di testo – la pagina viene visualizzata correttamente, come se ci fossero troppi dati caricati. Ho provato ad aumentare la memoria in config.php, ma niente.

Qualche suggerimento?
wp 4.2
php 5.3.3-7
Italy Cookie Choices

Disattivando Italy Cookie Choices con la stessa quantità di testo la pagina viene visualizzata

In questo momento ho solo questo plugin attivo per la gestione dei cookie nel sito

**Comment by Dubbo82** [comment]
Confermo quanto detto sopra: adesso per questo articolo ho ridotto il contenuto della sidebar e viene visualizzato correttamente prima dell'accettazione dei cookie. E' un comportamento molto strano!

stessa cosa avviene per questo articolo (verificate pure su questo che non ho problemi a lasciarlo non visualizzabile):

http://www.avvocatogianlucamengoni.it/751/notiziario-agro-giuridico-riforma-politica-agricola-comune-pac-2014-2020

**Comment by overclokk** [comment]
Ciao @Dubbo82 molto strano, quindi ora non sono attivi altri plugin? Provato con il tema standard?

**Comment by Dubbo82** [comment]
ciao!
grazie per la celere risposta!
allora casistiche:
tema base di wordpress, con plugin attivato questo fa il suo dovere sugli articoli e pagine (non vedo l'home ma credo sia per degli shorcode del tema che si porta dietro)
tema sito con plugin attivato:gli articoli con moltissimo test non vengono visualizzati, togliendo un po di testo  o comunque riducendo i dati caricati (sidebar, immagini, ecc...) viene visto correttamente.
tema sito con plugin attivato + wp3 total cache attivo:viene visualizzato tutto ma una volta accettate condizioni cookie e ricancelladoli, pulendo file temp ecc... il banner non viene piu visualizzato/non funziona
Non volendoci perdere troppo tempo credo che aggiusterò gli articoli troppo lunghi riducendo la sidebar.
Se hai qualche idea fammi sapere, lascio l'articolo della PAC:
http://www.avvocatogianlucamengoni.it/751/notiziario-agro-giuridico-riforma-politica-agricola-comune-pac-2014-2020Con il problema ancora per qualche giorno
Per vecchie versioni di wordpress 3.x che non posso aggiornare purtroppo qualche suggerimento?
Grazie,Diego
Date: Wed, 17 Jun 2015 15:48:51 -0700

**Comment by overclokk** [comment]
Ciao @Dubbo82 per le vecchie versioni di WordPress direi che con la prossima release abbiamo allargato il supporto.

Per quanto riguarda l'altro problema purtroppo da quello che mi dici direi sia proprio il template non sviluppato proprio bene visto che con il tema standard funziona correttamente, l'unica soluzione sarebbe contattare lo sviluppatore del tema.

**Comment by Dubbo82** [comment]
- Si sembrerebbe dovuto al tema provo a risolvere togliendo elementi alla sidebar non utili per i post che presentano quel problema.
- Grazie, magari fossero compatibili con la 3.x, altrimenti avrei dovurto ripiegare su soluzioni "a mano" e sarebbe stata una cosa molto onerosa in termini di tempo: avete una previsione del rilascio della versione del plugin compatibile con questa versione?
  un caro saluto,Diego

Date: Sun, 21 Jun 2015 03:05:43 -0700

**Comment by overclokk** [comment]
Spero nei prossimi giorni di riuscire a pubblicare la nuova release.

**Comment by Dubbo82** [comment]
Ottimo! grazie e buon lavoro! :)

Date: Mon, 22 Jun 2015 06:35:32 -0700

**Comment by Dubbo82** [comment]
ciao Enea,
ho visto l'aggiornamento, grazie.
Per siti davvero obsoleti (wordpress 3.4.2) sai per caso se il plugin funziona bypassando il controllo iniziale?Te lo chiedo perchè dovrei contestualmente migrare su un altro server per la versione di php 5.3
un saluto,Diego

Date: Mon, 22 Jun 2015 06:36:02 -0700

**Comment by overclokk** [comment]
Ciao @Dubbo82 attualmente lo abbiamo reso compatibile con una 3.5, inferiori non ho avuto modo di provarla, ho aggiunto un check sulla versione e se è inferiore non te lo attiva, dovresti fare delle prove mettendo un numeri di versione inferiore e vedere se hai problemi, la versione la puoi impostare nel file principale del plugin.

**Comment by Dubbo82** [comment]
ok grazie non appena migrato su php 5.3 provo con la modifica sul check e ti notifico i risultati, magari può servirti saperlo.
Diego

Date: Wed, 24 Jun 2015 15:25:50 -0700

**Comment by overclokk** [comment]
:+1:

**Comment by Dubbo82** [comment]
Ciao Enea,
con php 5.3 e wp 3.42 il plugin non blocca i cookies come nelle versioni più avanzate
Un saluto,Diego

Date: Thu, 25 Jun 2015 05:00:39 -0700

**Comment by overclokk** [comment]
Ok, quindi il minimo è 3.5
Ma ti da qualche errore?

**Comment by Dubbo82** [comment]
Errori in particolare, no.Non compare il banner e i cookie non vengono bloccati.
Diego

Date: Thu, 25 Jun 2015 15:40:36 -0700

**Comment by andreapernici** [comment]
In questi casi i problemi sono derivanti dal tema con alta probabilità e non dalla versione.

Questo è abbastanza verosimile quando non appare neanche il banner.
