### ISSUE TITLE
Sembra che non succeda nulla...

### ISSUE THREAD

**Issue by luckyjdesign** [overclokk/italy-cookie-choices#91]
Premetto che non programmo, al massimo posso copiare/incollare.
Ho installato Cookie Notice, che salva un cookie chiamato cn_cookies_accepted()
Ho installato il plugin Third Party Cookie Eraser, impostandolo così:
Cookie Name: cn_cookies_accepted()
Cookie Consent Value: true
Your message to show: il mio messaggio
Ho caricato su una schermata in incognito il sito su cui ho installato questi plugin, ed o fatto varie prove sia negando che fornendo il consenso tramite click sul banner creato con Cookie Notice.
Il messaggio non compare in nessun caso, inoltre monitorando il sito con Ghostery, l'estensione per Chrome che mostra quali tracker vengono utilizzati dal sito che visiti, ho visto che appena si carica il sito si carica anche il tracker di Google Analytics, cosa che speravo di eliminare fintanto che non avessi acconsentito. Dove sbaglio? Grazie per l'impegno e il tempo che ci avete messo, buon proseguimento

**Comment by overclokk** [comment]
Ciao @luckyjdesign disinstalla i due plugin e installa Italy Cookie Choices e vedi se risolvi.

**Comment by luckyjdesign** [comment]
Grazie mille. Ho disattivato i due plugin, ho installato e attivato Italy cookie choice, sembra funzionare perfettamente (finchè non acconsento all'utilizzo dei cookies non compare nulla) però non sono riuscita ad impostare la scelta "nego il consenso", in modo che se un visitatore che non vuole cookies continua a non vedere nulla oppure gli appare un messaggio "grazie arrivederci senza cookies il sito non funziona". Come posso fare, è previsto nel plugin? Magari interagendo con Third Party cookies eraser?
Grazie ancora

**Comment by overclokk** [comment]
Ottimo :+1: 
L'opzione per negare il consenso non c'è, anche su questo punto c'è poca chiarezza da parte del garante, stiamo aspettando di avere maggiori informazioni.

**Comment by andreapernici** [comment]
La negazione del consenso si può fare spiegando nell'informativa come gestirla via Browser.

Farla diversamente è una finezza, ma non è necessaria a meno di cookie di profilazione propri.
