### ISSUE TITLE
Non riesco a bloccare Facebook

### ISSUE THREAD

**Issue by gianpy81** [overclokk/italy-cookie-choices#92]
Ciao, come da oggetto non riesco a bloccare gli script di Facebook pur avendoli inseriti nel plugin, dopo averli messi mi blocca tutto il sito. Utilizzo il plugin ufficiale Facebook Wordpress. Grazie.

**Comment by overclokk** [comment]
Ciao @gianpy81 hai inserito lo snippet come lo trovi nel sorgente di pagina?

**Comment by overclokk** [comment]
Ciao @gianpy81 hai poi risolto?
