### ISSUE TITLE
Div che se ne va per conto suo

### ISSUE THREAD

**Issue by gianpy81** [overclokk/italy-cookie-choices#93]
Ciao, come da oggetto, dopo aver attivato il plugin, un div all'interno della sidebar se ne va per conto suo (ovvero si posiziona al di sotto del footer), il div contiene una pubblicità (juiceADV) e contiene i seguenti parametri:

```
    #juice-banner {
        width: 300px;
        height: 250px;
        margin-left: 10px;
    }   
```

**Comment by overclokk** [comment]
Ciao @gianpy81 per questo avrei bisogno di vedere una url con il plugin attivato e settato dove avrai preventivamente pulito una eventuale cache se hai installato plugin per le performance.

**Comment by overclokk** [comment]
Con la versione 2.2.0 ora è possibile customizzare l'intero CSS dimmi se il problema è risolto @gianpy81
