### ISSUE TITLE
Cookie Law Info + Italy cookie choices

### ISSUE THREAD

**Issue by kkri** [overclokk/italy-cookie-choices#94]
Ciao e grazie per il vostro lavoro. Se uso il plugin Cookie Law Info per l'informativa breve, per creare e inserire nell'informativa estesa l'elenco dei cookies utilizzati e usare lo shortcode che cancella tutti i cookies, riesco ad utilizzare il vostro plugin solo per il blocco preventivo, o c'è qualcosa che va in conflitto? Grazie.

**Comment by kkri** [comment]
Scusa, ma sono bloccata. Mi confermeresti se ci sono problemi di conflitto utilizzando Cookie Law Info come ho scritto ieri, oppure posso procedere ad adeguare diversi siti con quel metodo? Grazie.

**Comment by overclokk** [comment]
Ciao @kkri 
non so se ci sono problemi, non ho mai provato, ad ogni modo con questo plugin non hai bisogno di usarne altri.

**Comment by kkri** [comment]
Ciao @overclokk 
Volevo utilizzare parzialmente Cookie Law info, che ho visto usano/usavano in molti perchè ha di buono un banner con  bottoni e grafica gradevole e immediata, la possibilità di creare una griglia per l'elenco dei cookies, e uno shortcode che dà la possibilità all'utente di cancellare tutti i cookies con un click. Immagino vada semplicemente a togliere il cookie del consenso dato: non si potrebbe aggiungere almeno quest'ultima funzionalità al vostro plugin, se non è troppo oneroso? Grazie.

**Comment by overclokk** [comment]
@kkri nella prossima release ci sarà la possibilità di usare un CSS custom così si potrà personalizzare il banner a piacere.

L'elenco dei cookie non sarà mai perfetto, il browser è sempre lo strumento più veritiero, anche la cancellazione è sempre meglio gestirla dal browser.

**Comment by kkri** [comment]
@overclokk  Scusa non mi sono spiegata: c'è impostato un custom post type con 3 campi (nome cookie, scadenza, funzione) dove inserire MANUALMENTE i cookies trovati con qualche altro strumento (es. Ghostery + Chrome), poi il layout è visualizzato all'interno di una tabella inseribile tramite shortcode nell'informativa estesa. La cancellazione dovrebbe essere esatta perchè poi ripropone il banner dell'informativa breve come l'utente non avesse mai dato il consenso.

**Comment by overclokk** [comment]
Quando hai una lista di cookie non ti serve uno shortcode per inserirli, basta che crei una lista puntata nella pagina, non è obbligatoria una tabella.
Per la cancellazione basta spiegare all'utente come fare tramite browser.

**Comment by kkri** [comment]
ok, grazie.

**Comment by overclokk** [comment]
Di nulla, per qualunque altra domanda non esitare a chiedere.

**Comment by kkri** [comment]
Grazie di nuovo, anche perchè è domenica ... ma vedo che sono in buona compagnia ... Nei prossimi giorni dovrò sistemare dei siti un po' più rognosi, più che altro che hanno diversi cookies. Non so se sarò in grado di identificare e bloccare cookies non bloccati dal plugin inserendo il codice nel box che avete messo per questa funzione. Come devo procedere per trovare il codice giusto da copiare/incollare nel box? E' possibile bloccare qualcosa contenuto nei widgets tramite il box del plugin widget logic? (v.immagine).
![blocco-cookie-widget](https://cloud.githubusercontent.com/assets/6691744/8272392/c8bae6e2-1840-11e5-9ef4-8c688fa0417b.jpg)

**Comment by overclokk** [comment]
Hai già provato a vedere la wiki? https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/Custom-script

**Comment by kkri** [comment]
Adesso ho visto e capito come fare per trovare gli scripts.Nel box di widget logic prende HTML e PHP, uno script non credo lo accetti, ma adesso vedo se sarà necessario per qualche sito. 
Due domande al volo: non si potrebbe differenziare il messaggio che va nell'informativa breve da quello che va al posto dei widgets bloccati prima del consenso? Tipo mettere nei box "rossi" dei widgets "per visualizzare questo elemento è necessario accettare i cookies" Diventa meno pesante graficamente, anche se sempre abbastanza invadente e visibile ;) 
Se nelle impostazioni non si spunta che si deve vedere il banner dell'informativa breve, non fa neanche il blocco preventivo? Grazie.

**Comment by andreapernici** [comment]
Puoi già differenziare il messaggio di blocco tra informativa breve e box inpage.

**Comment by kkri** [comment]
Ah, bene! Invece se nelle impostazioni non si spunta che si deve vedere il banner dell'informativa breve, non fa neanche il blocco preventivo?

**Comment by andreapernici** [comment]
In teoria se non devi mostrare il banner non hai bisogno di bloccare nulla.

**Comment by kkri** [comment]
Sì è vero, ma comunque sono svincolabili l'una dall'altra le 2 funzioni?

**Comment by andreapernici** [comment]
A che pro?

**Comment by kkri** [comment]
Per utilizzare il plugin Cookie Law Info per il banner, lo shortcode che cancella tutti i cookies e il sistema di inserimento dei cookies per la creazione di una tabella da inserire nell'informativa estesa ed esportabile anche in altri siti senza bisogno di reinserire tutto.

**Comment by andreapernici** [comment]
Fare il bottone di cancellazione di tutti i cookie ci vuole poco. Se hai pazienza lo metteremo anche se non è necessario. 

Per la creazione della tabella anche quella non è necessaria per la normativa italiana quindi non credo sia una cosa intelligente investire tempo di sviluppo per aggiungere qualcosa che non servirà a nessuno.

In ogni caso dal punto di vista del nostro plugin ha poco senso fare una cosa del genere. Lo segnamo, ma non ti posso garantire che sarà introdotto.

**Comment by kkri** [comment]
Certo che ho pazienza per il bottone di cancellazione ;).
Per la tabella: è vero che non è necessaria, ma nei siti dove ci sono diversi cookies l'impaginazione è più ordinata, ma soprattutto, una volta inseriti (ognuno in un custom post type) si crea una sorta di db che si può esportare in altri siti. 
Comunque, grazie infinitamente per il vostro lavoro, siete supercompetenti, ma non credo di dirvi una novità ...

**Comment by andreapernici** [comment]
Sul database di porzioni di legalese ci stiamo ragionando...ma servirebbe un legale :D

**Comment by kkri** [comment]
Non posso aiutarvi: sono/ero una ragioniera ... e in più, "pentita" ... ;)

**Comment by overclokk** [comment]
Non serve un custom post type per fare una lista di cookie

**Comment by kkri** [comment]
Credo perchè così si può esportare e riutilizzare, no?

**Comment by overclokk** [comment]
I custom post type servono solo per creare contenitori speciali che pagine e post non possono gestire.

**Comment by kkri** [comment]
Sì, ma sono strutturati in campi per cui sono dei "records" di una tabella. Non riesco a trovare nella descrizione del plugin dove dice che si possono esportare e reimportare, ma non importa, grazie.

**Comment by overclokk** [comment]
Quello è anche uno dei motivi per cui esiste questo plugin ;-)
