### ISSUE TITLE
Problema background color e text color

### ISSUE THREAD

**Issue by marcosiino** [overclokk/italy-cookie-choices#95]
Ciao, ho installato il tuo plugin su circa un centinaio di siti prima che implementavi la possibilità di scegliere il colore di sfondo e il colore del testo nel banner dell'informativa e tutto funzionava correttamente. Adesso, dopo aver aggiornato il plugin su parecchi siti, mi ritrovo il banner con sfondo trasparente che quindi praticamente risulta illeggibile. A quanto pare dopo aver aggiunto la possibilità di modificare queste proprietà, non hai lasciato dei valori di default, e nel caso in cui un utente aggiorna il plugin nel CSS non viene specificato un valore di default per la proprietà background-color e color e quindi il banner si vede malissimo. Puoi per favore impostare dei colori di default nel caso in cui non sono stati selezionati dopo l'aggiornamento del plugin ? L'ideale sarebbe sfondo nero e testo bianco.

Il problema è che adesso mi tocca, come minimo riaggiornare il plugin su tutti i 100 siti dove l'ho installato prima di questa modifica :( oppure impostare manualmente il colore di sfondo e del testo.

Grazie.

**Comment by weAreCoine** [comment]
Ciao, stesso problema qui: www.italiapokertube.com. In più, non funziona l'accettazione via scroll o continuazione navigazione. I cookie invece vengono bloccati alla perfezione. ;) Qualche idea per la soluzione?

In ogni caso complimenti e grazie per l'ottimo lavoro! ;)

**Comment by overclokk** [comment]
@marcosiino @FabrizioReder sui siti in cui ho provato funzionava correttamente, il valore di default era impostato e non ho avuto questo problema, comunque faro subito dei test per capire meglio cosa possa essere successo.

Grazie

**Comment by marcosiino** [comment]
OK grazie!

Il giorno dom 21 giu 2015 11:43 Enea notifications@github.com ha scritto:

**Comment by overclokk** [comment]
@marcosiino prova la nuova versione 2.2.0 e dimmi se il problema è risolto

**Comment by marcosiino** [comment]
Il problema è che ormai ho reimpostato manualmente i colori su quasi tutti
i siti, dovrei vedere se è rimasto qualche sito con la vecchia versione del
plugin in cui non ho ancora reimpostato i colori, e aggiornarlo alla nuova
versione per vedere se vengono messi dei colori di default, nei prossimi
giorni provo e ti faccio sapere :)

Grazie mille intanto!

Il giorno mer 24 giu 2015 23:05 Enea notifications@github.com ha scritto:

**Comment by overclokk** [comment]
@marcosiino mi spiace non essere riuscito ad aggiornare in tempo ma in questa versione c'è stato molto lavoro dietro e poi anche causa lavoro e Web Marketing Festival ho fatto il possibile.

**Comment by marcosiino** [comment]
Figurati, ci mancherebbe, è già tanto che ci hai risparmiato tempo
sviluppando questo plugin :)

Il giorno gio 25 giu 2015 00:29 Enea notifications@github.com ha scritto:

**Comment by overclokk** [comment]
:+1:

**Comment by marcosiino** [comment]
Ho provato ad aggiornare un sito e installando la nuova versione del tuo
plugin mi dice che richiede PHP 5.3, hai fatto questa modifica recentemente
nell'ultimo update? Non è possibile usare una versione inferiore di PHP
(alcuni server non posso updatarli al momento a PHP 5.3)

Il giorno gio 25 giu 2015 13:57 Enea notifications@github.com ha scritto:

**Comment by overclokk** [comment]
Il plugin prima supportava dalla 5.4 in su e con questo aggiornamento l'abbiamo portata alla 5.3.26 quindi abbiamo aumentato il supporto a versioni precedenti, mai supportate versioni precedenti la 5.3

**Comment by marcosiino** [comment]
Strano, forse non mi ero accorto di quell'errore prima allora, ok grazie!

Il giorno gio 25 giu 2015 17:02 Enea notifications@github.com ha scritto:

**Comment by overclokk** [comment]
Strano perché con versioni precedenti mandava in errore il sito.
