### ISSUE TITLE
Ho un sito in wordpress in WPML : come lo installo ???

### ISSUE THREAD

**Issue by robertoneohabitat** [overclokk/italy-cookie-choices#98]
Ho un sito in wordpress in lingua italiana e inglese , come lo installo ??
lo chiedo perchè da wpml ho settato lingua inglese , ma il messaggio non esce nella versione inglese ma in quella in italiano ... come posso fare sia la versione inglese che quella italiana ??

Vi ringrazio per la risposta e apprezzo lo sforzo che state facendo per realizzare un prodotto/servizio di qualità....
RS

**Comment by overclokk** [comment]
Ciao @robertoneohabitat nella prossima release ci sarà il supporto per il multilingua dei plugin WPML, Ceceppa e Polylang, a breve sarà disponibile.

**Comment by overclokk** [comment]
Con la versione 2.2.0 sono supportati i plugin WPML, Ceceppa e Polylang
Domanda chiesta anche in questa issue #31
