### ISSUE TITLE
Revolution slider

### ISSUE THREAD

**Issue by markust4w** [overclokk/italy-cookie-choices#99]
Ciao Andrea,

revolution slider viene bloccato, come posso fare per "bypassare"? 

Grazie

**Comment by overclokk** [comment]
Ciao @markust4w hai seguito le indicazioni sulla wiki? https://github.com/ItalyCookieChoices/italy-cookie-choices/wiki/Custom-script

**Comment by markust4w** [comment]
Perfetto grazie mille! Ho visto infatti avete fatto nuova versione con questa possibilità, molto utile a mio avviso, in caso contrario avrei dovuto mettere mano al plugin :(

**Comment by overclokk** [comment]
Ottimo, dimmi solo se hai risolto il problema

**Comment by markust4w** [comment]
Si risolto

**Comment by markust4w** [comment]
Grazie

**Comment by overclokk** [comment]
Ottimo, perfetto :-)
